### ISSUE TITLE
Synoptic Panel - Drill through

### ISSUE THREAD

**Issue by Goofr** [okviz/free-visuals#1]
Hi,

I can't get drillthrough working on this visual.
Is this possible?

Thanks

Frank

**Comment by blipsAndChitz** [comment]
I would appreciate this feature as well, e.g one panel for each level of building, with second panel for floor plan of selected level. 

Thank you.

**Comment by AndreasRothmann1984** [comment]
Hi, is there any drillthrough chance now?
Thanks in advance
Andy

**Comment by DiscoverEI** [comment]
Is there now either a workable option for drill-through or auto zoom to selected feature in the latest edition of the updated Synoptic Panel? Thanks!

**Comment by tate-bowman** [comment]
Just chiming in -- drillthrough would be a much appreciated feature!

**Comment by xsg13** [comment]
Yes, this would be awesome!

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
