### ISSUE TITLE
Card with State (OKViz) version 1.4.2 not working with Variance

### ISSUE THREAD

**Issue by wendygaiden** [okviz/free-visuals#10]
I've been trying to add states to a measure using Card with States visual by OKViz. For example, using MRT as a measure (Median Resolution Time) by comparing the value to the previous month (target). However, the state is not changing the color for variance, for example, if MRT is going down compared to previous month, the variance will be negative and in this case, it should be State C, as stated but it's showing up as State A color. It seemed to be one way or the other and I cannot get both negative and positive trend to work. I tried Absolute Value and percentage over the target but not able to get it to work :'(

![Cards state not working](https://user-images.githubusercontent.com/50471526/57498150-56d3c900-730d-11e9-94d9-dca185564095.png)
[Test MRT.zip](https://github.com/okviz/ColorHelper/files/3164647/Test.MRT.zip)

Here's the link to the[ pbix file](https://www.dropbox.com/sh/h9fg0nz9695p6s0/AADFkUi5IXbfwnIwQN8U1MVxa?dl=0): 

Appreciate any help/tip,
Wendy

**Comment by danieleperilli** [comment]
The state is calculated by comparing the Measure or the State Measure (if exists) with the states. In the provided example the Measure is 8.2 and the first state is 1. So you are saying: "If the Measure > 1 then assign the Red color to the variance label." After the first match, the other conditions are ignored.

**Comment by wendygaiden** [comment]
This is a great visual but I don't think you understand the issue. It seemed to work if you have a static target/goal, but not when you are comparing to a previous month/quarter. There were a few more questions raised in Power-BI community and it seemed that this visual only works one way not the other. 
https://community.powerbi.com/t5/Desktop/OKViz-Cards-with-States-Can-t-figure-out-what-field-to-use/td-p/647786
https://community.powerbi.com/t5/Desktop/Cards-with-states-States-for-positive-or-negative-number/td-p/474009
https://community.powerbi.com/t5/Desktop/Card-with-States-to-show-This-month-vs-last-month/td-p/650564
https://community.powerbi.com/t5/Desktop/Values-and-variance-status/td-p/500832

For example, if I want the variance to show red when it's negative, and green when it's positive, how do you get it to work? Maybe my understanding is wrong and I shouldnt be using this card. 
Would appreciate the explanation.

**Comment by danieleperilli** [comment]
In your example you set the conditions with absolute values. If you want to compare the change over the target you must set the Value type field appropriately. 
<img width="169" alt="Power_BI" src="https://user-images.githubusercontent.com/9072177/58240040-6a8a2100-7d4a-11e9-92cf-d81e6bd446eb.png">

About positive and negative: in the current version of Card with States is not possible to define different comparison operators per condition - e.g. you can't say If Condition 1 < 0 Then Red AND If Condition 2 > 0 Then Green. In the next version (currently under review by Microsoft) you will be able to do so.

**Comment by wendygaiden** [comment]
Thanks Daniel! Any ETA when the new version will be out?

**Comment by danieleperilli** [comment]
It should be published by the end of the next month.
