### ISSUE TITLE
Card with States - States base color does not affect background

### ISSUE THREAD

**Issue by Bartbeckers** [okviz/free-visuals#100]
I want to change the background color (red or green) with the States in the 'Card with States by OKViz' visual (version 1.4.2). Unfortunately, the states doesn't affect the background of the base color. 

A workaround is to change the default background of the visual to red. However, doing this I have a red border (even when the visual background should change to green based on the states).

Looking forward to the solvation of this issue.

**Comment by danieleperilli** [comment]
Unfortunately, it's a known issue. The fix is included in the new version - it should be available on the marketplace by this month.
