### ISSUE TITLE
Card with States - Variance Indicator

### ISSUE THREAD

**Issue by nicola-dragoni** [okviz/free-visuals#101]
First off, I LOVE the Card with States KPI visual.
The flexibility it offers is amazing, and all my clients love it.

However, the other day I experienced a weird result.

As you can see from the image, the KPI for "Profitto Netto" shows the variance in a format which is no very appealing to the eye.

In the table on the bottom of the page I framed the data which are used to calculate the variance.
I would expect the variance to just have a negative number, since the difference between -618,335 and -526,662 is a negative number.

Is there something I am missing?
Is there a workaround?

![image](https://user-images.githubusercontent.com/52753209/74013373-9c9ceb00-498c-11ea-85b5-fbf218599331.png)

**Comment by danieleperilli** [comment]
It's a known issue, but we already solved in the new version a few months ago. Unfortunately, releasing the update in the marketplace is requiring a lot of time (more than usual) – hopefully, it will be available by this month.

**Comment by vanchikites** [comment]
I also love cards with states, my business partners love the simplicity of it!  I'm having a similar issue with percentage variance type.  My measure is -455, target value is -123 but it's displaying a +269.9% variance.  It should display -269.9%.  Will that also be corrected in the new version?  Or is there a workaround?
![image](https://user-images.githubusercontent.com/62621759/77472642-9fdc2100-6dea-11ea-90e0-6db67d018bb3.png)

**Comment by danieleperilli** [comment]
@vanchikites Do you have any report to share? The bug should be fixed in the next version, but to be sure I can test it with your data. Please send to support@okiziv.com if it's private.

**Comment by vanchikites** [comment]
Sure I will email you the example below.  It won't let me attach the actual file here.  Thanks in advance for our help!
![image](https://user-images.githubusercontent.com/62621759/77689575-4275da80-6f78-11ea-9415-5b67b554ec7c.png)

**Comment by danieleperilli** [comment]
Thanks for your file. I do confirm that the new version solves this issue. It's currently under review by Microsoft.
<img width="881" alt="Example_Card_with_States_-_Negative_Values_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/78035381-53a05c00-7369-11ea-8c63-fcbc6c2aa8ea.png">

**Comment by ArieDavista** [comment]
When can we expect the new version in AppSource? The description on AppSource says version 1.6.3.0 but when downloaded it is version 1.4.2.

**Comment by danieleperilli** [comment]
A couple of weeks, probably. We have no control over that.
