### ISSUE TITLE
Synoptic Panel - Some shapes not selectable

### ISSUE THREAD

**Issue by Domachin** [okviz/free-visuals#102]
Hello,
I have some SVG images with diagrams where both blocks and connections must be linked to data (an example is attached).
The issue is that some of them are not selectable even if i can see from the color that they associate correctly, and also they do not show the label if hovered with the mouse (in the attached file some examples are the blocks in the upper left corner).
Searching in the SVG file they are present and similar to the others, so i thought that the problem was an excessive file dimension, but even zipping the file the problem remains, independently from the PBIX file into which the SVG is embedded and from the data to which it is connected.
Maybe the Synoptic Panel itself has a limitation to the complexity of the image, or there is something incompatible in this SVG template?
[ECH.zip](https://github.com/okviz/free-visuals/files/4192628/ECH.zip)

**Comment by danieleperilli** [comment]
I think the problem is the number of nested layers. I suggest opening the svg with an advanced tool such as Illustrator and cleaning the layout structure.
