### ISSUE TITLE
Bullet Chart - Gridline Color

### ISSUE THREAD

**Issue by kkouvaras** [okviz/free-visuals#103]
Can an enhancement be made to allow the color of the gridlines to be altered from the default? This is an option available on standard Power BI bar charts under the Value axis. The default color for the OKViz Bullet Chart is hard to see over some lighter non-white background colors.

**Comment by danieleperilli** [comment]
We will consider in future updates. Thanks for suggesting.

**Comment by danieleperilli** [comment]
Added in v2.2.9.4
