### ISSUE TITLE
Synoptic Panel - Showing (Blanks) in Label 

### ISSUE THREAD

**Issue by kulchandraneupane** [okviz/free-visuals#105]
Synpotic Panel is showing (Blank) when i am using PlayAxis Custom visual to play the heat for different day. Please see below screenshot. also attached PowerBi File
[Uploading Heatmap_Test_04-Feb-2020.zip…]()

![Blank while playing synoptic panel_](https://user-
![Blank while playing synoptic panel_](https://user-images.githubusercontent.com/61282871/74945849-69436d00-541e-11ea-9854-2a0d1301a3aa.png)
images.githubusercontent.com/61282871/74945518-e6baad80-541d-11ea-9f1f-1ce51be8c48d.png)

**Comment by danieleperilli** [comment]
Please, try to attach it again, I can't download the file.
