### ISSUE TITLE
Smart Filter - Has the visual implemented the Rendering Events API?

### ISSUE THREAD

**Issue by saviourofdp** [okviz/free-visuals#106]
Scroll down to see the Custom Visuals Rendering Events API section on this blog post 
https://powerbi.microsoft.com/en-us/blog/power-bi-developer-community-january-update-2/

Some functionality in our embedded app relies on the report's rendered event and we're seeing issues where it's being fired before the visuals have properly rendered. We're theorising that some of the visuals we use haven't implemented this which may be causing the problem.

**Comment by danieleperilli** [comment]
I do confirm that Smart Filter doesn't support this feature yet. We are evaluating a new update, but likely it will not be released before a couple of months.

**Comment by danieleperilli** [comment]
The new version including the rendering events has been sent to Microsoft for review, it could reach the store in 2/4 weeks.
