### ISSUE TITLE
Sparkline - Reference line on x-axis to signify today on sparkline

### ISSUE THREAD

**Issue by ghost** [okviz/free-visuals#107]
I have an application where I am using the sparkline to show information on a rolling window basis with some historical information and some projected/forecast information. I'm looking for a way to put a vertical reference line that indicates "today". Since I have projected information I cannot use the current data point color because it highlights a future date. Is there any way to accomplish this with the sparkline, if not would you consider this as a feature enhancement request?

Thank you for providing this very useful visual!

**Comment by danieleperilli** [comment]
Unfortunately, at the moment is not possible. We will consider it in the next updates. Thanks for posting.
