### ISSUE TITLE
Cards with States - Updating card position

### ISSUE THREAD

**Issue by eolay** [okviz/free-visuals#109]
When the Card was updated - in my old dashboard all cards changed their position! They fell down. What to do? Wait for updating or move them by hand?
![122](https://user-images.githubusercontent.com/32883095/76287635-f6f3d900-62b5-11ea-883e-ee20709a7c44.jpg)

**Comment by marcosqlbi** [comment]
We asked to Microsoft to rollback to the previous version, so your report should be back to the previous behavior in a few hours. In the meantime, it would be useful if you can create a small report with the same issue so we reproduce the problem and fix it in the next release.

**Comment by eolay** [comment]
> We asked to Microsoft to rollback to the previous version, so your report should be back to the previous behavior in a few hours. In the meantime, it would be useful if you can create a small report with the same issue so we reproduce the problem and fix it in the next release.

Thank you so much! It's ok now.
I get the source of the problem:
In the old version, the Card with States was not aligned with the standard Card. You can see it on the screenshot below. 
So users need to change card's height and position to align various cards by hand. 
Then you fixed the aligned problem, but now cards jumped in all reports. 
I'm not sure, that it is possible now to change the alignment of Value in Card with states and not brake the old reports... 
Maybe you can give the user the capability to choose the version? And if the user uses the old version, cards would not be updated automatically. 
I add the dashboard for example. Not the same, but good enough (I hope).
![цукцууу](https://user-images.githubusercontent.com/32883095/76339737-8d061e80-630b-11ea-89cb-926fc73670e0.jpg)
![1222](https://user-images.githubusercontent.com/32883095/76339742-8d9eb500-630b-11ea-9255-2976a4c47fa5.jpg)

[Example.zip](https://github.com/okviz/free-visuals/files/4313811/Example.zip)
