### ISSUE TITLE
Sparkline - Target Value not displayed correctly

### ISSUE THREAD

**Issue by tylercmsft** [okviz/free-visuals#11]
![Sparkline_Error_TargetValue](https://user-images.githubusercontent.com/30120831/57951420-9e2efc00-78af-11e9-9804-4d212da662ab.png)
When adding a Target Value, the resulting line chart is a flat horizontal line; this occurs with or without a category.  If I move the Target Value to the "Values", everything is displayed correctly.

**Comment by Suzanvane** [comment]
I have the exact same problem, using target with seasonality, showing up as a flat line.  I presume this is a bug. Can this please be fixed? It is such great visual to use, but now unfortunately useless.

**Comment by tylercmsft** [comment]
Any updates?

**Comment by torben87** [comment]
Your visual is by far the best for visualising line/area charts in small multiples in Power BI. If only the target values bug could be fixed, this would be an amazing visual for our business needs! Is there any update/estimate on when this will be fixed?

**Comment by danieleperilli** [comment]
We planned several updates for our visuals, but the problem is that we have limited resources. Anyway, it is something we will do by the next quarter, probably.

**Comment by dgumpper** [comment]
Is this still on the radar for first quarter of 2020? Thank you! Kind regards: David

**Comment by danieleperilli** [comment]
@dgumpper Sorry for the late reply. We are working on an updated version that probably will be released this month.

**Comment by EversBart** [comment]
Hi Guys, are you still working on this problem?

**Comment by meertenhamer** [comment]
Very good and helpful visual. Would be great if the target wouldn't be static.. Is this something that will be released?

**Comment by Suzanvane** [comment]
Hi, This is so much needed. Love the visual, but can't use it without a dynamic target bij month/year. Could you please inform us on any foreseen update?

**Comment by danieleperilli** [comment]
Unfortunately, we have suspended the release of updates on this visual, except for security bugs. I have added an On-Hold tag and closed the issue; I will reopen it when we begin actively working on the project again.
