### ISSUE TITLE
Cards with States - culture code not working properly

### ISSUE THREAD

**Issue by Jayclaw** [okviz/free-visuals#110]
After the latest update the numbers in the visual are in US format no matter what culture code is selected. This is also the case when selecting "Auto" culture code. 

E.g. when selecting Norwegian culture code, the decimal separator is still "." instead of ",".

**Comment by danieleperilli** [comment]
Thanks for reporting. We reverted the visual to the previous version and identified the issue which will be fixed in the next update.
