### ISSUE TITLE
display license info on visuals every month

### ISSUE THREAD

**Issue by macrovan** [okviz/free-visuals#111]
This is Chen Yue from Beijing China, I’ve purchased license for Smart Filter Pro for Power BI since July 2019, payment starts on every 9th, to check the payment details please refer to subscription #193479. 

However almost every month, below warning message will display on the visuals, I’ve tried to click the link of “Verify license”, nothing happened.
![license_warning](https://user-images.githubusercontent.com/49434701/76377366-a8ae0b00-6385-11ea-91cc-d4d0bb1ec8ca.png)

 
Furthermore, I closed all options to check update, but above warning always displays every month. This warning display makes trouble to me, I need to show report to boss every week, he suspected I’m using Smart Filter Pro illegally. 
![panel](https://user-images.githubusercontent.com/49434701/76377390-b8c5ea80-6385-11ea-9e9c-e954c000ce50.png)

 

Could you show me how to close the license info display manually, or turn it off until I’m not paying the license fee any longer? Thanks in advance.

**Comment by danieleperilli** [comment]
Hi Chen, 
If you have the two options "Send telemetry" and "Check for updates" disabled, the visual can't automatically verify the license through the Internet, so you see that message. 
In this case, you have to manually replace the visual every time your subscription expires with the one provided you via email – if leave one of the above options enabled, the visual automatically verify the license and doesn't bother you anymore.
Please, continue this thread by writing to support@okviz.com; this repo is only for free visuals, thanks.
