### ISSUE TITLE
Card with States 1.6.2 - Availability

### ISSUE THREAD

**Issue by SeanPowerBI** [okviz/free-visuals#112]
@danieleperilli 
Please make 1.6.2 available somewhere!
I spent literally a whole day adjusting all my cards to make them look right.
I experienced all issues described however I was able to fix all of them in the formatting options of 1.6.2.
Yes conditional transparency changed to white however all you had to do is go and select NO FILL.
(Its a bit confusing because it still showed white in the formatting options but the card was transparent)
The down/up arrows became very small I guess they defaulted to size 8 but all you had to do is change their size in the formatting options too.
The thing I had do most is get rid of the new show template button which showed up in all my cards.
Some of the cards that display a Change from Target number and an arrow and text below the main measure had to be adjusted from Middle to Top and slightly moved to be at the same exact spot in the report as they were before but again that was all do-able now I have to move those again.
Please can you make Card with States 1.6.2 available somewhere
Thank You!
Sean

**Comment by danieleperilli** [comment]
Sean, I'm fixing all the issue reported by the users before submitting an updated version - I'm sorry you spent your time, but we are on the very same page :)
