### ISSUE TITLE
Card with States - Not Rendering in Chrome

### ISSUE THREAD

**Issue by CCLNTN** [okviz/free-visuals#113]
The card with states visual is not rendering in chrome. 
This behavior is sporadic. Not all computers within the same network exhibit this behavior.
I'll send a copy of the pbix file via email as I cannot make public

**Comment by danieleperilli** [comment]
We reverted the visual to the previous version - probably not all the clients have updated it yet. To prevent possible future regressions, can you provide more details about your issue?

**Comment by CCLNTN** [comment]
Yes - 
This is a PowerBI report server environment - Version 1.6.7221.30698 (September 2019)
Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by danieleperilli** [comment]
I mean, which kind of error you saw? Just an empty box instead of the visual?

**Comment by CCLNTN** [comment]
Sorry, sent screenshots from other email. Yes just a blank box.
