### ISSUE TITLE
Bullet Chart - Matrix tooltip blank 

### ISSUE THREAD

**Issue by profantalex** [okviz/free-visuals#114]
Hi,

there seems to be an issue with the bullet chart 2.2.3 and a tooltip which has a matrix on it.
The tooltip with the matrix doesn't always load when you hover the mouse over visual for the first time, it's blank. When you hover over it next time then it loads correctly.

The strange thing is that when there is e.g. a line chart then it always loads correctly.
I'm attaching a sample pbix where I've hopefully made it clear. A screenshot of what I'm experiencing is attached too.
![BulletChart-tooltip_issue-screenshot](https://user-images.githubusercontent.com/62140520/76618573-36762b80-6529-11ea-805a-45ac93ce06bb.png)
[BulletChart-tooltip_issue.zip](https://github.com/okviz/free-visuals/files/4329369/BulletChart-tooltip_issue.zip)

Currently I'm using Feb 2020 Desktop but the issue is in the service too.

Thanks a lot!
Alexandra

**Comment by danieleperilli** [comment]
I just tried and it works for me; no blank tooltips on the service. I suggest opening a ticket with Microsoft because it doesn't seem an issue of the visual itself.
