### ISSUE TITLE
Can't display visual on web - Card with States

### ISSUE THREAD

**Issue by usernameb20** [okviz/free-visuals#115]
Hello,

I keep getting the same error displayed when I am using Card with States on web; it says can't display the visual and that I need to add it to a report first. It works perfectly fine on desktop but not on web and I am not sure I understand this error that's being displayed and there isn't much info about this issue on PowerBi's support.

Any idea how I can find my way around this?
![image](https://user-images.githubusercontent.com/62640934/77514193-6ad1dc00-6e87-11ea-93f2-78adcab3a28c.png)

**Comment by danieleperilli** [comment]
Can you share the report?
