### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by SSoret** [okviz/free-visuals#116]
Hi, since your new version 2.2.5, updated the 3/7/2020, i have problems with figures shown on axis.
How to replace the comma of the thousands separator with a space?
Change culture has no effects.
Thanks for your help.
Regards

**Comment by danieleperilli** [comment]
The new version is not yet available in the marketplace, you are using the v2.2.3 which has the bug you reported. They say it's updated, but it took 2-3 weeks to be really updated. Just right-click on the visual icon and press About to check it.

**Comment by SSoret** [comment]
Hi Daniele,

Since the last mail, i'd Survey the update of your component on the MS PBI marketplace but it not seems to be done.
Do you confirm?
Thanks.
Regards


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Daniele Perilli <notifications@github.com>
Envoyé : vendredi 27 mars 2020 08:05
À : okviz/free-visuals <free-visuals@noreply.github.com>
Cc : SSoret <ssoret@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [okviz/free-visuals] Bullet Chart (#116)


The new version is not yet available in the marketplace, you are using the v2.2.3 which has the bug you reported. They say it's updated, but it took 2-3 weeks to be really updated. Just right-click on the visual icon and press About to check it.

**Comment by danieleperilli** [comment]
Not yet. They rejected the submission for a minor bug. We already resent a new version, but every time the process restart we have to wait 2/4 weeks.

**Comment by SSoret** [comment]
OK Thanks!
Have a nice day!
Regards


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Daniele Perilli <notifications@github.com>
Envoyé : jeudi 14 mai 2020 13:42
À : okviz/free-visuals <free-visuals@noreply.github.com>
Cc : SSoret <ssoret@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [okviz/free-visuals] Bullet Chart (#116)


Not yet. They rejected the submission for a minor bug. We already resent a new version, but every time the process restart we have to wait 2/4 weeks.
