### ISSUE TITLE
Bullet Chart - Axis size (X)

### ISSUE THREAD

**Issue by metrico320** [okviz/free-visuals#118]
Hi, is there a way that the (X) axis can be adjusted so that the (absolute) results don't look that far apart.  In the Microsoft “cluster bar chart” you have the option: “log / linear”.  is there any alternative?  Greetings.

**Comment by metrico320** [comment]
> Hi, is there a way that the (X) axis can be adjusted so that the (absolute) results don't look that far apart. In the Microsoft “cluster bar chart” you have the option: “log / linear”. is there any alternative? Greetings.

![B919ED62-E35C-4C04-80AB-4E91AEAF9C56](https://user-images.githubusercontent.com/26695068/77858204-86aaea00-71c7-11ea-99a4-2dabce363631.jpeg)

**Comment by danieleperilli** [comment]
At the moment, is not possible. We will consider in future updates.
