### ISSUE TITLE
Bullet Chart - States misbehave if state value is 0

### ISSUE THREAD

**Issue by mucby** [okviz/free-visuals#119]
![okviz bullet chart](https://user-images.githubusercontent.com/62994720/78131757-e26db100-741b-11ea-8637-1018ef148e09.png)

Using version 2.2.3 from AppSource.

As shown in the picture, there are five states (see category B):

- light blue
- dark blue
- orange
- violet
- lavender

For category A **dark blue** is missing, so I would expect to have state values defined as 1-1-3-6-10.
Instead, the state values are 0-1-3-6-10. **light blue** should be missing.

[okviz bullet chart.zip](https://github.com/okviz/free-visuals/files/4414809/okviz.bullet.chart.zip)

**Comment by danieleperilli** [comment]
Fixed in the v2.2.6. It will released in 2/3 weeks (it depends on Microsoft timeline). You can try a private version from our website: https://okviz.com/bullet-chart/ (please note that this version is not certified and will not be updated automatically)
Thanks for reporting.

**Comment by mucby** [comment]
Thank you! I will need to wait for the certified version though.

**Comment by danieleperilli** [comment]
Of course, but please take a look to confirm it is solved.

**Comment by mucby** [comment]
I tried to already, but "the administrator has disabled..." ;-)
