### ISSUE TITLE
Synoptic Panel - State measures duplicated in colors settings

### ISSUE THREAD

**Issue by Arklur** [okviz/free-visuals#120]
The issue I'm facing is that instead of having the same number of items in the "Format > States" what I put in the "Fields > States", there are much more, as you can see here:

![](https://i.imgur.com/DqkJsER.png)

The number of items seems to be based on the distinct count of the values used in the "Fields > Category (or Subcategory)". Currently the workaround is to remove the field used in the "Fields > Category", that way the correct number of items show up in the list:

![](https://i.imgur.com/ta118T7.png)

Here is the sample report. I simplified it, the used measures are a little bit more complicated, but even with simple measures the issue still persist:
[okviz_synoptic_panel_state_colors.zip](https://github.com/okviz/free-visuals/files/4430922/okviz_synoptic_panel_state_colors.zip)

**Comment by johnalindogan** [comment]
Hi! I'd like to share that I am also encountering this same issue. The visual is still functioning despite the duplicate states being displayed under Format>States. My concern is that the visual gets extremely sluggish when I start adding more objects (100+). 

PowerBI Desktop Version: 2.79.5768.1082 64-bit (March 2020)
Synoptic Panel v15.0.0

**Comment by abfab96** [comment]
Hello,
I also am having this same issue. I haven't been able to get it to work no matter what I do. Any advice?

**Comment by abfab96** [comment]
@danieleperilli do you know of any workarounds that I can do/use while this bug is being repaired?

**Comment by bkelsowork** [comment]
Same issue for me. It seems that every area on the design is getting one of each of the states options made for it. I have 20+ possible state options and 150+ areas. So I get 3,000+ state options created in the format menu and am worried about performance issues.

In these screenshots of my test project, you can see how the colors states are being created many times over and over again.

![image](https://user-images.githubusercontent.com/112589295/187955499-9a7f4a17-07c5-4d92-a072-c88ac8932741.png)
![image](https://user-images.githubusercontent.com/112589295/187955600-f76f546f-596e-4727-88fa-3fd8d7e2e57f.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
