### ISSUE TITLE
Synoptic Panel - More data

### ISSUE THREAD

**Issue by CharlBo** [okviz/free-visuals#121]
Hello,
First of all I want to apologize for my translated English ...
I just noticed that the visual displays approximately 1000 data.
Is it possible to display more by settings or others?
Thank you in advance for your help.
Super visual, I will bluff my hierarchy !!!
CharlBo

**Comment by danieleperilli** [comment]
Without the incremental loading, which is a relatively new feature, not yet supported by the visual), the data limit of custom visuals is 30,000 rows. We will introduce the incremental loading before the end of the year, hopefully.

**Comment by leokonst8** [comment]
Hello,
Can you please change it to be up to 30,000 rows. It currently supports up to 1000.
The visual is amazing!
Thank you

**Comment by arthurcury** [comment]
Hello, Daniel.

Is incremental loading currently available? 

Thanks!

**Comment by ForTheLoveOfD365** [comment]
Hi Daniel,

Checking in on this thread, is the visualization still have a data limit of 30,000 rows?

Thanks!

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
