### ISSUE TITLE
Synoptic Panel - Crash when Saving

### ISSUE THREAD

**Issue by mmarsh105** [okviz/free-visuals#122]
I created my shop map in the synoptic designer and saved it. I can get it to load into Power BI and show data, but whenever I try to save the program it crashes.
There is no error code or anything to go along with it. Power BI just closes itself and there is no file anywhere to be found.
I don't seem to have a problem with any of the images from the gallery, only the images I've created myslef.

**Comment by danieleperilli** [comment]
Please provide a sample file (report + image).

**Comment by mmarsh105** [comment]
[Error 1.docx](https://github.com/okviz/free-visuals/files/4456798/Error.1.docx)
[Error 2.docx](https://github.com/okviz/free-visuals/files/4456800/Error.2.docx)
I finally got these error reports. They just showed up when I had the program open so I'm not 100% sure they are related to the main issue. Most of the time PowerBI just closes on it's own and all progress is lost with no error report

**Comment by mmarsh105** [comment]
[Error 3.docx](https://github.com/okviz/free-visuals/files/4456964/Error.3.docx)

**Comment by danieleperilli** [comment]
We need the pbix file and the svg image, these logs are for reporting issues to Microsoft.

**Comment by mmarsh105** [comment]
Hopefully this works and is what you need. I apologize as all of this is new to me and I thank you for your patience as I work through this
[MAPNEW1.zip](https://github.com/okviz/free-visuals/files/4481942/MAPNEW1.zip)
[Bithub Map 1.zip](https://github.com/okviz/free-visuals/files/4481945/Bithub.Map.1.zip)

**Comment by danieleperilli** [comment]
It works for me. Are you using the last version of Power BI?
<img width="1698" alt="Power_BI" src="https://user-images.githubusercontent.com/9072177/79448764-4da1b080-7fe2-11ea-8ad2-7a2f8b8682c9.png">
