### ISSUE TITLE
Bullet Chart - Unable to assign targets

### ISSUE THREAD

**Issue by apfenech** [okviz/free-visuals#124]
Is there a way to assign the targets with the Bullet Chart?  I am using it to show Revenue, Cost, and Net Revenue but when I drag my measures in as targets, I am unable to assign them correctly – the visual automatically assigns the targets and I can’t figure out how to make sure they get assigned the right targets.  Value and Comparison line up in order from top to bottom, but the targets do not.
 
Here, you can see the targets are correct but I have not included the third target for Net Revenue.
 ![TwoWorking](https://user-images.githubusercontent.com/28718809/78938631-c4353000-7a6f-11ea-8f5c-30ab43d0968f.png)
 
 
If I bring in a third target for Net Revenue, I can’t get the targets 
to be assigned to the right values:
![ThreeBroken](https://user-images.githubusercontent.com/28718809/78938670-d7e09680-7a6f-11ea-967e-39995450bc51.png)

I've have a dummy file with the behavior but the smallest I can get it is 90MB.  I've reached out to Daniele for assistance getting this in the right hands.

**Comment by danieleperilli** [comment]
Thanks for the sample report, I'm able to reproduce the issue, which we will fix in the next release. Unfortunately, any new version requires 4/5 weeks to be released on the marketplace plus our internal time to fixed the issue. I will update you here when we have something to test. Thanks for reporting!

**Comment by danieleperilli** [comment]
Fixed in 2.2.7
