### ISSUE TITLE
Sparkline - sparklines gone missing

### ISSUE THREAD

**Issue by tmoney74** [okviz/free-visuals#125]
I've created a report page with a bunch of sparklines.  I went to work on another page in the report, and when I returned to the sparklines page, they went missing.  I mean, they're still there - I can seem them load and they are available to select, but there is nothing showing up.

![image](https://user-images.githubusercontent.com/63686678/79287493-f7bdf300-7e91-11ea-8633-5eb740b2dd92.png)

**Comment by danieleperilli** [comment]
Please share the report. It could a cross filter or a platform issue.

**Comment by danieleperilli** [comment]
Send to support@okviz.com or attach on Github, do not attach on the reply via email, it doesn't work.

**Comment by danieleperilli** [comment]
I just checked it. The problem is in the query: if you convert the visuals to standard line charts you see a single point, not a line.

**Comment by tmoney74** [comment]
Thank you.
