### ISSUE TITLE
SynopticPanel - Too many values

### ISSUE THREAD

**Issue by PaulHallam** [okviz/free-visuals#126]
I have a floor plan svg uploaded into Synoptic Panel, there are 499 areas all with an individual I.D.

When i add the I.D. to the category field and add a measure in the Synoptic Panel i can get every one of the areas coloured individually and the corresponding legend showing.....ALL GOOD.

In the underlying data table each I.D. has a corresponding department, there are 35 departments in the table. All I.D.s are associated with a department.

**The Problem**
I want the colours and legend to be by department so i move the I.D. to the Subcategory and add the department to the category. However not all departments are shown and i get the error

Too many values
We are not able to display all the data because there are too many values for the following fields: Department , I.D. Filter the data or choose another field.

It seems strange that it can handle all the 499 areas originally but cant take the departments

Please Help

Paul

**Comment by danieleperilli** [comment]
When you bind a field to the visual the number of rows is not summed with the rows of the other fields but multiplied, so I think you reach to limit of 30K.

**Comment by PaulHallam** [comment]
Thanks daniel, so you are saying its 499*499 which is way over 30,000. 
But when i reduce the data to 200 rows so 200 * 200 (40,000) it works.

**Comment by danieleperilli** [comment]
I don't know how they really make the calculation, but the limit is set by Power BI. There is a way to load data incrementally, but we are not able to support yet.
