### ISSUE TITLE
Sparkline - Can't see the tooltips

### ISSUE THREAD

**Issue by eitanmoran** [okviz/free-visuals#127]
Hi,
I have made a Sparkline Visual and add some info to the Tooltip  Field Pane of the Visual 
but i cant see any info when hovering on the points ( i could not find any Tooltip section in the Format pane).
is there any guide lines for using the Tooltips?

**Comment by danieleperilli** [comment]
No special steps to follow, just drag the field on the Tooltips section in the Fields panel.
Probably there is an issue with the field you are using. Please, provide a sample file so we can reproduce the issue.
