### ISSUE TITLE
Bullet Chart - Infinity Data Label

### ISSUE THREAD

**Issue by Turnbullca** [okviz/free-visuals#128]
Hi Guys,

I love this chart and use it a lot but I there is a "feature" that exhibits itself when I have data for this year but not for next.  If Show % change over - Comparison Value and there is no in my case Previous Year Data I see the word + infinity.  Is there anyway I not show this or this scenario.

Also as a Feature request is it possible have seperate formatting options for the value and Show % change over text.

Love your work.

Thanks

Chris

**Comment by danieleperilli** [comment]
Please, provide a sample file.

**Comment by Turnbullca** [comment]
Hi Daniel,

Thanks for getting back to me.

This is what I see when there is no result for Comparison Value.

![image](https://user-images.githubusercontent.com/64676356/80859738-ed09a900-8c5a-11ea-9ca1-c2dcdcf1a21b.png)

When there is a result for LY I see this.

![image](https://user-images.githubusercontent.com/64676356/80859761-17f3fd00-8c5b-11ea-8598-7b0ba9558b8a.png)
Thank You for having a look at it.

Chris

**Comment by danieleperilli** [comment]
Chris, we need a sample PBIX file.

**Comment by danieleperilli** [comment]
Fixed in 2.2.7
