### ISSUE TITLE
Synoptic Panel - Some areas are not getting color as per their deaprtment and legend does not filtering the area

### ISSUE THREAD

**Issue by ShafeekhM** [okviz/free-visuals#129]
Hi,
Some of my areas are not getting coloured based on their department. But once I click on the slicer filter it is highlighting that area. Also when I select the department in the legend it is not highlighting that corresponding department in the plan. I will send you the file to okviz support. it is highly confidential.

**Comment by danieleperilli** [comment]
There are too many values in the visual, the limit is set by Power BI but it's difficult to understand how it's calculated – it should be 30K records, each measure multiplied for each column.
<img width="1503" alt="2020-05-07_09-01-32" src="https://user-images.githubusercontent.com/9072177/81264870-739afd80-9042-11ea-8d98-d0566d78508a.png">

**Comment by ShafeekhM** [comment]
Hi Daniel,
Sorry to bother you again, I am attaching a small file for your review with only three rows of the data. Still the same problem.


[Test.zip](https://github.com/okviz/free-visuals/files/4607771/Test.zip)

**Comment by danieleperilli** [comment]
This is a different problem: try to remove the spaces from the area names, it should be the reason why the areas are not matched.

**Comment by ShafeekhM** [comment]
Great...!!!! characters like "()" and spaces are removed and It is working as intended...!!!
 I need one more help from you. Could you please have a look at what is wrong with my "data label". it is not scaling properly.
![image](https://user-images.githubusercontent.com/64707315/81558322-1ccb5600-93ab-11ea-8d01-75624df8b170.png)
