### ISSUE TITLE
Bullet Chart - CTRL+Click Does Not Multi-Select

### ISSUE THREAD

**Issue by dagostino-ja** [okviz/free-visuals#13]
Title says it all, I can normally ctrl+click two visualizations and have a cross section of the results displayed, for some reason this visual is only single select, I can't make two selections within the visual itself and I can't make two selections using a target from a separate visual in conjunction with this one.

**Comment by danieleperilli** [comment]
Which is the visual you are referring to?

**Comment by dagostino-ja** [comment]
https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380953?tab=Reviews
This one, the bullet chart.

**Comment by danieleperilli** [comment]
Yes, unfortunately the feature is not yet supported. We will include it in the next update, but it won't came out before 1-2 months.

**Comment by dagostino-ja** [comment]
That's a great turn around time! Happy to hear it, I appreciate your hard work.

Thanks,
Joey

iPhone. iTypos. iApologize.

**Comment by danieleperilli** [comment]
Fixed in version 2.2.0 (under review by Microsoft - no ETA yet).
