### ISSUE TITLE
Card with States - Variance color issue

### ISSUE THREAD

**Issue by bpeco** [okviz/free-visuals#130]
This shouldn't be happening. I have conditions for changing the color of the reference label. However, the conditions also affect the Data Label.
Please find attached an example:
![card issue](https://user-images.githubusercontent.com/53384985/80994710-706dfa80-8e13-11ea-8c77-3eb7ad99ef34.png)

**Comment by danieleperilli** [comment]
Unfortunately, it’s a known issue, we already sent a new version to Microsoft two weeks ago.
