### ISSUE TITLE
Synoptic Panel - SVG File not loading in Power BI

### ISSUE THREAD

**Issue by fajer48** [okviz/free-visuals#131]
Trying to import svg file, however, it doesn't get loaded and no error is given.
The map is generated from Synoptic Designer for Power BI.
Power BI version 2.65.5313.1562 64-bit (January 2019)

<img width="959" alt="sample" src="https://user-images.githubusercontent.com/34274449/81053439-bf786600-8ecd-11ea-95f9-73a5a7372422.png">

**Comment by danieleperilli** [comment]
I suggest updating the version of Power BI.
