### ISSUE TITLE
Bullet Chart - Tooltips position after drillthrough

### ISSUE THREAD

**Issue by marthaav** [okviz/free-visuals#133]
Drill Through does NOT work well in Services. It works perfect in Desktop only.

The issue is that in the browser, the visualization loses the focus every time the DrillThrough feature is clicked to go to another page.
Back into the original page, when right-click again, the menu where the DrillThrough was is gone.
The page needs to be refreshed to make it work again.
Does anybody experience this? is there a workaround? 
The visualization is wonderful, but with the DrillThrough  getting lost after each click, my users are not happy :(. Please help

**Comment by danieleperilli** [comment]
Can you provide a sample report?

**Comment by marthaav** [comment]
Thanks Daniel, I tried to attach it but this site does not support PBI extensions. Shall I send you to your gmail?

**Comment by danieleperilli** [comment]
Please, send it to support@okviz.com

**Comment by marthaav** [comment]
Done. sample report sent

**Comment by danieleperilli** [comment]
It's probably a platform bug. Take a look here: https://github.com/microsoft/powerbi-visuals-utils-tooltiputils/issues/39

**Comment by danieleperilli** [comment]
Just re-opened because it's easier to track for new users.

**Comment by rkhatua-aarete** [comment]
Hi Team, 
Is there any way we can handle the tooltip at proper position. Let me know its  urgent
