### ISSUE TITLE
Card with states - Showing (blank) instead of 0

### ISSUE THREAD

**Issue by varayalagos** [okviz/free-visuals#134]
Context: 
Power BI Desktop March and April 2020,  Card with states visual

Problem:
As you see in the image, the visual is showing blank instead of 0. If I create a normal card. it gives us the right number: 0.

![Card with states](https://user-images.githubusercontent.com/64966969/81297614-7f39f480-9041-11ea-8658-7819e79fa8f5.PNG)

**Comment by danieleperilli** [comment]
Sample file.

**Comment by varayalagos** [comment]
Link to download:

https://esvanguardia-my.sharepoint.com/:u:/g/personal/varaya_esvanguardia_cl/ERXBk3ulZnNLpfpQBuE-DLoBhma6u1X_Y8GTJyxB6094MQ?e=Zq4DzV

Alternative:
[Card with states Issue.zip](https://github.com/okviz/free-visuals/files/4593795/Card.with.states.Issue.zip)

I proved the version 1.6.4 and 1.6.5

**Comment by danieleperilli** [comment]
Thanks, I will include a fix in the next version.

**Comment by varayalagos** [comment]
Thanks!
1) I realized the problem is in the format pane: "Category"--> "Display" : "Custom Text"
2) Is it possible in the next version to control the result "INFINITY" we get when the division is by 0? The real value for example is 5 and the Budget is 0, so it gives us "Infinitive" as a % difference, and the client use 0% in their reports.

**Comment by danieleperilli** [comment]
We fixed both issues
- ++Infinity is not displayed anymore 
- The target value is correctly displayed in the label also when is equal to 0

You just have to wait a few weeks, we are collecting issues from users before releasing a new version (1.6.6).
