### ISSUE TITLE
Bullet Chart- All rows (categories) not showing, only showing a portion of categories. 

### ISSUE THREAD

**Issue by daccorti** [okviz/free-visuals#137]
Issue:
We have a bullet chart on a dashboard that displays operational activities (category) and hour variance associated with them. There are  ~5,900 distinct activity types and variance values they can range from negative infinity to positive infinity (in theory). If the values are sorted ascending by variance (negative -> positive) we're not able to scroll from the max negative value and get to the max positive value. It would appear we've reached a max number of rows displayed. If we sort in the opposite fashion (descending: positive -> negative) we're able to see the proper values, but still not able to scroll all the way through the range of values. 

Reproducibility: 
As stated above, we have ~5,900 values in our category field with the associated variance values ranging from negative infinity to positive infinity.

**Affected environment**
- Power BI Desktop (include the version: E.g.: April 2020)
- Power BI Online 

**REQUIRED: Repro file**
I've Included a dummy pbix file that demos the same issue as well as the data used to populate it. There are 6000 jobs with hours values ranging from -5000 -> +5000. You are unable to see all 6000 jobs scrolling from start to finish, though by resorting the list you can see the majority but not all.

**Screenshots**
See demo file.

[BulletChart.zip](https://github.com/okviz/free-visuals/files/4610705/BulletChart.zip)

**Comment by danieleperilli** [comment]
The visual currently displays max 1000 values. We will increase this number up to 30,000 in the next update (v2.2.8). Unfortunately, there is already a new version (2.2.7) in the review pipeline, so you have to wait 6/8 weeks before this fix reaches the AppSource. Anyway, we will publish a private version (not certified) on the OKVIZ website by the next week.

**Comment by daccorti** [comment]
Thanks for the update.
