### ISSUE TITLE
Synopic panel - UK Map some regions not picking up data

### ISSUE THREAD

**Issue by James123456789987** [okviz/free-visuals#138]
Hi 
 
I wonder if you can help me please? I have downloaded the Synopic panel visualisation for power BI and selected the UK regions map. It works and looks great. Except that some areas just aren't picking up in the visualisation. I’ve created a fresh power bi file with only 1 table. And I’ve assigned a value of 1 against each region, but several of the regions are not picking up data and I can’t for the life of me figure out why. 
 
This data: 
Region | Number of cases
Channel Islands | 1
East Midlands | 1
East of England | 1
North East England | 1
North West | 1
Northern Ireland | 1
Scotland | 1
South East | 1
South West | 1
Wales | 1
West Midlands | 1
Yorkshire and the Humber | 1
London | 1

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)

**REQUIRED: Repro file**
Report attached
[test map.zip](https://github.com/okviz/free-visuals/files/4615253/test.map.zip)
[test map.zip](https://github.com/okviz/free-visuals/files/4615256/test.map.zip)
![Untitled](https://user-images.githubusercontent.com/65227562/81683167-a3387400-944d-11ea-9206-3e7dec6bc34c.jpg)

**Screenshots**
also attached, shows southeast with count of 1 and southwest and north west with no count of 1. Data table used would expect a count of 1 for each area.

My simple mind suggests that the visual cannot find South West and North West because they are in fact called something different in the visual. I have tried South west with a trailing space and few other combinations, but nothing seems to work. 

Any help would be massively appreciated, since this is an awesome visualisation and easy to use. 

Thanks 
Duncan

**Comment by James123456789987** [comment]
Additional info : I have cards attached to the map. If I click on Southwest on the map the card correctly displays the number of cases. So it's the little pop up box that isn't showing the data. Not that the map in its entirety is not working. Thanks

**Comment by danieleperilli** [comment]
I think the problem is that every area (green) is nested in another layer (red)
Open the svg map in the Notepad just move all the nested maps to the root.
![image](https://user-images.githubusercontent.com/9072177/81963498-759e2700-9615-11ea-9d69-e5672bea704f.png)

**Comment by James123456789987** [comment]
Hi @danieleperilli 

Thanks for your help. I've had a go at this. It has changed the map, as in the whole map now doesn't appear, but also it has made no difference to the original problem. Everything else works. I've tried moving the data to a few different places, but none seem to resolve the problem.

![Capture](https://user-images.githubusercontent.com/65227562/82211213-6a464680-9908-11ea-8c38-197fa69b6802.JPG)
 
Is the position here ok? I know its slightly different from your screen, but I tried that position also and it had the same result

Many thanks for your help

**Comment by danieleperilli** [comment]
It's probably better if you edit the map in your graphic editor and move all the shapes to the root layer. Sorry, we don't provide design support for custom maps.

**Comment by James123456789987** [comment]
I seem to have fixed it by making the following changes:

![Untitled](https://user-images.githubusercontent.com/65227562/82213225-b941ab00-990b-11ea-9da7-662f994f8a69.jpg)

Hopefully this will help someone in the future

**Comment by James123456789987** [comment]
> It's probably better if you edit the map in your graphic editor and move all the shapes to the root layer. Sorry, we don't provide design support for custom maps.

I'm not talking about a custom map though, this is the map that comes with the vizulisation in power bi

I got the SVG data by using the graphic editor, but it seems to export different data every time, there is no consistenacy to it and it doesn't work at all once imported into Power BI. 

But my original query is regarding the UK map from the gallery in the Vizualisation, not a custom map

**Comment by danieleperilli** [comment]
I didn't realize it, sorry.

**Comment by James123456789987** [comment]
It's all ok, it's really hard to describe over the net. I've attached a version of the Map. I've manged to edit the .SVG file so that South West and West England now show correct value in the tool-tip ...unfortunately  I've shrunk Scotland and I've no idea how :) I can't seem to get Scotland back to the right place and size, no idea what I've done 


[test map.zip](https://github.com/okviz/free-visuals/files/4645069/test.map.zip)

**Comment by James123456789987** [comment]
[test map.zip](https://github.com/okviz/free-visuals/files/4645222/test.map.zip)

OK, I've almost got it to work. all the areas now show 1 in the tool tip and Scotland is back to the right size and shape, however now the end of the Southwest is clipped off, And I can't figure out how. I've adjusted the map position that moves the map, but SW is still cut off. Then I tried changing the % size, but that had no effect...

**Comment by James123456789987** [comment]
The author at this website had the same problem:
[https://www.osinsci.xyz/powerbi/uk-postcode-regions-for-analytics/](url)

> The only problem I found was that there were multiple mappings over the different regions, meaning that even though the colour saturation and region assignment worked, the data labels weren’t visible when hovering over the region.

They have they're own map which I can use. But I'd like to get this one sorted.

I now have all areas displaying the correct tool tip of 1 case. And all the areas are the correct size and shape.... EXCEPT for Scotland

`<g title="" class="area" id="Scotland" transform="matrix(2.16104, 0, 0, 2.16104, -724.396, -988.943)">
</g>

	<path title="" class="area" id="Scotland" d="M 696.2 148.9 l 3.7 6.3 l -1.4 3.2 l -15.5 -5.5 l -`

If you take the g title part out then the map shows the correct tooltip value, however then Scotland is shrunken and in the wrong place on the map. This is I presume because because the G title section has resizing and location data in it. The question is how to get this into the path title section.

I'm so close to be able to make this work. 

It would be great though if the visualisation worked out of the box without all this manipulation behind the scenes. I don't know anything about the coding language this is written in, I've just been cutting and pasting bits of code out to see what effect it has... which is obviously very time consuming

**Comment by James123456789987** [comment]
[test4.zip](https://github.com/okviz/free-visuals/files/4649854/test4.zip)

This is the SVG file that almost works. Only Scotland fails to show a tool tip value 

Everything else is sorted now

**Comment by James123456789987** [comment]
No worries, I have sorted it. this code:

`transform="matrix(2.16104, 0, 0, 2.16104, -724.396, -988.943)"`

Needed to be nested at the end of the Scotland "SVG path element"
