### ISSUE TITLE
Card with States - Decimals not showing when adding "Measure for Comparison"

### ISSUE THREAD

**Issue by stefan-schweiger** [okviz/free-visuals#139]
**Describe the issue**
As soon as I add a "Measure for comparison" to the visual the decimal places configuration for "Data Label" gets ignored and only a integer value is shown. In the screenshot below you can see the behavior with version 1.4.2 (downloaded from your website) and the current 1.6.3 version available in AppSource for which I'm encountering the bug.

**To reproduce**
Steps to reproduce the behavior.

**Affected environment**
 - Power BI Desktop (April 2020)

**Repro file**
[VIZ_Card_Bug.zip](https://github.com/okviz/free-visuals/files/4628545/VIZ_Card_Bug.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/3532342/81938094-bd608680-95f4-11ea-8268-34792fbc6d84.png)
Above: v1.4.2 Below: v.1.6.3

**Comment by danieleperilli** [comment]
The fix will be included in the next version (v1.6.6). The workaround is to set a specific format for the main measure (which is not now).

**Comment by stefan-schweiger** [comment]
Thanks for you fast response. Any idea when this version will be available on AppSource?

**Comment by danieleperilli** [comment]
We are still collecting issues, then we will send a fixed version to Microsoft for publishing; let's say it would be by the next week. Their approval process takes 3/4 weeks.
