### ISSUE TITLE
Bulle Chart - Tooltip option not available

### ISSUE THREAD

**Issue by anujparihar** [okviz/free-visuals#14]

**Comment by anujparihar** [comment]
Hello,
The Bullet Chart doesn't seem to have the formatting option for Tooltips. 
I wish to turn off the default tooptip in chart, and use my custom fields as tooltip, but I can't do that.
I am very happy with the result otherwise and don't want to shift to any other visual for this feature.
Thanks.

Regards.
Anuj

**Comment by danieleperilli** [comment]
Added in version 2.2.0 (under review by Microsoft - no ETA yet).
