### ISSUE TITLE
Bullet Chart - The tool tip text appears on the left side of the report

### ISSUE THREAD

**Issue by carlosmcruzd** [okviz/free-visuals#140]
when the report is loaded, the Bullet chart tool tip text appears on the left side on top of the screen, and does not appear on the object.

![bulletChart](https://user-images.githubusercontent.com/21182641/81996860-cf9ded00-9613-11ea-8bdb-7c5df2f473a2.png)
![bulletChart](https://user-images.githubusercontent.com/21182641/81996883-e04e6300-9613-11ea-88bb-f191a3472f40.png)

**Comment by danieleperilli** [comment]
Duplicate of #133
