### ISSUE TITLE
Card with States - Trend Line doesn't work with negative amount

### ISSUE THREAD

**Issue by totangZP** [okviz/free-visuals#143]
**To reproduce**
When the amount become zero, the trend line will become empty

**Affected environment**
 - Power BI Desktop (May 2020)

**REQUIRED: Repro file**
Sent to support@okviz.com already

**Screenshots**
![image](https://user-images.githubusercontent.com/65884271/82780349-72166580-9e89-11ea-8cd2-a43e5dd42dac.png)

**Comment by danieleperilli** [comment]
Thanks for submitting the issue. The fix will be included in the next version (v1.6.7) that we will publish as a private version by the next week. The same version will appear on the AppSource by the end of the month.

**Comment by danieleperilli** [comment]
Fixed in v1.6.7

**Comment by totangZP** [comment]
Omg, the speed is so fast! Thanks, Daniel!
