### ISSUE TITLE
Bullet Chart - Additional markers type

### ISSUE THREAD

**Issue by gerwin90** [okviz/free-visuals#144]
Hey, I have be messing around with the BulletChart for PowerBI extension you have and I love it. One of the things I noticed is that there is only four types of markers for the target - line, circle, square and cross. 

Do you intend to add more to this? Considering this is a target field I think it would be very good to include a "flag" as an option.

**Comment by danieleperilli** [comment]
Thanks for the suggestion. Unfortunately, at the moment we don't plan to add other markers type – maybe in the future.
