### ISSUE TITLE
Bullet Chart -  tooltips are not disabled in an IPad (IPhone)

### ISSUE THREAD

**Issue by FinRR** [okviz/free-visuals#145]
If you disable tooltips, they still appear in the mobile version and interfere with viewing on the IPad and Iphone, but everything works correctly in the browser.

**To reproduce**
open a dashboard in your iPad

**Affected environment**
 - Power BI iOS app

**Comment by FinRR** [comment]
https://okviz.com/wp-content/okviz/bulletChartByOKViz-tour.pbix

**Comment by FinRR** [comment]
I sent a bulletChartByOKViz-tour.pbix with the disabled tooltips to support@okviz.com

**Comment by danieleperilli** [comment]
The tooltips toggle is managed by Power BI, so it's probably a platform bug. Have you tried to replace the visual with a built-in one?

**Comment by FinRR** [comment]
I used yours file with built-in visual. I updated the version to the current one in Power Bi, but it didn't help.

**Comment by danieleperilli** [comment]
Try to replace the visual with a Bar Chart and check if the issue with the tooltips persists.

**Comment by FinRR** [comment]
I replaced the visual element with the built-in Bar Chart and the issue was solved. But I like the Bullet Chart is much more than a Bar Chart )

**Comment by danieleperilli** [comment]
I understand – it was just a test. 
Anyway, we don't know when the user enables or disables the tooltips because it's automatically managed by a library provided by Microsoft, so I suggest submitting the issue directly to them by referring to this thread.

**Comment by danieleperilli** [comment]
It could be related to #133

**Comment by FinRR** [comment]
Thank you, I wrote to them.

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
