### ISSUE TITLE
Bullet Chart - Square target marker position

### ISSUE THREAD

**Issue by vipulguptacc** [okviz/free-visuals#146]
Looks like there is a problem with Bullet Chart by Okviz visual(2.2.5.0) when we use a target marker of square shape. It just runs slightly above the destined value whereas circle and line shape are working fine.
Attached are the screenshots:
![Line](https://user-images.githubusercontent.com/66106454/83229784-35f34580-a1a6-11ea-8f03-56c5ca6cab18.jpg)
![Circle](https://user-images.githubusercontent.com/66106454/83229791-37bd0900-a1a6-11ea-9823-27b9ab7a53c5.jpg)
![Square](https://user-images.githubusercontent.com/66106454/83229792-38559f80-a1a6-11ea-96a8-8f59b0c5c6d4.jpg)

**Comment by danieleperilli** [comment]
Please provide the sample report

**Comment by vipulguptacc** [comment]
Hi Daniel,

Attaching a pbix file with the dummy data i just created.
There are three tabs:
1. Target Marker - Line: Works fine as 90% line and target marker overlaps
2. Target Marker - Circle: Works fine as 90% line and target marker overlaps
3. Target Marker - Square: Has a problem as 90% line and target marker do not overlap and gets very clearly visible when the size of the visual is shortened.
[Bullet Chart.zip](https://github.com/okviz/free-visuals/files/4700360/Bullet.Chart.zip)

**Comment by vipulguptacc** [comment]
Hi Daniel,
Any update on this?
Can the team confirm if this is bug and any ETA for its resolution so I can communicate in my firm accordingly.
Thanks in advance.

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
