### ISSUE TITLE
Synoptic Panel - Hide "(Blank)" panel visual

### ISSUE THREAD

**Issue by marciosonobe** [okviz/free-visuals#148]
Hello,
I would like to hide the description "(Blank)" on the panel when data is not available.

**Affected environment**
 - Power BI Desktop (may 2020)

**Screenshots**
![Synoptic Panel - Hide_Blank](https://user-images.githubusercontent.com/66377445/83669495-0da18780-a5a8-11ea-8838-b23caea0fea5.jpg)
 Tks

**Comment by marcosqlbi** [comment]
The easiest way to get this is to write a measure that returns an empty string if the result is blank.
I'm not sure it works with Synoptic Panel but you can try:

Measure = COALESCE ( [Existing measure], "" )

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
