### ISSUE TITLE
Card with states - measures don't show up in the right order

### ISSUE THREAD

**Issue by tgraziosi** [okviz/free-visuals#149]
I have a visual with 6 measures, and they should show up as a 3 column x 2 row grid but they don't and they're out of order
Here is a screenshot showing it:
![image](https://user-images.githubusercontent.com/8724532/84299220-60d28780-ab1e-11ea-9054-713d58488e6c.png)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
