### ISSUE TITLE
Synoptic Panel - Data labels not working

### ISSUE THREAD

**Issue by dcf2981** [okviz/free-visuals#150]
I'm working on a custom map, but I've hit a weird issue. Synoptic panel pulls in my data areas correctly and highlights the zones, but the data labels on some of the cells won't show up. 

If I hover over the affected cells, the data is displayed correctly, but there's no data label.

**Comment by dcf2981** [comment]
![image](https://user-images.githubusercontent.com/33068995/84774915-7dead880-afac-11ea-8fea-94ca5b18afd2.png)

I forgot to include a screenshot. Here's what I'm seeing

**Comment by danieleperilli** [comment]
Please, attach the report.

**Comment by dcf2981** [comment]
Here's a copy of the report and relevant files:

https://drive.google.com/file/d/1twgmuQ0k0YbhPTOdEr2O065W_bR54Qr2/view?usp=sharing

**Comment by danieleperilli** [comment]
Sorry, I think you should create a smaller map (8MB is too much for any browser), I can't even inspect the single areas...

**Comment by Paule08** [comment]
I have the same problem. Some fields are displayed correctly, other fields not. 
![18-09-_2021_13-17-50](https://user-images.githubusercontent.com/18749603/133887038-fcb2502d-b45a-4575-ab59-bd1dce48431b.png)

**Comment by Gwenderlay** [comment]
![image](https://user-images.githubusercontent.com/119318856/204285723-5437e63b-d377-455f-bd51-b35a6ac4b1d7.png)

Similar results here; been using it for the same use case plenty of time and it seems to go wrong only on this one image, with about half of the areas defined correctly in PowerBI but not showing any data label associated to it.
File size is 2,055 KB. Have others in use that are larger and are working fine.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
