### ISSUE TITLE
Card with States - Not compatible with Power BI Subscriptions

### ISSUE THREAD

**Issue by johnybilek** [okviz/free-visuals#152]
Hi,
I love using the 'Card with states' visual in Power BI. Unfortunately, we found out that the visual does not seem to be compatible with the Power BI 'Subscriptions' (automatic email from Power BI with an image of a report page). All other visuals are ok, I only have problem with Card with States.
Can you please help? Thank you very much!
![image](https://user-images.githubusercontent.com/54617354/84863737-bc989580-b075-11ea-8911-599efdedc85f.png)

**Comment by danieleperilli** [comment]
Which version of the visual are you using? It seems you are using a private version from our website, which is not certified and cannot be rendered in emails.

**Comment by johnybilek** [comment]
Hello Daniele,

thank you for your answer. I am using 1.6.5 version as I had some issues with the certified one some time ago (I think that modifier over target was not displayed or was displayed but in strange format/colour etc.).
What do you suggest? Get back to the certified one ? Or will the new version be certified soon?

Thank you very much
Jan

**Comment by danieleperilli** [comment]
The v1.6.5 has been certified, so you can download it from the marketplace.
