### ISSUE TITLE
Cards with States - order problem when applying -sort By Column desc- feature

### ISSUE THREAD

**Issue by mrtttlm** [okviz/free-visuals#153]
**Describe the issue**
Hi, 
firstly its a very good and useful visual, thanks for your efforts. 
I have a question: 
Using as multiple card, (a measure and a category information) I have problem when sorting the cards by category field.

Category information is a text field and it is sorted by another column.
in the format pane , multiple card section: 
when I choose sort by title, it sorts cards by alfanumeric order ( even if a different order by is specified for that column in the model), 
when I choose manual, the order is right but does not have an option like desc

I just want to order cards based on what specified in the model and desc order.
is there any way to do in this situation?

Thanks

**Affected environment**
 - Power BI Desktop RS (May 2020)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recrea
[Cards with states order issue sample.zip](https://github.com/okviz/free-visuals/files/4796601/Cards.with.states.order.issue.sample.zip)
te the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***
d
![want this order but desc](https://user-images.githubusercontent.com/33581684/84984924-7827fb00-b144-11ea-8d71-a9e6e3c26d7c.png)

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.
![want this order but [](desc](https://user-images.githubusercontent.com/33581684/84985050-b8877900-b144-11ea-8cc0-53f9c81575b1.png))

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
