### ISSUE TITLE
Card with States - Issues with MultiCards

### ISSUE THREAD

**Issue by JosePereiraViz** [okviz/free-visuals#154]
Good evening,

In one of our client, on  powerbi project, we are using the "Card with States" powerbi visual and we are having some problems in which we ask for your help in order to overcome them.
[
![Issue](https://user-images.githubusercontent.com/45037162/84999532-32216600-b149-11ea-8005-cc16db983d0b.png)
](url)
 
According to the images, we can see that the cards are behaving in an unexpected way. Is any configuration missing? 

We are using as Measure a metric with values in percentage and the values in the conditions to obtain the colors are also in the percentage format. Could it be causing conflict?

Taking advantage of this email, to clarify some more doubts, is there any configuration that allows me to have the name of the category above and the values of measure and the % over target below?

 
![Dbout](https://user-images.githubusercontent.com/45037162/84999590-47969000-b149-11ea-9937-a53c1d852b73.png)

And can only show the value of the measure, the target and the value of the Reference Type i choose, correct?

I request, please, your help as soon as possible, because it is a large project with a lot of impact for the client.

Thank you.

Best Regards
 
José Pereira

**Comment by danieleperilli** [comment]
Please, follow the rules for posting issues: a meaningful title and (more important) the sample report file.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
