### ISSUE TITLE
Cards with States - Messages cannot be configured

### ISSUE THREAD

**Issue by dedelman04** [okviz/free-visuals#155]
**Describe the issue**
When I create a new visual with Cards with States and activate the "Show Messages" feature under Formatting -> States, the option to put in a message never appears. For an existing visual, the option is there as expected

**To reproduce**
Open SurveyResults in PowerBI version 2.79.5768.721 64-bit (March 2020)*
Add a new visual using Cards with States (ver 1.6.5). 
Add the measure "Satisfaction Percentage" (home table is "Surveys") to the "Measures" field and the "Measure for Comparison" field
Go to Formatting -> States, make sure it is switched On and expand
Scroll to "Show Messages" and switch it On. 
Scroll to "Condition 1" and expand
Notice that there is no field for "And show the message"
Go to the page "Dashboard" and click on the visual labelled "Total Satisfaction Score" (far left, top row excluding slicers) - under Condition 1, you will see that there is a field for "And show the message"

*This was also attempted with the newest release of PBI Desktop "2.82.5858.641 64-bit (June 2020)" and had the same results

**Affected environment**
- Power BI Desktop 2.79.5768.721 64-bit (March 2020)
- Power BI Desktop 2.82.5858.641 64-bit (June 2020)

**Repro file**
[Survey Results.zip](https://github.com/okviz/free-visuals/files/4805639/Survey.Results.zip)

**Screenshots**
Existing visual
![image](https://user-images.githubusercontent.com/42451900/85155759-c7daf500-b21e-11ea-8ea6-6f557cbfc739.png)

New Visual
![image](https://user-images.githubusercontent.com/42451900/85155844-e3de9680-b21e-11ea-94eb-55a8c8272cdf.png)

Thanks!

**Comment by andrew-eyre** [comment]
I have exactly the same issue. Is there a target date for resolution?
I signed up to Premium to get this feature but it seems to be missing or have been removed? Version 1.6.8 is currently installed

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
