### ISSUE TITLE
Card with States - KPI, Target, Previous Month value ? no templates available for that?

### ISSUE THREAD

**Issue by eltonaguiar** [okviz/free-visuals#156]
unable to show both 
Suppose KPI Is # of incidents for a month.

KPI # , Target # , Previous Month # ? 
suppose KPI is 300,(should be below target in this case, but need ability to change) 
Target is 200 
Previous Month value is 400. 
Can the card support showing 3 different numbers? I didn't see any of the templates that have that

**Comment by danieleperilli** [comment]
Sorry, it's not possible. We will evaluate it for future updates.
