### ISSUE TITLE
Synoptic Pannel - Wrong display with bubbles

### ISSUE THREAD

**Issue by louise-labatie** [okviz/free-visuals#157]
**Describe the issue**
As my map is quite heavy, I use Inkscape to modify the Area ids. 
Once on Power BI, i upload my map and fill Category and Measure fields. But all tool-tips I have are displayed as 'Area XX' with XX the id of the zone on Inkscape. Whereas it should be displaying data related to Category and Measure.

**To reproduce**
Modify a svg map on Inkscape and add ids you want to map for each layers.
Add Synoptic Pannel viz on a Power BI desktop report.
Fill Category and Measure fields with processed data.

**Affected environment**
 - Power BI Desktop (2.82.5858.641 64-bit (June 2020))
- Inkscape (1.0 (4035a4fb49, 2020-05-01))
- Windows 10

**REQUIRED: Repro file**
[Bug_Example.zip](https://github.com/okviz/free-visuals/files/4824312/Bug_Example.zip)
France_regions.svg is the map used in Synoptic Pannel.

**Screenshots**
![image](https://user-images.githubusercontent.com/46763059/85525558-7ad59500-b609-11ea-9bd8-3d2bb7dead96.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
