### ISSUE TITLE
Synoptic Panel for Power Bi download corrupt

### ISSUE THREAD

**Issue by Jonnap2000** [okviz/free-visuals#158]
Hi,

I have downloaded the Synoptic Panel for Power Bi and when i try to load it the statement pops up saying 'the synopticPanelByOKViz.1.5.0.0.pbiviz is corrupt or invalid report file'

Please help

**Comment by danieleperilli** [comment]
You are probably trying to directly open the file with Power BI. Please, take a look at these articles: 
https://okviz.com/blog/updating-power-bi-custom-visuals/ 
https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals
