### ISSUE TITLE
Card with States - Title top padding setting

### ISSUE THREAD

**Issue by djpirra** [okviz/free-visuals#159]
Something really simple that is currently missing in the Cards visual is the ability to set a top padding on the title since it is so close to the border of the card.
Is this something that can be added so that we can choose a particular top padding value?

**Comment by danieleperilli** [comment]
You can already set it.
![image](https://user-images.githubusercontent.com/9072177/85826234-7b466b00-b784-11ea-9703-a33c2a3bead4.png)

**Comment by djpirra** [comment]
The one that is on the AppStore does not have it or am I missing it totally?

**Comment by danieleperilli** [comment]
Yes, it's available in the certified version on the AppSource.

**Comment by djpirra** [comment]
Hi Daniele, isn't that the padding for the KPI value? I was referring to be able to add padding to the title of the card.
Also, would be great to have the capability to add line breaks to the custom text on the target.

**Comment by danieleperilli** [comment]
Unfortunately, the title (and its position) is not customizable by custom visuals.

**Comment by djpirra** [comment]
Can we have support for line breaks on the custom text for the target so we can have same behavior as the normal targets?
