### ISSUE TITLE
Synoptic Panel - Selected map item freezes map data after slicer change

### ISSUE THREAD

**Issue by vonBarbarosa** [okviz/free-visuals#16]
Hello!

I've come to a problem with the Synoptic Panel:

## Setup:
- Synoptic Panel with items and numerical values
- Slicer which changes the numerical values of the items
- Optional: A card to show the numerical value based on the filter

## Sample files:
- In my example, I have desks with occupancy values (in percentage), I have a slicer to filter the data by hour period and a card with the occupancy value (after filters)
[bug-report v2.zip](https://github.com/okviz/free-visuals/files/3277878/bug-report.v2.zip)

## How to reproduce the bug:
- Given the setup or the sample file
- I select one item (desk) on synoptic panel. The mean value on the card shows the same value on the selected item tooltip.
- With the item still selected, I change the slicer filter.

### What's expected:
- Every value on the tooltips of the synoptic panel is changed. The heatmap color changes accordingly. The value on the selected item tooltip is the same as shown in the card.

### What actually happens:
- The value on the card changes correctly, but the tooltips values on the panel don't change. Even if I select other items to filter, or click out of the items to select all of them, the tooltip values are still frozen. The heatmap value doesn't change accordingly. The only way I found to get out this frozen state is to move the through the map (zoom in or out, or drag around).

## Environment
- Synoptic Panel by OKViz version 1.5.0.0
- Windows 10 and Power BI Desktop 2.69.5467.1751 64-bit (May/2019)
- Also in Power BI on cloud (app.powerbi.com)

Thanks!

**Comment by danieleperilli** [comment]
I can reproduce. It seems an issue of the visual's internal caching process. Thanks for reporting it.

**Comment by fiker916** [comment]
Is this issue resolved since 2019? I am experiencing the same issue. Thanks

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
