### ISSUE TITLE
Card with States - Allow target comparison when using trendline

### ISSUE THREAD

**Issue by djpirra** [okviz/free-visuals#161]
**Description**
Allow direct target comparison to work when using trendlines.

**To reproduce**
Add one attribute to the Trendline that is not from date dimension but is reflecting the date (example when using dynamic axis for date, months, years etc... )
Add one measure on the "Measures" and set it to SUM.
Add one measure on the "Targets"

The reference value will not be showing correctly.
It should ignore the trendline and compare target measure vs main measure.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
[PBI OkViz Issue.zip](https://github.com/okviz/free-visuals/files/4864449/PBI.OkViz.Issue.zip)

 - Power BI service
 - Power BI iOS app
 - Power BI Android app

**Comment by okviz** [comment]
When there is a trendline, the value and the reference are defined by the value you set in the Data Label value option.
![image](https://user-images.githubusercontent.com/20169220/86563660-0d105e00-bf65-11ea-8e90-1f9a58f03d6e.png)

In your example, the sum of the main measure values and the sum of the targets are the same, so the change is 0%.
![image](https://user-images.githubusercontent.com/20169220/86563762-42b54700-bf65-11ea-8f2e-f2691309ff0e.png)

If you want to compare only the last data point or the first one, please change the value displayed by the data label.
