### ISSUE TITLE
Sparkline - Text Tooltip

### ISSUE THREAD

**Issue by asmyth76** [okviz/free-visuals#162]
**Describe the issue**
When adding a text field in the tooltip it either doesn't show up or shows (blank). I feel like the issue is on my end ... but I've been able to add a text field to other sparkline visuals as a tooltip, so I'm not sure what I'm doing wrong.

**To reproduce**
Drag a text field to the tooltip area then mouseover a datapoint on the sparkline

**Affected environment**
- Power BI Desktop : 2.81.5831.1181 (May 2020)
- Sparkline version: 1.1.3

[Example Sparkline.zip](https://github.com/okviz/free-visuals/files/4868720/Example.Sparkline.zip)

![Sparkline](https://user-images.githubusercontent.com/21333392/86451236-86644280-bd12-11ea-866a-be8da9294ad0.png)

Thanks in advance!

**Comment by danieleperilli** [comment]
Unfortunately, we have suspended the release of updates on this visual, except for security bugs. I have added an On-Hold tag and closed the issue; I will reopen it when we begin actively working on the project again.
