### ISSUE TITLE
Card with States - Allow formatting as Duration

### ISSUE THREAD

**Issue by djpirra** [okviz/free-visuals#163]
**Describe the issue**
We have a measure that is currently in milliseconds and we want to be able to present it in **days, hours:minutes:seconds** 
If we use a measure creating a text in this format, then we are not able to compare with targets etc...

**To reproduce**
Add a measure with a numerical value in the card and try to represent in the specified format and also compare to target.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service
 - Power BI iOS app
 - Power BI Android app

**Comment by marcosqlbi** [comment]
I think that there are no custom format strings to display an interval in Power BI, so this is an issue beyond the capabilities of the visual. If Power BI had a custom format string for dates that supported that format, it would be supported by all the visuals.

**Comment by djpirra** [comment]
Hi Marco, I am aware of that, was just thinking maybe the formatting could be dealt directly by the visual if you selected a specific format option. That would make sure that the visual has the original aggregatable value and also can represent it in a readable way.

**Comment by marcosqlbi** [comment]
It's going to be expensive for the implementation because it should support locale settings and different formats. I'm not saying it wouldn't be useful, but it's unlikely it could be prioritized enough for the implementation.

**Comment by djpirra** [comment]
To be honest, I think this should be prioritized on the Pow.er BI side. It's something that most of the reporting tools have... even Excel has it. With so many customers reporting this, I wonder why it was not implemented yet.
Anyway thanks Marco.

**Comment by marcosqlbi** [comment]
I totally agree!
