### ISSUE TITLE
Card with States - State Message does not change & default position of dynamic Data Label

### ISSUE THREAD

**Issue by phlppnsk** [okviz/free-visuals#165]
**Describe the issue**
There are 2 parts to this issue:
1. I have 3 conditions for the coloring of the visual. I am using the dynamic label version. In the state message I want to use the value of a field, specifically the "LOG_TIME_Message". When condition 1 is met, this works perfectly fine. When 2 or 3 are met, the state message does not change but stays at the value left or right from it, depending on where you are "coming from" on the trendline.
2. Per default, when opening the report the value shown in the datalabel is the one of the earliest point in the trendline. For my use case, I need to see the LATEST value when opening the report. There currently is no way of setting this up, is there?

**To reproduce**
1. Move along the trendline and pay attention to the state message. As a reference I added a table next to the card.
2. Open the report or switch from page 2 back to page 1

**Affected environment**
 - Power BI Desktop (Version: 2.80.5803.1061 64-bit (April 2020))
 - Power BI service
 - Power BI iOS app
 - Power BI Android app (don't know, can't check but would guess so?)

**REQUIRED: Repro file**
[OKVizIssueSampleReport.zip](https://github.com/okviz/free-visuals/files/4895624/OKVizIssueSampleReport.zip)

**Screenshots**
Condition 1 to start:
![image](https://user-images.githubusercontent.com/68053869/87019602-1acb1b00-c1d3-11ea-9bae-b9ee5c6ace40.png)
From 1 to 2:
![image](https://user-images.githubusercontent.com/68053869/87019624-1f8fcf00-c1d3-11ea-9f45-c8fc96dfaa21.png)
From 2 to 3:
![image](https://user-images.githubusercontent.com/68053869/87019640-228abf80-c1d3-11ea-8734-78e75e5c65d6.png)

Different data point with Condition 1:
![image](https://user-images.githubusercontent.com/68053869/87019749-43531500-c1d3-11ea-8308-9d1dc74aa974.png)
From 1 to 1:
![image](https://user-images.githubusercontent.com/68053869/87019766-4b12b980-c1d3-11ea-8738-1e3312fab51b.png)

Hope you can help me out with this.
Cheers
Philipp

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
