### ISSUE TITLE
Bullet Chart - Service hiding Y-Axis Values

### ISSUE THREAD

**Issue by HennemanTJ** [okviz/free-visuals#166]
**Describe the issue**
Desktop shows Y-Axis just fine, when shared to Service/App the Y-Axis appears to be hidden. If I shrink the text down to 3 or 4 it will sneak more numbers on there but not the whole number.  

**To reproduce**
N/A - just sharing to service

**Affected environment**
 - Power BI service

**Screenshots**
![image](https://user-images.githubusercontent.com/29777362/87168330-4e25ac80-c29c-11ea-94e9-4a67fe13303c.png)

![image](https://user-images.githubusercontent.com/29777362/87168388-685f8a80-c29c-11ea-8071-2eccae15e1c5.png)

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
