### ISSUE TITLE
Synoptic Panel - Unmatched Area Error

### ISSUE THREAD

**Issue by TMoss21** [okviz/free-visuals#169]
Hello,

I have a drawing of a building (svg. file) that has 920 compartments, each has it's own specific code. I am using this as my visual and using synoptic panel to match the compartments to a set of data.

The data is 3 columns, Compartment Code, Compartment Name, Compartment Condition. My aim is to assign each condition a colour (through data colours) and have the drawing of the building essentially show the colours which in turn gives a quick idea of the condition of each compartment.

By setting Code to Subcategory, State to Category and Name to Measure in the fields section, I can do this. It works perfectly with 5 variations in condition, the drawing has all the colours of all the compartments.

However, as soon as I add one more condition option and there are now 6 possible colours, a large chunk of my data becomes unmatched and no longer appears in the visual. I can see that the data that becomes unmatched is at the end of the table (i.e the last few rows) which makes me think this is due to a limitation of data? But I didnt think 920 data points would be a problem.

Can someone please help out?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
