### ISSUE TITLE
Synoptic Panel - Can't change subcategory label on tooltip

### ISSUE THREAD

**Issue by vonBarbarosa** [okviz/free-visuals#17]
Hello!

I noticed I can't change the subcategory label on the Synoptic Panel tooltip the same way I can change the category label.

## Setup:
- Synoptic Panel with columns on **Category** and **Subcategory**

## Example files:
[bug-report v2.zip](https://github.com/okviz/free-visuals/files/3277878/bug-report.v2.zip)

## How to reproduce the bug:
- On the Synoptic Panel, I hover on the item to see the tooltip

### What's expected:
- I see the tooltip with the labels and values according to the selected variables (columns)

### What actually happens:
- I see the tooltip with the right labels and values for Id and measure, but the label for subcategory is written **Subcategory**, and I can't change it, as show on the figure:
![image](https://user-images.githubusercontent.com/14874259/59220885-60ff1680-8b9c-11e9-9eaa-68f908e71ecc.png)

## Environment
- Synoptic Panel by OKViz version 1.5.0.0
- Windows 10 and Power BI Desktop 2.69.5467.1751 64-bit (May/2019)
- Also in Power BI on cloud (app.powerbi.com)

Thanks!

**Comment by vonBarbarosa** [comment]
Correcting the example file:
[bug-report v2.zip](https://github.com/okviz/free-visuals/files/3277878/bug-report.v2.zip)

**Comment by danieleperilli** [comment]
Yes, it's a known issue.

**Comment by erikatmt** [comment]
Hi! I still face the same issue.

Do you plan to add a patch to fix this anytime soon?

**Comment by hifihedgehog** [comment]
I noticed this same issue. Any ETA?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
