### ISSUE TITLE
Card With States - Labels doesnt work with Internet Explorer

### ISSUE THREAD

**Issue by JosePereiraViz** [okviz/free-visuals#171]
Good Morning,

We hereby report that we are having problems viewing card labels when using Internet Explorer, as shown in the image 1.

When using the Chrome browser, the card labels appear straight and work very well, as shown in the image 2.

Have you ever encountered this situation?

Best Regards,

José Pereira

**Affected environment**
 - Power BI service

**Screenshots**
Image 1
![image](https://user-images.githubusercontent.com/45037162/88169505-f4b26b80-cc13-11ea-9f0e-4f09ff562cf0.png)

Image 2
![image](https://user-images.githubusercontent.com/45037162/88169529-fda33d00-cc13-11ea-86d0-a4e96c3b3f9a.png)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
