### ISSUE TITLE
Bullet Chart - Wrong Target Markers

### ISSUE THREAD

**Issue by RensMatthews** [okviz/free-visuals#172]
The Bullet Chart visual is not correctly displaying the Target icons for the belonging data.

In the picture below the Line marker should actually be a Dot marker, as the data belongs to FCII_EXQL. In this view there is no data for 'AFE Budget [PMR]' and 'BCT Forecast [PMR]'.
![Bug](https://user-images.githubusercontent.com/68737146/88390638-f23d4680-cdb8-11ea-9cd6-4a4594de9489.png)

In the picture below the Cross marker appears while I haven't even chosen it (see legend). Also some markers display the data of another marker. For example, on the 7th bar the Line marker is actually displaying the data belonging to FCII_EXQL.
I am pretty confident this has to do with whether or not all markers are required per node, as for the rows where all markers have data they are displayed correctly. When there is only one marker needed it just uses the icon of the first one in the legend, regardless whether it is actually the correct icon belonging to that data.
![Bug2](https://user-images.githubusercontent.com/68737146/88390641-f5383700-cdb8-11ea-87b9-02976850e626.png)

Please find below sample report that replicates this error. Issue seems to occur when the dataset is filtered by a slicer.
[Bullet Chart - Bug - Wrong Target Markers.zip](https://github.com/okviz/free-visuals/files/4972083/Bullet.Chart.-.Bug.-.Wrong.Target.Markers.zip)

**Comment by RensMatthews** [comment]
Unfortunately I cannot add or send the PBIX file as the data is coming from SQL databases and Analysis Services. Without access to these sources one cannot view the report.

**Comment by danieleperilli** [comment]
Please, create a sample report with dummy data, otherwise we can't investigate.

**Comment by RensMatthews** [comment]
Please find

> Please, create a sample report with dummy data, otherwise we can't investigate.

Please find a sample report in the original post. Thanks!

**Comment by RensMatthews** [comment]
> The Bullet Chart visual is not correctly displaying the Target icons for the belonging data.
> 
> In the picture below the Line marker should actually be a Dot marker, as the data belongs to FCII_EXQL. In this view there is no data for 'AFE Budget [PMR]' and 'BCT Forecast [PMR]'.
> ![Bug](https://user-images.githubusercontent.com/68737146/88390638-f23d4680-cdb8-11ea-9cd6-4a4594de9489.png)
> 
> In the picture below the Cross marker appears while I haven't even chosen it (see legend). Also some markers display the data of another marker. For example, on the 7th bar the Line marker is actually displaying the data belonging to FCII_EXQL.
> I am pretty confident this has to do with whether or not all markers are required per node, as for the rows where all markers have data they are displayed correctly. When there is only one marker needed it just uses the icon of the first one in the legend, regardless whether it is actually the correct icon belonging to that data.
> ![Bug2](https://user-images.githubusercontent.com/68737146/88390641-f5383700-cdb8-11ea-87b9-02976850e626.png)
> 
> Please find below sample report that replicates this error. Issue seems to occur when the dataset is filtered.
> [Bullet Chart - Bug - Wrong Target Markers.zip](https://github.com/okviz/free-visuals/files/4972083/Bullet.Chart.-.Bug.-.Wrong.Target.Markers.zip)

**Comment by RensMatthews** [comment]
I have attached it to the original post, thanks!

**Comment by RensMatthews** [comment]
Any idea when this might be investigated? Thanks!

**Comment by RensMatthews** [comment]
Any update on this would be much appreciated, thank you.

**Comment by RensMatthews** [comment]
Is this even on the roadmap to be fixed? Would love to hear from you, thanks.

**Comment by RensMatthews** [comment]
I guess that's a no then?

**Comment by danieleperilli** [comment]
Fixed in v2.2.9.4
