### ISSUE TITLE
Synoptic Panel - wrong detection of areas, colors from svg. file and  just a part of the picture is exported to Power BI

### ISSUE THREAD

**Issue by EmPi44** [okviz/free-visuals#174]
Issue:
The areas of the SVG. file are not displayed properly in Power BI Desktop.

To reproduce:
Insert the SVG.File to the Synoptic Panel Design and import it to Power Bi Desktop. 

Affected environment:
 - Power BI Desktop
- Inkscape 0.92

[MAP_V1.zip](https://github.com/okviz/free-visuals/files/5012149/MAP_V1.zip)

**Comment by EmPi44** [comment]
SVG.File file was created from a PowerPoint presentation with the format .emf

**Comment by danieleperilli** [comment]
It seems you didn't associate the area to any name in your records. Please, follow the tutorial here: https://okviz.com/blog/introducing-synoptic-panel-v1-4/

**Comment by EmPi44** [comment]
Hi Daniele,

associating the areas will only solve the problem that the area is not black anymore. But the problem is that the not the whole .svg is displayed in Power Bi only the opper left part of the grafic.
