### ISSUE TITLE
Bullet Chart - Show % Change Over Negative Number Parenthesis

### ISSUE THREAD

**Issue by devhawkio** [okviz/free-visuals#175]
**Describe the issue**
Negative percentages are showing as (9)% when they should show as (9%) or -9%

**To reproduce**
Set a target higher than the value (both formatted as currency), then in "Show % change over" select "First Target"

**Affected environment**
 - Power BI Desktop (July 2020)
 - Power BI service
[Example.zip]
(https://github.com/okviz/free-visuals/files/5043523/Example.zip)

**REQUIRED: Repro file**
Example.zip attached

**Screenshots**
Example shows this issue clearly

**Comment by danieleperilli** [comment]
Fixed in v2.2.9.4
