### ISSUE TITLE
card with States by OKVIZ-Visual refresh is not working

### ISSUE THREAD

**Issue by abhayjadhav-24** [okviz/free-visuals#177]
Regarding the visual 'card with States by OKVIZ', having visual data Refresh issue based on slicer selection value. Suppose if i have selected any one of the value from slicer then this visual is not getting refreshed as per slicer selection.

Also i wants to know the information about when i use this visual for production environment,if  we required how do i get support for this visual. Wants to know the process to raise the support ticket & how i will get assistance regarding this ticket. 

Is there any cost associated with the visual licence or visual support cost.

**Comment by jodeja** [comment]
Same here, it seems like enabling shadow is the trigger to this issue.

**Comment by 5Aces** [comment]
Turning off the shadow option also fixes the inability to copy/paste the visual. Great spot, jodeja.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
