### ISSUE TITLE
Sparklines - Formatting value labels

### ISSUE THREAD

**Issue by florentibus** [okviz/free-visuals#180]
I can't seem to change the value labels from decimal to percentages.
![image](https://user-images.githubusercontent.com/70030961/90919382-5ea96680-e3b4-11ea-89e3-6a61a208ed62.png)

**Comment by NovatiaDevelopment** [comment]
We can confirm that this issue also persists if you change the format datatype in the powerbi toolbar, does this visual support reformatting of data types or can it only display native datatypes?

**Comment by NovatiaDevelopment** [comment]
Our field loses it's percentage formatting when we change the sort category. Is this related to this formatting issue?
