### ISSUE TITLE
Power Bi - OKVIZ Card With States w/ Multiple Cards

### ISSUE THREAD

**Issue by p1z0n1** [okviz/free-visuals#181]
I am new using Power BI and also Okviz´s Card With States and as I have no found any manual to begin with this visual I´m reaching you.  I´m starting to migrate from KPI Indicator visuals from Fredrik Hendenstrom to OKViz Card With States. However I am actually facing some difficulties to configure OKViz in Multiple Cards mode and I need some help from your side.

I have a report that uses 5 KPI Indicator see below, that shows 5 types of apps deployment termination states: On Time, Late, w/Failure, Cancelled and NoGo. Each one has different targets: 83%, 8%, 5%, 3% and 1%.

I´d like to configure the visual to change color states based on targets, but I couldn’t manage it. Below you can see the snapshots from my report and Card With States Config.

So, could you please give us some help on this subject?

Thanks in advance for your help and guidance.

[FW Power Bi - OKVIZ Card With States w Multiple Cards.zip](https://github.com/okviz/free-visuals/files/5114144/FW.Power.Bi.-.OKVIZ.Card.With.States.w.Multiple.Cards.zip)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
