### ISSUE TITLE
Volume  in Candlestick chart

### ISSUE THREAD

**Issue by abitz88** [okviz/free-visuals#182]
Hallo

It would be greatly appreciated if we could get and easy way to plot volume in your chart. This would ease the analysis of the candlesticks. Something like below.

https://www.google.com/url?sa=i&url=https%3A%2F%2Ftradingqna.com%2Ft%2Fwhat-is-this-grey-candle-in-my-candlestick-chart%2F16296&psig=AOvVaw3oNzn9UFKCYHGKAPeGantg&ust=1598306247780000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKjB_PSosusCFQAAAAAdAAAAABAD

Thank you for a great chart!

**Comment by marcl11** [comment]
Is there an idea of this request will be followed up, or nobody is taking care anymore of the candle chart ?

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry. I will reopen this issue if we change our plans.
