### ISSUE TITLE
card with States by OKVIZ-On Tooltip Date value is showing with Datetime & not only date without time 

### ISSUE THREAD

**Issue by abhayjadhav-24** [okviz/free-visuals#183]
I can see tooltip information for Date as 08/08/2020 12:00:00 AM where i have already set data type as Date only but still can see date value with time.

Date column having data type as Date , Is it possible to show the date value as date only instead of Date with time?

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
