### ISSUE TITLE
card with States by OKVIZ- Support required for this visual

### ISSUE THREAD

**Issue by abhayjadhav-24** [okviz/free-visuals#184]
I wants to know the information about when i use this visual for production environment & if we required, how do i get support for this visual. Wants to know the process to raise the support ticket & how i will get assistance regarding this ticket.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
