### ISSUE TITLE
Card With States - Sort By Column not being used

### ISSUE THREAD

**Issue by helloyesthisisdave** [okviz/free-visuals#187]
**Describe the issue**
The categories within the visual do not abide by the sorting for the Category column Sort By Column value and are instead only sorting by the Measure value.

**To reproduce**
See repro sent to support email.  Visual contains just the Category Name from a column that has a Sort By Column configured and a Measure, though the Sort By is not being honoured.

**Affected environment**
Power BI Desktop - Version 2.84.981.0 64-bit (August 2020)

**REQUIRED: Repro file**
Repro sent to support@okviz.com

**Screenshots**
N/A

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
