### ISSUE TITLE
Synoptic Panel- Category not displaying all values

### ISSUE THREAD

**Issue by thendraluser21** [okviz/free-visuals#189]
**Describe the issue**
Hi Team, 
I'm using synoptic panel for seating dashboard, i have 366 rows(seats) when i display based on seat number it  highlight perfectly but when i display  based on secretary(category) it is not highlighting all seats. i'm aware there is a limitation but can you please explain the exact  limitation ?  if any paid version available that would resolve this issue  would be very helpful.

**Affected environment**
- Synoptic panel (version 1.5.0)
 - Power BI Report server  (September 2019)

**Comment by daniellibrantz** [comment]
I´m having the same problem, only 2 subcategories are recognized and I have 5, the first 2 always work, I hanged the order, name and always the same result, only the 2 first were recognized.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
