### ISSUE TITLE
Card with States - Performance

### ISSUE THREAD

**Issue by sumanchintala** [okviz/free-visuals#19]
Hi , 

Currently i am using the beautiful KPI called Card with States by OKViz in one of my power bi report.   But seems to be this KPI has a performance issue while running the report in power bi desktop or power bi service. Could you please help me how to improve the performance . 
Below are the KPI performance Analyzer status. 
![image](https://user-images.githubusercontent.com/39137058/59374834-c1b45d80-8d1a-11e9-973a-fc6544f0ba56.png)

**Comment by marcosqlbi** [comment]
Even thought the custom visuals have an overhead compared to other visuals, the cost of Visual display seems too high, unless you are displaying a line chart with hundreds of points.
Are you able to provide us a repro PBIX file so we can further investigate?
