### ISSUE TITLE
okviz Cards with States

### ISSUE THREAD

**Issue by heytherejem** [okviz/free-visuals#191]
I've included a simple measure in the Tooltips and it's not appearing when I hover over the visual.

I tried other measures, none are working
I tried closing and reopening the application and it still does not show the tooltip

I use Power BI Desktop April 2020 version

I have the Premium Licence

![CardswithStates](https://user-images.githubusercontent.com/71014848/92595652-9e20ef80-f29c-11ea-9a43-88b1f7ef0ad5.png)

**Comment by deverauxt** [comment]
I have the same issue, was this resolved? I have the PowerBI August version.

**Comment by deverauxt** [comment]
Okay so after the better half of a day looking for a workaround I figured out that the DEFAULT card does not show the tooltips. I tried a few of the others and they work fine! Might be a bug, might be a design feature, but I hope this saves someone else some headache.  -_-

**Comment by heytherejem** [comment]
This must be a bug as the tooptip option is there. Okviz - this is your support site, you haven't responded? Can you help?

**Comment by heytherejem** [comment]
deverauxt what card does show tooltips?

**Comment by deverauxt** [comment]
heytherejem choose one of the other templates aside from the default from the pop up in the bottom right corner of the card, and then in the Visualizations -> Format -> Multiple Cards -> Show Tooltips. Seems all but the default work.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
