### ISSUE TITLE
Sypnotic Panel:     Runs out of memory on Mobile Device/Center Image

### ISSUE THREAD

**Issue by kdixon5490** [okviz/free-visuals#192]
Is there anyway to center the Map Image on the mobile device?

Because I don't know how to center the image I had to add to maps on the screen so that the image would show correctly in the portrait view on the map.

I believe this is causing the screen to run out of memory.

Any suggestions?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
