### ISSUE TITLE
Visual Name - Synoptic Designer

### ISSUE THREAD

**Issue by PrakashPisipati** [okviz/free-visuals#193]
**Describe the issue**
**I am using drawings to map rooms, I have a total 63 rooms in each floor, after 50 rooms i am unable to export to power bi and it is getting crashing**

**To reproduce**
Steps to reproduce the behavior.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service
 - Power BI iOS app
 - Power BI Android app

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by marcosqlbi** [comment]
Please, read this article: https://okviz.com/blog/introducing-synoptic-panel-v1-4/
The editor we provide in https://synoptic.design might have limitations because of the browser. The article suggests other SVG editors such as Inkscape (which is free).
