### ISSUE TITLE
Card with States by OKViz - Tooltip visualization

### ISSUE THREAD

**Issue by Oceangsy** [okviz/free-visuals#195]
I have a question while using the Card with States by OKViz visualization. I would like to display further information related to the “Category” metric via Tooltip. However, it seems not possible even I set "Show Tooltips" as "on". 
I’ve adjusted the sample file you provided to explain it (please see screenshots below). In this case, I would like to show the ‘Product’ [Category Code] information via Tooltip. Do you know if this is possible? If not, is there an alternative solution? Many thanks in advance for your support.

![screenshot_1](https://user-images.githubusercontent.com/23743296/93856198-f1da0280-fcb8-11ea-9bc5-869078b1a16e.PNG)
![screenshot_2](https://user-images.githubusercontent.com/23743296/93856211-f6062000-fcb8-11ea-8f58-d0190b97c1f5.PNG)
![screenshot_3](https://user-images.githubusercontent.com/23743296/93856227-facad400-fcb8-11ea-98c3-3cc80f0f0db0.PNG)

**Comment by Oceangsy** [comment]
[Question about Tooltip_Sample.zip](https://github.com/okviz/free-visuals/files/5376454/Question.about.Tooltip_Sample.zip)

**Comment by A-Kazak** [comment]
I would be happy to have a capability of adding a tooltip to the Card with States visal.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
