### ISSUE TITLE
Support for dynamic data colors

### ISSUE THREAD

**Issue by djpirra** [okviz/free-visuals#20]
Instead of having a color configuration for the targets it would be more flexible to create a measure with the rules for the coloring of the bars.

Currently with the configuration we are not able to correctly represent items from an income statement where for example positive revenue is good but positive cost is bad.

Thank you

**Comment by danieleperilli** [comment]
With the latest version of Card With States (currently under review by Microsoft) we improved a lot how states work and we will apply this new approach to all our visuals soon.
