### ISSUE TITLE
Card with States - Format String Expression

### ISSUE THREAD

**Issue by totangZP** [okviz/free-visuals#200]
Just would like check if the visual will be supporting "format string expression" from calculation group?

Since now I am trying to build a report utilizing the calculation group, and would like to use the card for some KPI indicator.

But found the % can't be presented as %.

Will it be possible in the near future? Thank you.

![image](https://user-images.githubusercontent.com/65884271/95277097-934b8180-087f-11eb-8ed9-b80ab176e21d.png)

**Comment by danieleperilli** [comment]
It's not an issue of Card with States, but it's a platform issue that Microsft is already aware of and applies to every custom visual.

**Comment by totangZP** [comment]
Dear @danieleperilli ,

Thanks for the clarification.

Really appreciate!

Tom
