### ISSUE TITLE
Dot Plot - Y axis not properly displaying values > 100

### ISSUE THREAD

**Issue by reileybergin** [okviz/free-visuals#201]
**Describe the issue**
The Y axis on the DotPlot is cutting off values greater than a 100.

**Expected behavior**
Show 100

**Current behavior**
Shows 00

**Affected environment**
Power BI Desktop (Version: 2.85.985.0 64-bit (September 2020)
Dot Plot (dotPlotByOKViz.1.0.0.0)

![image](https://user-images.githubusercontent.com/25494043/95394610-d97a0280-08ca-11eb-91fb-778cffabc7d6.png)

 PBIX report file:
[DotPlot_AxisBug.zip](https://github.com/okviz/free-visuals/files/5344276/DotPlot_AxisBug.zip)

**Comment by danieleperilli** [comment]
Unfortunately, we have suspended the release of updates on this visual, except for security bugs. I have added an On-Hold tag and closed the issue; I will reopen it when we begin actively working on the project again.
