### ISSUE TITLE
Card with State - Difference between measure and target in % points

### ISSUE THREAD

**Issue by PetFra** [okviz/free-visuals#202]
**Describe the issue**
The calculation between the measure and the target as _change over target_ works fine but if both these measures are in % the difference should be expressed as % point.

**To reproduce**
Just add two measures formatted as % in measure and target and activate the _change over target_ calculation

**Affected environment**
PowerBI Desktop

Sample file attached

[CardWithStateIssue.zip](https://github.com/okviz/free-visuals/files/5353709/CardWithStateIssue.zip)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
