### ISSUE TITLE
Synoptic Panel - Failure embedding maps

### ISSUE THREAD

**Issue by tpiel** [okviz/free-visuals#203]
**The Issue**
I am trying to use the new method of embedding maps into Synoptic Panel in Power BI so they can be filtered by a slicer.
I am following the step by step instructions from this link: https://okviz.com/blog/introducing-synoptic-panel-v1-4/.  It is not loading and I am left with a blank visual with a small gray dot flashing on and off in the middle of the visual, so it never loads the map.  Does this new method actually work?  Is there a way I can/should do this without having the file path and somehow just get the svg data as a text value?

**Steps to replicate**
I am attaching the sample file, and a sample excel sheet that I used to test the visual.
Beyond importing the data from the excel file the preparation steps are:
1. Add a custom column to the sheet with the file path in the data
2. In defining the custom column, set it to execute the function (File.Contents( [ file_path_column] )) 
3. Manually set the new column to be of data type `Text`
4. Load new column data into 'Map' field of synoptic panel

**Affected environment**
 - Power BI Desktop Version: 2.85.985.0 64-bit (September 2020)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

[test_synoptic_panel_embed.zip](https://github.com/okviz/free-visuals/files/5357210/test_synoptic_panel_embed.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/44116860/95626365-1fa8a080-0a48-11eb-838a-808921470e5f.png)
![image](https://user-images.githubusercontent.com/44116860/95626490-5ed6f180-0a48-11eb-95a9-edcc21fb0612.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
