### ISSUE TITLE
Smart Filter - Drop-down menu does not overlap other visuals

### ISSUE THREAD

**Issue by LinqLover** [okviz/free-visuals#205]
**Describe the issue**
When adding a Smart Filter visual of a small height to a report, I'd like to see a large menu list when I click the drop-down arrow, still.

**To reproduce**
- Add a Smart Filter visual to a report
- Resize it to a small height
- Open the drop-down list

**Affected environment**
 - Power BI Desktop (include the version: E.g.: October 2020)
 - Power BI service

**REQUIRED: Repro file**
[okviz-smart-filter-#205-height.pbix.zip](https://github.com/okviz/free-visuals/files/5385440/okviz-smart-filter-.205-height.pbix.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/38782922/96142154-0b5e1b00-0f02-11eb-9e18-cb1a151c6bb1.png)

**Comment by LinqLover** [comment]
Just for reference, the built-in Slicer visual does support this, so it must be possible to implement:

![image](https://user-images.githubusercontent.com/38782922/96143157-1f564c80-0f03-11eb-952d-e856684d0d4f.png)

**Comment by danieleperilli** [comment]
Unfortunately, is not possible for custom visuals to extend beyond their boundaries. The built-in visual can do it because it is not a third-party custom visual.

**Comment by LinqLover** [comment]
Oh, what a pity. Is there an upstream issue for PBI? However, thanks for your fast reaction!

**Comment by danieleperilli** [comment]
I'm afraid there isn't any issue, because it's a mere consequence of a security measure; indeed custom visuals run inside an iframe.
