### ISSUE TITLE
Bullet Chart - Category labels on higher levels disappears when using drill down (expand)

### ISSUE THREAD

**Issue by RasmusRymark** [okviz/free-visuals#206]
**Describe the issue**
When I have assigned multiple categories to the Bullet Chart and use the drilldown arrows in the visual I wish to keep the top level - when using the Expand all levels button.

**To reproduce**
Add multiple categories to Power BI visual -> drill down using All Levels.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service
 - Power BI iOS app?
 - Power BI Android app?
[BulletChart_MissingParentCategories.zip](https://github.com/okviz/free-visuals/files/5415256/BulletChart_MissingParentCategories.zip)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
