### ISSUE TITLE
Bullet Chart - Conditional formatting for Actual vs Plan

### ISSUE THREAD

**Issue by jimmyjosejoy** [okviz/free-visuals#208]
I have conditionally formatted my bullet chart as below:
IF actual value  is less than Plan Value   ->  Red Colour for Actual Bar

  otherwise Default Green.

Is there a way I can additionally create one more condition like If there is no Plan, the Actual bar should be shown in Black Colour

Attached the Sample file. 
Desktop Version - September, 2020
[Bullet Chart Sample.zip](https://github.com/okviz/free-visuals/files/5428553/Bullet.Chart.Sample.zip)

**Comment by danieleperilli** [comment]
In v2.2.9.4 we added advanced color rules that should satisfy your requirements.
