### ISSUE TITLE
Sparkline - Not Displaying Defined Date Format In Tooltip

### ISSUE THREAD

**Issue by danielreber** [okviz/free-visuals#209]
**Describe the issue**
I have multiple sparklines that use a value and a date. The date is defined in Modeling to use a format of m/d/yyyy hh:nn AM/PM. However, the date format in the tooltip includes everything spelled out. For example, 10/29/2020 10:00 AM is displayed as Thu Oct 29 2020 10:00:00 GMT- 0400 (Eastern Daylight Time) 

**Affected environment**
 - Power BI Desktop October 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/36636578/97895931-69f90680-1d02-11eb-808c-c47ece650b00.png)

[Sparkline Issue.zip](https://github.com/okviz/free-visuals/files/5476614/Sparkline.Issue.zip)

**Comment by danielreber** [comment]
Hi, were you able to reproduce this issue?

**Comment by danielreber** [comment]
@okviz  were you able to reproduce this issue?

**Comment by danielreber** [comment]
@marcosqlbi @okviz  Is this the same issue as issue #227

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry. I will reopen this issue if we change our plans.
