### ISSUE TITLE
Synoptic panel displays dark color instead of the right color

### ISSUE THREAD

**Issue by CodeToYourMother** [okviz/free-visuals#21]
Instead of displaying any of the colours set up in the file, the map displays a dark, almost black color. This fixes itself every time I switch "Saturate" in "Data Colors" off and back on. 
I'll send the file via email because it has client's data.

**Comment by danieleperilli** [comment]
I just checked the file you sent me about this issue: the saturation can't work with textual columns! You have to put a numeric measure in the Measure field to have this working.
