### ISSUE TITLE
How to use the Synoptic Panel?

### ISSUE THREAD

**Issue by shyke2020** [okviz/free-visuals#210]
I have not yet understand the setting method of the following options in the Synoptic Panel: Measure, and States the Measure, Target, States
Can you provide a sample file for me?I according to you provide the sample files to learn how to use it.
![image](https://user-images.githubusercontent.com/74278483/98762527-d1097000-2412-11eb-9b43-3289a500d6d3.png)

This is an example of a file, I do hope to set up the target, and set colors according to the sales target completion rate. 
Or you can provide a sample file for the several options, I study the set method.
[Sample files.zip](https://github.com/okviz/free-visuals/files/5521602/Sample.files.zip)

**Comment by danieleperilli** [comment]
Please, refer to this article:  https://okviz.com/blog/introducing-synoptic-panel-v1-4/ 
You can download the sample file from our AppSource: https://visuals.azureedge.net/app-store/synopticPanelByOKViz.1.5.0.0.pbix

**Comment by shyke2020** [comment]
Thank you very much!

As shown in the figure below, you provide the sample file is not set in these fields, I can't grasp the function of several Settings. Could you provide other can reflect the function of the sample files? Thank you very much!
















在 2020-11-11 14:09:44，"Daniele Perilli" <notifications@github.com> 写道：

Please, refer to this article: https://okviz.com/blog/introducing-synoptic-panel-v1-4/
You can download the sample file from our AppSource: https://visuals.azureedge.net/app-store/synopticPanelByOKViz.1.5.0.0.pbix

**Comment by shyke2020** [comment]
Thank you very much!

As shown in the figure below, you provide the sample file is not set in these fields, I can't grasp the function of several Settings. Could you provide other sample files? Thank you very much!​
![image](https://user-images.githubusercontent.com/74278483/98777905-85fc5680-242c-11eb-96cb-0b25e1489d3a.png)
