### ISSUE TITLE
Smart Filter - bookmark

### ISSUE THREAD

**Issue by ELefkow** [okviz/free-visuals#211]
I would like to reset the Smart Filter (Free version) using a bookmark to clear the selection box.

I'm able to get the data to reset but the selection doesn't clear out from the visual.

![Screenshot 2020-11-12 081457 (OKVIZ)](https://user-images.githubusercontent.com/74363930/98950954-416dcb00-24bf-11eb-9134-7ca28767ac1c.gif)

Thanks,
Ed

**Comment by danieleperilli** [comment]
This feature should be available in the PRO version of Smart Filter.

**Comment by pasqualeceglie** [comment]
But it's really strange that to reset it with a bookmark I have to get the PRO version
