### ISSUE TITLE
Smart Filter Pro - No default selection in "Observer" mode with "Single Selection" On

### ISSUE THREAD

**Issue by Rangama** [okviz/free-visuals#212]
I am evaluating Smart Filter Pro for a specific requirement where I want it to select the first item (according to its display order which can be dynamic based on other prior filters/conditions) by default in the "Observer Mode" so that whatever the depended visuals will display results according to that default selection until the user changes it. 

At the moment Power BI's in-built Slicer does this with "Single Select" in horizontal orientation. However, the problem with that is item cells width is not fixed thus, it is very much possible to acquire entire page width / visual width if there are a few items for the Slicer, which is not nice looking.

**To reproduce**
1. Add a category to Smart Filter Pro
2. Select "Observer" from "Mode" and set "Single selection" option to "On".
3. Depended visuals of the Smart Filter Pro still shows information related to all category objects instead of the first category object

**Affected environment**
 - Power BI Desktop (latest)
 - Power BI service
 - Power BI iOS app
 - Power BI Android app

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without 
[Smart Filter Pro vs Default Slicer in Single Selection Mode.zip](https://github.com/okviz/free-visuals/files/5542496/Smart.Filter.Pro.vs.Default.Slicer.in.Single.Selection.Mode.zip)

a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

Smart Filter Pro in Observer Mode with Single Selection On
![image](https://user-images.githubusercontent.com/74497365/99187122-b6b8f480-277a-11eb-9fc3-7a0dd99ad9cd.png)

Default Slicer in Power BI with Single Selection On

![image](https://user-images.githubusercontent.com/74497365/99187161-ebc54700-277a-11eb-9176-fe498a911bf6.png)

**Comment by danieleperilli** [comment]
Thanks for the suggestion, we will consider whether to introduce automatic resizing in future versions.
Regarding the "sticky selection": unfortunately it's not clear to me.
Can you provide more details? Please use the dedicated repository: https://github.com/okviz/smart-filter-pro-issues
