### ISSUE TITLE
Bullet Chart clarification

### ISSUE THREAD

**Issue by cmsatheesh2017** [okviz/free-visuals#213]
![Okviz Bullet chart clarification](https://user-images.githubusercontent.com/31646490/99212741-e35c2300-27f1-11eb-8e47-2ab1a43f2d42.JPG)

Hi Team,

Please find the above picture. Here you can see the compare value is displayed on the right side label for each visual. 

1. This  compare value is not appear in the right end of the X-Xcale for the visuals 1 to 3 . It will appear if we increase the width of the visual. I need all the visual should be equal width in screen so I can’t increase width. How to make end value appear at the end of each visual?. 

2. How to increase the Height of the filled blue bar inside the rectangle.

In below picture, grouped by category in the bullet chart I can increase the rectangle size only. How to increase spacing between each rectangle?

![Okviz Bullet chart clarification 2](https://user-images.githubusercontent.com/31646490/99213107-be1be480-27f2-11eb-99d8-b8969a3761e4.JPG)

Please reply to my clarification as earlier possible.

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
