### ISSUE TITLE
Card With States - No Documentation on Manual Sort order with Small Multiples

### ISSUE THREAD

**Issue by Janlorie** [okviz/free-visuals#214]
**Describe the issue**
After contacting the support by the website form, I was redirected to Github to ask this question. There is no documentation available for the Manual Sort order for small multiples in the Card With States. There is no other option available to sort by any other column or data except Category name/Ref From/Ref to. 

**To reproduce**
Open PBIX with Card With states, Add necessary measures and a group by column. Go to settings > multiple cards > Sort option > Select Manual.   (No information for that option)

**Affected environment**
 - Power BI Desktop (Versions used are the Report server versions between May and October 2020)

**REQUIRED: Repro file**
In this case it doesn't seem necessary to include a PBIX because it is not related to a specific file or version. I Just need documentation on the option. But the Report will be sent to support@okviz.com.

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.
This issue is regarding the "Sort order" option with value Manual.
![image](https://user-images.githubusercontent.com/17987303/99769097-19591a00-2b06-11eb-987b-9132c63f29d4.png)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
