### ISSUE TITLE
Candlestick by OKVIZ

### ISSUE THREAD

**Issue by abitz88** [okviz/free-visuals#216]
Not an issue as much as a wish. It would be very beneficial to have and extra chart area below the existing, that follows the slider movment af the x-axis. Then one could plot other information that does not follow the same scale as the OCHL. Example: the volumn, ADX or RSI. 

Much apreciated. Keep up the amazing work. For now i will normalize everything between 0 and 1. 

![canvol-2-fdxexam](https://user-images.githubusercontent.com/33158301/100065513-293d6a80-2e34-11eb-9289-32bf25a247c5.png)

**Comment by whuegel** [comment]
This would be tremendously helpful. I use candlesticks as a solution to track moving targets. Having context for volume side by side (or underneath) tells the full story. 

I can do this with OOTB visuals but they don't line up with the x-axis of the candlestick.

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry. I will reopen this issue if we change our plans.
