### ISSUE TITLE
Smart Filter

### ISSUE THREAD

**Issue by BryantWu0823** [okviz/free-visuals#217]
Why is smart filter not shwing on pbi web.

**Comment by igorhfreitas** [comment]
I am facing the same on Power BI Report Server.
The last update - from May 2020 - was working, this issue stated after update Report server version for Oct 2020.
When I open Desktop app, everthing is ok.

**Comment by danieleperilli** [comment]
I guess this is a temporary problem that should be fixed. If the problem persists, reopen it, but keep in mind that we cannot do any analysis without a sample report file.
