### ISSUE TITLE
Synoptic Panel Removing Frame 

### ISSUE THREAD

**Issue by ReneDB** [okviz/free-visuals#218]
How to remove the frame between "elements" and the border of the visual ?
I chose a grey backround so you can see the frame between the drawings and the border of the visual.
Is there a way to reduce the space (marked with red lines)

Thanks in advance !

Rene 
![Frame_zoom](https://user-images.githubusercontent.com/75434110/101040409-69ab8f80-357c-11eb-81c5-d17bbc9845f0.png)
![Frame](https://user-images.githubusercontent.com/75434110/101040571-74febb00-357c-11eb-8048-ab80bda1c06c.png)

Synoptic Panel by Okviz Version : 1.5.0
Power BI : Version: 2.86.902.0 64-bit (Oktober 2020)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
