### ISSUE TITLE
Sparkline - Request Ability to set min and max height similar to the bullet chart

### ISSUE THREAD

**Issue by marons13** [okviz/free-visuals#219]
**Describe the issue**
Would like the ability to fix the height of the sparkline visual similar to what the bullet chart has with the min and max height.
This allows the user to put together multiple visualizations next to each other, and have them stay aligned when the number of attributes varies. 

**To reproduce**
Create a few visuals next to each other, align them accordingly and then filter the data so the number of attributes in the visual decreases

**Affected environment**
 - Power BI Desktop (Aug 2020)
 
**REQUIRED: Repro file**
***IMPORTANT: We don't consider issues without a sample report!***
[NFL OkViz Playground.zip](https://github.com/okviz/free-visuals/files/5643020/NFL.OkViz.Playground.zip)

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

Screenshot Before

![image](https://user-images.githubusercontent.com/72872364/101169542-192f4300-360b-11eb-9fc5-65b1ac023352.png)

Screenshot when Filtering and lines are no longer aligned with rest of visuals

![image](https://user-images.githubusercontent.com/72872364/101169566-251b0500-360b-11eb-8e96-b10c13d72aaf.png)

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry. I will reopen this issue if we change our plans.
