### ISSUE TITLE
Smart Filter Free - Filtering on Whole Numbers

### ISSUE THREAD

**Issue by HSimm2** [okviz/free-visuals#22]
Product works well when filtering across Text data, but will not actually filter on Whole Numbers. It will make auto-complete suggestions for Whole Number data (such as for serial numbers) but will not actually apply a filter. This is a new issue. I have been using this applet for filtering for over a year with no issue.

**Comment by steraji** [comment]
I'm just started having this problem too!

**Comment by rang14** [comment]
I have the same problem. Filtering with numbers does not work.

**Comment by danieleperilli** [comment]
Yesterday, a new version has been published in the marketplace and it could have introduced a regression. We are investigating. Thanks for reporting it.

**Comment by danieleperilli** [comment]
We just fixed the issue on our side and sent the new package to Power BI team. I will update you when they reply with an ETA.

**Comment by HSimm2** [comment]
Thanks for the comments and the feedback! Thought I was going crazy when my analysis quit working.

**Comment by danieleperilli** [comment]
Fixed in v1.2.3+. Waiting for Microsoft release in the Marketplace.
