### ISSUE TITLE
Card with States - data label reference (format bug)

### ISSUE THREAD

**Issue by hosznyak** [okviz/free-visuals#220]
For the reference value is not possible to set the Display unit and Decimal places value, and the reference value is not inherit settings from the data label. In addition the display unit abbreviations is not fit to the culture code. In Hungary the thousand sign is not k, it is e (thousand in hungarian 'ezer')

![image](https://user-images.githubusercontent.com/35693260/102380755-96be6000-3fc8-11eb-806e-fa048bf100ac.png)

Please inherit the settings or provide setting options for the reference value

Thanks
András

**Comment by ClarkMcLauchlan** [comment]
I have the same issue and would love a fix.

My customers do not like a "k" apearing so we divide by 1000 to convert to thousand format. This means we set the display unit selector to "none" which is fine for the data value but the variance does not inherit this so it converts the variance to thousands format again and adds a "k". This means the "15,000,000" should appear as "15,000" (they business understand this is already in thousands so aren't confused by it) but instead appears as "15k". This causes confusion for us.

It worked fine in version 1.4.2 so we used the older version but we had to update to the certified version when the KPI cards broke and wouldn't appear at all a few months ago.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
