### ISSUE TITLE
Card with states - Segoe (Bold) font not working

### ISSUE THREAD

**Issue by infused-kim** [okviz/free-visuals#221]
First of all, happy Holidays and thank you for creating this crucial addition for Power Bi.

**Describe the issue**
I am trying to use the Segoe (Bold) font in the card with states visual, but it is not working.

**To reproduce**
- Create a card with states visual
- Add a measure to it
- Set the font to `Segue (Bold)`
- Observe font showing as Arial

A workaround is to create a settings JSON with the following content:
```json
{
	"name": "Kim's KPI",
	"id": "auto-1608986075426",
	"visualStyles": {
		"card": {
			"horAlignment": "left",
			"alignment": "top",
			"paddingLeft": 120,
			"transparency": 0
		},
		"dataLabel": {
			"locale": "en",
			"fontSize": 11,
			"fontFamily": "'Segoe UI Semibold'",
			"variance": true,
			"varianceType": "target",
			"variancePosition": "bottom",
			"varianceFontSize": 72
		},
		"categoryLabel": {
			"show": false,
			"wordWrap": true
		},
		"trendLine": {
			"pointsWeight": 2
		}
	}
}
```

This allows you to set the font to Segoe SEMI bold. Unfortunately, the same technique doesn't work for bold. It does work for Black though.

More info and other variations I have tried can be found in this PBI support thread:
https://community.powerbi.com/t5/Desktop/Theming-Usage-of-the-quot-Segoe-Bold-quot-font/m-p/497510/highlight/true#M232042

But perhaps Semibold, and black can be added to the dropdown for easier use too.

**Affected environment**
 - Power BI Desktop - December 2020
 - Did not test other environments

**REQUIRED: Repro file**
Can be downloaded here:
https://1drv.ms/u/s!AiPkjSqghF1xhOd-wsQWE7X_dEvLVA?e=KjuhNI

Check the first tab, called `Segoe Bold`

**Screenshots**
Attached a screenshot.
<img width="1470" alt="Screen Shot 2020-12-26 at 19 02 27" src="https://user-images.githubusercontent.com/7404004/103153840-ee20b500-47ac-11eb-9db3-e3e341fc29d4.png">

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
