### ISSUE TITLE
Synoptic Panel react slow

### ISSUE THREAD

**Issue by Sinchetru** [okviz/free-visuals#223]
**Describe the issue**
Hi, I have tried to make a floor plan with 40-50 rooms (polygons), I have done that in the Synoptic designer, and after that I have imported the data (SVG) in Power BI. When I move/zoom the floor plan the image reacts very slow and sometimes doesn't react at all. Are there too many polygons? How can I improve the performance (my computer is quite powerful)? In the example are just a third of the rows number that I want to use in my Report.

**To reproduce**
Load the table from the excel file, insert Synoptic Panel Visualisation SVG Image (Room ID as Category and Mesure). 

**Affected environment**
 - Power BI Desktop (2.88.721.0 64-bit December 2020)

**REQUIRED: Repro file**
[
[ISSUE.zip](https://github.com/okviz/free-visuals/files/5746502/ISSUE.zip)
](url)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
