### ISSUE TITLE
Card With States - Text Measure in Tooltip With Unit (Thousands/Millions)

### ISSUE THREAD

**Issue by Janlorie** [okviz/free-visuals#226]
**Describe the issue**
A text-returning field or measure always returns "NaN" in the tooltip when using a unit other than None or Auto. Even though the Measure/Column is typed as Text, it's being handled as if it's a number. 

**To reproduce**
1. Create Card With states Visual 
2. Insert Normal data for the card (Numbers/Data)
3. Set Units to anything other than None/Auto. 
4. Add a Text-returning field in tooltip
5. Check the tooltip, it shows "NaN"

**Affected environment**
 - Power BI Desktop (October 2020)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
