### ISSUE TITLE
Card with States - Data Label Format with a Calculation Group in the model

### ISSUE THREAD

**Issue by profantalex** [okviz/free-visuals#227]
**Describe the issue**
The format of measure on the Card with states is not applied at all on the visual if there is a calculation group in the model. The calculation group doesn't even have be applied on the visual. 

**To reproduce**
1.	Create a simple measure, set a format on it (other than General)  
2.	Create a calculation group in the model
3.	Use the measure in the Measures field of the Card with States visual
        The calculation group doesn’t have to be used
4.	The format of the measure on the card is not applied at all

**Affected environment**
 - Power BI Desktop December 2020
 - Power BI service

**REQUIRED: Repro file**
There is a simple scenario on the first page and some complex samples on the second page, including the standard Card visual comparison and the calculation group. 

[calculation-group-card-with-states.zip](https://github.com/okviz/free-visuals/files/5787482/calculation-group-card-with-states.zip)

**Screenshots**
![card_with_states_data_format](https://user-images.githubusercontent.com/62140520/104021802-b14aba00-51bf-11eb-8277-bb6308a4355b.png)

**Comment by marcosqlbi** [comment]
Obtaining the right format for custom visuals using calculation groups requires a new library from Microsoft. We are waiting for that, then we have to implement the new technique in the visual, and then the component must be certified again. Unfortunately, we do not have a timeline because we do not know when Microsoft will release the required updates.
You will receive updates on this item when we have news to share. Sorry for that.

**Comment by profantalex** [comment]
Hi Marco, thanks very much for such a quick reply! 
I fully understand, hopefully Microsoft will release it soon.

Have a nice rest of the day!

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
