### ISSUE TITLE
Synoptic Panel - Crash if Decimal Places != Auto AND Value is empty

### ISSUE THREAD

**Issue by cheinz71** [okviz/free-visuals#228]
**Describe the issue**
Synoptic panel does not show the SVG and properties cannot be changed any more.
I assume that an uncatched exception occurred in the custom visual due to the specific data constellation (see below). 

**To reproduce**
1. set the parameter "Decimal Places" to a value except "AUTO", for example "1"
2. Bind a column to "Tooltip" which contains empty data, e.g. a String type with value ""

**Affected environment**
 - Power BI Desktop (November 2020)
 - Power BI service

**REQUIRED: Repro file**
Sample report (.PBIX zipped as .ZIP file): [https://tsmpublicsharetemp.blob.core.windows.net/share/Repro_Bug_Synoptic.zip](https://tsmpublicsharetemp.blob.core.windows.net/share/Repro_Bug_Synoptic.zip)
After you open the report, you will not see the embedded svg. This is the bug. To show the SVG, you have to remove field "Name" from the Tooltips binding.
If you need the svg as a separate file, you can get it here: [https://tsmpublicsharetemp.blob.core.windows.net/share/synopticPanelBug.svg](https://tsmpublicsharetemp.blob.core.windows.net/share/synopticPanelBug.svg)

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

Thank you in advance!!!!

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
