### ISSUE TITLE
Smart Filter (free) - height needs to be reserved for the visual

### ISSUE THREAD

**Issue by ehasin** [okviz/free-visuals#230]
**Describe the issue**
Smart Filter visual height needs to account for displaying the selection options, otherwise these won't be shown. This problem doesn't happen with the standard PBI slicer (see screenshots).

**To reproduce**
Add a smart filter visual with limited height, try selecting values from the drop down list.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service

**REQUIRED: Repro file**
Example report file attached.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
Screenshots attached.
![Capture](https://user-images.githubusercontent.com/8416125/104485511-dfb70380-55ca-11eb-8466-1dd085de49f8.PNG)

[example.zip](https://github.com/okviz/free-visuals/files/5810114/example.zip)

**Comment by danieleperilli** [comment]
Not a bug. It's a limitation of custom visuals. It's not possible to display anything outside the visual boundaries for security reasons.
