### ISSUE TITLE
Card with States - Incorrect Result on Card With States – KPI compared to PowerBI´s table visual

### ISSUE THREAD

**Issue by p1z0n1** [okviz/free-visuals#232]
[Support Card with States.docx](https://github.com/okviz/free-visuals/files/5875379/Support.Card.with.States.docx)

Card with States – Support Requested

Incorrect Result on Card With States – KPI
Hello, need assistance to figure out why result on Card With States – KPI is different from the Total provided Power BI´s table.
Please follow attached file to see more information.

PowerBI Desktop v.2.84.661.0 64bit- August 2020
SO Windows 10

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
