### ISSUE TITLE
Synoptic for Power BI - Unable to open in Power BI (Dec 2020)

### ISSUE THREAD

**Issue by rockerape** [okviz/free-visuals#233]
**Describe the issue**
Syntopics cant open in power BI - it tells either the files is encrypted or corrupted "
 
**To reproduce**
downloaded from the okviz page; start open from explorer; the window pop up shows its  encrypted or corrupted and close the window

**Affected environment**
 - Version: 2.88.1385.0 64-bit (December 2020)

**Screenshots**
[![gambar](https://user-images.githubusercontent.com/75766365/105957395-ca9ea200-60ab-11eb-8e90-cfd98595d3c9.png)
](url)

**Comment by marcosqlbi** [comment]
Are you loading the custom visual from Power BI? It seems you are trying to open it from Windows Explorer.

_To import a Power BI visual, in the Visualization pane click Import a custom visual and select Import from file._
https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals
