### ISSUE TITLE
Smart Filter - Cannot remove/change the background white color 

### ISSUE THREAD

**Issue by YuChingC** [okviz/free-visuals#234]
**Describe the issue**
Currently, when under Observation Mode, there's white background for the selected items, which doesn't look good when the dashboard wallpaper is not white

**To reproduce**
1. Open PBI desktop and get data from local folder
2. Import smartFilterByOKViz.1.1.7.0
3. Change visual mode to Observer
4. Change visual Background as OFF

**Affected environment**
 - Power BI Desktop: May 2020

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.
![image](https://user-images.githubusercontent.com/78098568/106023804-1aa85380-6102-11eb-9d05-501d20916bf2.png)

[Sample_Smart Filter.zip](https://github.com/okviz/free-visuals/files/5881699/Sample_Smart.Filter.zip)

**Comment by YuChingC** [comment]
The staff has already replied and the issue is put in backlog for fixing

**Comment by danieleperilli** [comment]
The issue is only related to Smart Filter Pro. In the free version, you can't change the background color.
