### ISSUE TITLE
Card with States - Organizational visuals license

### ISSUE THREAD

**Issue by Thell** [okviz/free-visuals#235]
Adding the AppSource version **or** the downloaded private build version (from the profile page on OKViz) to the Organizational visuals and then using the visuals premium features is requiring Licensee Name and License key.

The FAQs seem to pertain to Pro _Custom_ Visuals and the blog post [Unlocking the AppSource version of Smart Filter Pro
](https://okviz.com/blog/unlocking-visuals-from-appsource/) seemed to indicate the downloaded version that includes the license information wouldn't require that.

Its not a huge issue as I can continue to cut and paste from the license email but I am wondering if I am just missing something or if its intended to work this way.

![image](https://user-images.githubusercontent.com/2185020/106369441-ef4a8200-6316-11eb-8e34-a5f77f58f5c7.png)
![image](https://user-images.githubusercontent.com/2185020/106369550-1eadbe80-6318-11eb-8dec-efbac39820e6.png)

**Comment by marcosqlbi** [comment]
The article you are referencing is valid only for Smart Filter Pro.
Currently, Card with States visual does not have that licensing system also in the private download, which is intended to provide fixes sooner than the release made through AppSource.
You can read more about the reasons for that in this article: https://okviz.com/blog/updating-power-bi-custom-visuals/

**Comment by Thell** [comment]
Thanks for the quick reply and for saving my sanity from trying and trying again.
