### ISSUE TITLE
Card with Stats  - How to make % Vari display below Sales Amount

### ISSUE THREAD

**Issue by paulyeo11** [okviz/free-visuals#237]
**Describe the issue**
I try to create a visualization , that sales amount in first row and  Vari % in second row 
Now i need to use 2 PBI card one for display sales amount and vari% for Second row.
 
**To reproduce**
https://www.dropbox.com/s/vzxdqxmdsk5iyrs/PBT_V2021_140%20how%20to%20use%20okviz%20display%20YTD%20Sales%20with%20%25%20vari%20V1.pbix?dl=0

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
