### ISSUE TITLE
Smart Filter

### ISSUE THREAD

**Issue by sabisgood** [okviz/free-visuals#238]
**Describe the issue**
Too many values

**Affected environment**
 - Power BI Desktop (version: December 2020)

**Screenshots**
![PBI  Smart filter okviz](https://user-images.githubusercontent.com/78752624/107259133-ece5d780-6a3c-11eb-8ce7-b04d1afcbf8a.png)

Question : how many values max is possible in this visual ? 

Thx

**Comment by danieleperilli** [comment]
30K rows is the limit set by Power BI for custom visuals without incremental loading (which is included in the PRO version of Smart Filter).
