### ISSUE TITLE
Smart Filter Pro isnt work

### ISSUE THREAD

**Issue by pawa1412** [okviz/free-visuals#239]
Hello, 

first of all, thanks for the tool it's amazing.
However, when I try to filter a specific item the filter does not work. I thought at first that it could be because of the number of records, but the site says to allow unlimited rows, so I don't know what the problem can be anymore.
it´s working with values under 300000, but when i try the 339326 for example it does not work.

I sending you the repository by mail, because it's confidential

**Comment by danieleperilli** [comment]
This forum is just for free visuals. The support team will reply via email.
