### ISSUE TITLE
Bullet Chart - Tooltip highlighted not translating

### ISSUE THREAD

**Issue by francismcguire** [okviz/free-visuals#240]
**Describe the issue**
The default tooltip does not translate like it should. When i click on a field in another visual, thus filtering the Bullet Chart, the tooltip shows the "highlighted" value. Normally, when a report is in French, it should say "En surbrillance" instead of highlighted. Unfortunately this isn't the case with Bullet Chart by OKViz

**Steps To reproduce**
1. Open report, change language setting to French (France) in the global regional settings, 
2. create a bullet chart
3. create another visual
4. click on a category in the second visual to effectively filter the bullet chart
5. notice that the tooltip says "Highlighted" instead of "En surbrillance"

**Affected environment**
 - Power BI Desktop Latest version
 - Power BI service

**REQUIRED: Repro file**
[BulletChartToolTipTranslationBugExample.zip](https://github.com/okviz/free-visuals/files/5997571/BulletChartToolTipTranslationBugExample.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/43823742/108245456-4bd2dd00-711e-11eb-8f1a-b1730a49778b.png)

**Comment by danieleperilli** [comment]
In v2.2.9.4 you have now the ability to change that label.
