### ISSUE TITLE
Card with States - JSON formatting

### ISSUE THREAD

**Issue by harshit-tayal** [okviz/free-visuals#241]
I am trying to make a JSON theme for power BI report that uses card with states by OKVIZ but I cannot figure out the names of the variables to set their properties. 
Just like I want to change the default values of States and Condition property property but I can’t because I don’t have their actual parameter names. I am able to get the names of some attributes that I am sharing with you.
![OKVIZ](https://user-images.githubusercontent.com/79261068/108358641-fb8a7680-7214-11eb-895c-4a468e14f8f0.png)

**Comment by danieleperilli** [comment]
It doesn't support JSON themes. It's something not yet fully available to custom visuals.

**Comment by harshit-tayal** [comment]
chup kr

**Comment by harshit-tayal** [comment]
any update when it is going to support JSON themes
