### ISSUE TITLE
Syntoptic - Version confusion.

### ISSUE THREAD

**Issue by Thell** [okviz/free-visuals#242]
I went to add Synoptic Panel to my Organization Visuals and now seem to have three differently dated version from which to choose. Which should be used or are they all the same?

From the Organization Visuals search results:
![image](https://user-images.githubusercontent.com/2185020/108638429-d5ebb000-7454-11eb-97a6-d612326be918.png)

From the homepage:
![image](https://user-images.githubusercontent.com/2185020/108638444-e9971680-7454-11eb-9eeb-9bf70fc09ccc.png)

From the AppSource web site search:
![image](https://user-images.githubusercontent.com/2185020/108638639-cde04000-7455-11eb-873e-071d2721da38.png)

**Comment by danieleperilli** [comment]
We changed the website, no more confusions on the versions.
