### ISSUE TITLE
Multi-Cards with States - No Cross Filter Functionality?

### ISSUE THREAD

**Issue by bwt615** [okviz/free-visuals#243]
Would be great to be able to click on a multi-card and have it filter on what was used for the category (e.g. click on a card - everything else filters). Reached out to your email about this as a commercial proposition.

Thanks!

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
