### ISSUE TITLE
I can not sync the Smart Filter by OKViz on multiple pages

### ISSUE THREAD

**Issue by adriansuteu933** [okviz/free-visuals#245]
I have the free Smart Filter by OKViz and when I try to sync it to keep the selected items on multiple pages, I click on it and then the Sync slicer section is blank.

I have the same slicer (Smart Filter) on multiple pages.

![image](https://user-images.githubusercontent.com/80310687/110431998-3d416b00-80b7-11eb-98d6-7b9776645630.png)

**Comment by danieleperilli** [comment]
The sync slicers feature is available only in the PRO version of Smart Filter Pro: https://okviz.com/smart-filter-pro/
