### ISSUE TITLE
Card with States - drag and drop the visual to new position

### ISSUE THREAD

**Issue by weiinldn** [okviz/free-visuals#246]
**Describe the issue**
I tried to move the visual to a different position on the dashboard but found it is not possible. The visual's position can only be changed by resizing it. 

**To reproduce**
load data via a spreadsheet
add the visual "Card with states" and select the measure data
the visual position is locked and cannot be moved by drag and drop

**Affected environment**
 - Power BI Desktop (2.90.782.0 64-bit (February 2021))

[Card_with_States_Drag_n_drop_issue.zip](https://github.com/okviz/free-visuals/files/6116400/Card_with_States_Drag_n_drop_issue.zip)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
