### ISSUE TITLE
It is not possible to use Synoptic Panel in Power BI Report Server in Custom Authentication mode

### ISSUE THREAD

**Issue by lotfi1008** [okviz/free-visuals#249]
It is not possible to use Synoptic Panel in Power BI Report Server in Custom Authentication mode.
Visual Synoptic Panel does not display output when uploading the dashboard (pictured below)

![9c4cb044-ec90-413c-bfd1-2955433cbfa1](https://user-images.githubusercontent.com/11138434/111002972-8a655b80-839b-11eb-848e-6ff93d486240.jpg)

We used the following code to implement Custom Authentication
https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
