### ISSUE TITLE
Synoptic Panel - Category State Colour Bug on page change when measure is filtered to return a single record

### ISSUE THREAD

**Issue by cpuah** [okviz/free-visuals#250]
**Describe the issue**
The dataset relates to the number of injuries recorded with their respective body location mapped onto the panel.
When the filter reduces the returned rows down to a single row (i.e. count of 1), the visual will be colored black when you click off the main page onto a second page and then return to the main page.

**To reproduce**
See attached pbix flie
1) Open attached file
![image](https://user-images.githubusercontent.com/33239123/111090186-cc9ac280-857e-11eb-9039-0158eefd7b33.png)

2) In the filter, select 19307, visual highlights Back = RED
3) Click on Page 2 tab
![image](https://user-images.githubusercontent.com/33239123/111090192-d45a6700-857e-11eb-880f-cbceeb290c18.png)

4) Click on Main Page Tab to return
5) Visual bugs out and is colored black.
![image](https://user-images.githubusercontent.com/33239123/111090199-e0debf80-857e-11eb-8c19-bbdb699742fa.png)

**Affected environment**
 - Power BI Desktop (include the version: E.g.: Dec 2020)
 - Power BI service
 - Power BI iOS app
 - Power BI Android app
[HSe_Report_Issue.zip](https://github.com/okviz/free-visuals/files/6138011/HSe_Report_Issue.zip)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
