### ISSUE TITLE
Bullet Chart - States not working with a measure

### ISSUE THREAD

**Issue by svenvu** [okviz/free-visuals#255]
When using the awesome bullet chart in a dataset that contains a calculation group, the field "States" can not be used with a measure. All other fields like Category, Value, Comparison Value, Targets and Tooltips work fine. 

Could you please let "States" also work when using a measure for States?
I can't complete the bullet chart without the beautiful States :(

Friendly greets and much appreciated if this could be fixed!

**Comment by fcailleau** [comment]
Same here :/ did you find a workaround ?

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
