### ISSUE TITLE
Sparkline - separate high/low points formatting for each series

### ISSUE THREAD

**Issue by olgarudakova42** [okviz/free-visuals#256]
Hi. thank you guys, for what you are doing.
I would like to put several KPI's in form of sparkline next to each other. For some of them high is bad (ex. Q-line length), so I want to have high point red; for some low is bad (items per transaction) so I want to have low point red.
Currently work that around by  stacking 8 separate sparklines on top of each other. 
Working file [https://drive.google.com/file/d/1uyrmI5QeRZspoirGxnsT6H7Z2Qj0iPNK/view?usp=sharing](url)

**Comment by danieleperilli** [comment]
I'm closing this issue as it is very old and we did not collect enough information in time. Feel free to reopen it explaining your needs better and adding an example report file.
