### ISSUE TITLE
Card with states - change the color of datalabel and trendline at the same time

### ISSUE THREAD

**Issue by olgarudakova42** [okviz/free-visuals#258]
**Describe the issue**
It would be nice, I f I could change the color of datalabel and trendline at the same time

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service

**REQUIRED: Repro file**
[Customer conversion monitoring.zip](https://github.com/okviz/free-visuals/files/6252510/Customer.conversion.monitoring.zip)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
