### ISSUE TITLE
Card with States - display percentage format when CG are in the model

### ISSUE THREAD

**Issue by lukasKrk** [okviz/free-visuals#259]
**Describe the issue**
Card with States visual displays results of a measure in a decimal format, even if the measure has other format (in this case percentage). The behaviour returns to normal only when format expression string are removed form every calculation items in a model. 

**To reproduce**
In the repro file remove format expression strings from calculation items in calculation groups :
- ^base_frekwencja[%resp..]
- ^base_wynik[%resp..]

**Affected environment**
 - Power BI Desktop  for Report Server - Version: 2.88.2361.0 64-bit (January 2021)
 
**REQUIRED: Repro file**

[card_with_states_display_format.zip](https://github.com/okviz/free-visuals/files/6252785/card_with_states_display_format.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/81862079/113482240-fbc99300-949d-11eb-8598-46ff0cd93991.png)

**Comment by danieleperilli** [comment]
Custom formatting with calculation groups is not yet supported by custom visuals.

**Comment by lukasKrk** [comment]
Even if the measures used in the visual have nothing to do with calculation groups? 
In my uploaded example , the measure used in a visual is a basic measure that is not related to any calculation group.
Does it mean that in order for the visual to work correctly there cannot be any calculation group in a model (regardless of whether they are used in a measures used in a visual or not?

**Comment by marcosqlbi** [comment]
Yes, unfortunately this is what happens. You can see the same problem by using any other custom visual or standard visuals like Funnel, which still doesn't support the new format. We need Microsoft to fix the API and then we can provide an updated component.

**Comment by lukasKrk** [comment]
Thank you for clarification. I just recently started using calculation groups (thanks to your great articles) and this is the first time I encountered this problem with custom visuals. 
Have a Happy Easter :)

**Comment by AlanMcKevittIVCE** [comment]
Hi! 
I found this post after I encountered the same problem - percentage formatted measure not showing as percentage due to calculation groups in data model.  Is there any fix for it available yet?  Or is it just something we are going to have to live with?
