### ISSUE TITLE
Synoptic Panel - Word wrap doesn't work

### ISSUE THREAD

**Issue by emilianocapasso** [okviz/free-visuals#26]
Hello,
I've been trying to understand how to make the text wrapping inside an area,
from your example it should work easily by activating "Word Wrap" but it doesn't work

I'll send you a pbix file by email for privacy

**Comment by danieleperilli** [comment]
I just checked your file. The issue is caused by the fact that we apply word wrap only to columns field, not to measures. You have put strings in the main measure, but the visual is not able to manage it. It is something we will change in the future, but I can't say when, sorry.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
