### ISSUE TITLE
Synoptic Panel - Tooltip showing "Area" for unbound regions

### ISSUE THREAD

**Issue by Mike-Honey** [okviz/free-visuals#260]
**Describe the issue**
A tooltip shows "Area" for all unbound regions of the visual, including the text inside the innermost boxes (bound areas).  Can this be avoided?  Ideally tooltips would only be shown for bound regions, and the tooltip's area would include any inner nested area that is unbound.

**To reproduce**
Create Synoptic Panel using SVG file provided. Assign data columns to the Category and Measure wells. Hover the mouse over the visual. All unbound regions will show a tooltip "Area".  Only the edges of bound regions (seemingly excluding their text?) will show a correct tooltip.

**Affected environment**
 - Power BI Desktop (March 2021)
 - Power BI service

**REQUIRED: Repro file**
Attached: [Synoptic Panel repro - 2021-04-08.zip](https://github.com/okviz/free-visuals/files/6275204/Synoptic.Panel.repro.-.2021-04-08.zip)

**Screenshots**
See below:
1 - unbound area shows "Area" tooltip
2 - text inside bound area shows "Area" tooltip
3 - edge of bound area only (outside inner text) shows correct tooltip
![Synoptic Panel repro - 2021-04-08 issue 1 pic 1](https://user-images.githubusercontent.com/9509644/113951375-cda9d180-9856-11eb-95ed-1c259e4c8506.png)

![Synoptic Panel repro - 2021-04-08 issue 1 pic 2](https://user-images.githubusercontent.com/9509644/113951395-d4d0df80-9856-11eb-8308-3a8242809c2a.png)

![Synoptic Panel repro - 2021-04-08 issue 1 pic 3](https://user-images.githubusercontent.com/9509644/113951411-dac6c080-9856-11eb-8896-adeca01a3888.png)

**Comment by danieleperilli** [comment]
Unfortunately, it's not possible. We evaluate it for future updates.
