### ISSUE TITLE
Synoptic Panel - Selecting a bound region fades everything out

### ISSUE THREAD

**Issue by Mike-Honey** [okviz/free-visuals#261]
**Describe the issue**
When a bound region of the visual is selected, everything on the visual is faded so much as to be unreadable.  Can this be avoided?

Ideally, we could adjust the Transparency % that is applied for this action, to suit the colors used in each Synoptic Panel instance.

**To reproduce**
Create Synoptic Panel using SVG file provided. Assign data columns to the Category and Measure wells. Select any bound area. Everything (SVG shapes and text, bound areas) is faded so much as to be unreadable.

**Affected environment**
 - Power BI Desktop (March 2021)
 - Power BI service

**REQUIRED: Repro file**
Attached: [Synoptic Panel repro - 2021-04-08.zip](https://github.com/okviz/free-visuals/files/6275221/Synoptic.Panel.repro.-.2021-04-08.zip)

**Screenshots**
See below:
1. Synoptic Panel as displayed on opening the page
2. Synoptic Panel after a bound area is selected. If you squint you can just see some faint grey shapes.

![Synoptic Panel repro - 2021-04-08 issue 2 pic 1](https://user-images.githubusercontent.com/9509644/113951855-c505cb00-9857-11eb-93d6-9422e2d017b7.png)

![Synoptic Panel repro - 2021-04-08 issue 2 pic 2](https://user-images.githubusercontent.com/9509644/113951869-cb944280-9857-11eb-8996-99448fc162b6.png)

**Comment by danieleperilli** [comment]
Unfortunately, it's not possible. We evaluate it for future updates.
