### ISSUE TITLE
Bullet Chart - visual wont refresh in dashboard

### ISSUE THREAD

**Issue by xavierwq** [okviz/free-visuals#263]
Whenever i pin an okviz visual to a dashboard, the data on the dashboard tile wont be updated as my PBI report visual. 

e.g. i have a bullet chart created in my PBI report, the value i have today is 80%. I pin the bullet chart to my dashboard. The next day, my PBI report is refreshed with the latest dataset and my value now is 90%. however the dashboard tile will still show 80%. 
(i have click on refresh in dashboard too). 

tested on okViz KPI card too, wont refresh in dashboard

The only way i can do now is to delete and repin the visuals. 

Is there a way i can solve this issue?

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
