### ISSUE TITLE
Synoptic Panel - General questions

### ISSUE THREAD

**Issue by freesmith** [okviz/free-visuals#264]
Hi,
we've got 2 questions:
1. We want to simulate the stadium attendance example (see image below). We have the X, Y coordinates of each seat, can we somehow use that information, or do we manually have to create each seat with the synoptic designer (48.900 seats)?

![image](https://user-images.githubusercontent.com/5021011/116385182-d3bd1d80-a818-11eb-8a8e-9f0324f21b5a.png)

2. Is there any way of dynamically changing the measure in the chart? For example, lets say we have a dropdown in the report that shows: ticket holders, season ticket holders and both. The ideal use case, you select an option and based on the selection it populates the synoptic panel values/measures with this option.

Thanks

**Comment by danieleperilli** [comment]
1. You have to create the map.
2. Unfortunately, you can't change the data binding on the fly, so not, it's not possible.
