### ISSUE TITLE
Synoptic Panel - Pop Up Menu

### ISSUE THREAD

**Issue by saguado69** [okviz/free-visuals#266]
Hello,

I'm trying to use Synoptic Panel as a data slicer, so I have an SVG containing 2 shapes that are matching my data. Everything works fine buit whenever I mouseover the visual, the pop up menu with Change/Load and Gallery options appears.

I would like to know if there is any way to disable the menu once an image is loaded into the component.

Thanks.

![image](https://user-images.githubusercontent.com/45149331/116990046-de712a00-acd2-11eb-9ef2-62e0e8100497.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
