### ISSUE TITLE
Synoptic Panel - I have multiple panels that use the same data set and I would like to change between them by filtering.

### ISSUE THREAD

**Issue by LorentzAspen** [okviz/free-visuals#268]
I would like to filter/flip thorugh multiple panels/drawings which are connected to the same dataset in the same PowerBI window and not be required to set up a new page for each. Would this be possible to allow for in the plugin?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
