### ISSUE TITLE
Bullet Chart - Target Color Not Working

### ISSUE THREAD

**Issue by jggude** [okviz/free-visuals#27]
Select different colors for different targets but targets aren't changing colors
![Screenshot (1)](https://user-images.githubusercontent.com/52678847/60842052-da3c5a00-a198-11e9-83d7-9ff9bf4d267f.png)

**Comment by danieleperilli** [comment]
Please, provide a repro file.

**Comment by jggude** [comment]
What is a repro file?

**Comment by danieleperilli** [comment]
A sample file used to reproduce the issue.
