### ISSUE TITLE
Synoptic Panel - Incorrect color saturation

### ISSUE THREAD

**Issue by mah65** [okviz/free-visuals#272]
I have a visualisation that shows count of injuries per body location. The higher the count, the higher the saturation should be.
I however have encountered situations where body parts are colored incorrectly. 

For example, they show different saturations while the count in each part does not indicate that. Here are the OkViz plots.

![image](https://user-images.githubusercontent.com/10214950/119421590-654d7b80-bd42-11eb-81de-37b8e374de8d.png)

or

![image](https://user-images.githubusercontent.com/10214950/119421677-99c13780-bd42-11eb-882f-4c09796385f9.png)

or 

![image](https://user-images.githubusercontent.com/10214950/119421807-e86ed180-bd42-11eb-8627-31487aec03ae.png)

Another problem is that sometimes the plot shows black colors upon changing the value of slicer filter. Figure below:

![image](https://user-images.githubusercontent.com/10214950/119420976-f58ac100-bd40-11eb-80b6-7a3a057a22cc.png)

I have chosen saturation level as 20-100.

OkViz version: 1.5.0
Power BI Desktop version: 2.93.641.0 64-bit (May 2021)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
