### ISSUE TITLE
Synoptic Panel - Issue with map and slicer

### ISSUE THREAD

**Issue by powerbiusr** [okviz/free-visuals#273]
**Describe the issue**

I’m using a map of Synoptic Panel from OKViz and when I try to filter on a slicer list clicking on the map, there is no response. If I replace the slicer with table or matrix and I do the same, there is no problem. But I need to use slicer.

Is there any way to solve this problem modifying features o whatever or is it Synoptic panel error and there is no solution?

Also I would like to know why every time I click on a new map area it takes a long time changing the selected area. I seems like if it was looking for something. But the data I am using for it is in my computer, not in the network.

**Affected environment**
 - Power BI Desktop 

**Screenshots**

If I select the area in the map in a red circle, there is no effect on the slicer list on the right (Image 1).

<img width="436" alt="Image 1" src="https://user-images.githubusercontent.com/85337489/120786782-ec62d680-c52e-11eb-9ad8-43b3f5f1853c.png">

If I replace the slicer with a matrix, clicking on the map area it filter the list as is expected (Image 2).

<img width="422" alt="Image 2" src="https://user-images.githubusercontent.com/85337489/120786788-ecfb6d00-c52e-11eb-8f37-44fdafbd4240.png">

Thank you very much in advance.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
