### ISSUE TITLE
Area name changes position after applying the filter

### ISSUE THREAD

**Issue by Sinchetru** [okviz/free-visuals#275]
**Describe the issue**
After I apply filters on the visuals the data labels change position even though it is set to "middle" mode. Removing filters does not return the data labels to the middle position. To return the data labels to the original position it is necessary to upload the SVG image again. How can I avoid this behavior?

**To reproduce**
Open the file.
Load the SVG file int to the visual. The Room Label will change position to the middle. 
Try to filter any room with the "Raum ID" filter and then delete the filter. The room number will change its position.

**Affected environment**
 - Power BI Desktop for PBI Report Server (version: Mai 2020)

**REQUIRED: Repro file**
[Data.zip](https://github.com/okviz/free-visuals/files/6680443/Data.zip)

**Screenshots**
![After filtering](https://user-images.githubusercontent.com/22330324/122638416-4600fe80-d0f4-11eb-8352-ea07e3551087.png)
![Before filtering](https://user-images.githubusercontent.com/22330324/122638417-46999500-d0f4-11eb-8470-d690cac83277.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
