### ISSUE TITLE
Card with States- Need asssitance to change color of part of the multiple values

### ISSUE THREAD

**Issue by Duviea** [okviz/free-visuals#277]
**Describe the issue**
Its not a bug --Hi,

I’m using the multiple card definition
And the target as the previous month value
Can I change on each one of the Elements on the card the color of the Font to Red if the previous month is higher.
Need this when the trend is a negative one- e.g. lost customers.

Or should I be setting the values differently in the visual.

Thanks in advance

**To reproduce**
Steps to reproduce the behavior.

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
