### ISSUE TITLE
Synoptic Design - Cannot highlight more than 1000 blocks in Power BI when each block has multiple entries. 

### ISSUE THREAD

**Issue by joshashwin** [okviz/free-visuals#278]
Synoptic Design - Cannot highlight more than 1000 blocks in Power BI when each block has multiple entries. The blocks / Areas highlight is limited to 1000 entries or less... Please increase this limitation to 10,000 minimum or provide alternative options to address the issue.

**Affected environment**
 - Power BI Desktop 

**REQUIRED: Repro file**
I've emailed the reports to support@okviz.com for reference and support. Also, the screenshot report is attached in the email indicating the exact issue

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
