### ISSUE TITLE
Smart Filter not visible anymore in IE, but in Chrome working fine

### ISSUE THREAD

**Issue by mt89** [okviz/free-visuals#28]
The smart filter visual in our published reports is not visible/working anymore. The bug occurs just when opening the report with IE. When i'm opening the same report with chrome, the filter works and is visible as supposed.

PowerBi Version: 2.70.5494.761 , 64bit (June 2019)
IE: Version 11.557.17763.0 / Updateversion: 11.0.130 (KB4503259)

**Comment by danieleperilli** [comment]
Please, provide a sample report, so we can reproduce the issue.

**Comment by schand03** [comment]
We are facing the same issue.

**Comment by mt89** [comment]
It's not really file releated. All the smart filters in various files are not visible anymore in IE. In Chrome & Edge it's working fine. 

Attached a screenshot with the comparison between IE & Chrome. 
[Comparison.pdf](https://github.com/okviz/free-visuals/files/3380522/Comparison.pdf)

**Comment by danieleperilli** [comment]
I see. Thanks for reporting. We are in talking with Microsoft and the issue should be solved in a couple of days, hopefully.

**Comment by avinash726** [comment]
We are also facing the same issue with smartFilterByOKViz-1.1.8B visual. Is there any update on this?

**Comment by schand03** [comment]
Looks like its resolved. Thanks for the quick turnaround

**Comment by danieleperilli** [comment]
Nice, thanks for the feedback.

**Comment by danieleperilli** [comment]
Fixed in v1.2.4. Waiting for Microsoft release in the marketplace.
