### ISSUE TITLE
Card With States - Measure and Target does not respect order

### ISSUE THREAD

**Issue by janscas** [okviz/free-visuals#280]
**Describe the issue**
When using multiple cards (multiple measures) I want to set a target for each measure. Suppose I want to show the sales, the budget and some other measures.

The target for the Sales measure is SalesPY, The target for the budget we set the Sales measure again (so I can just set the color to red or black if budget is bigger than Sales)

When using this approach the order of the measures and target areas is applied as described but the visual does not respect it.

**It sets the target of Sales to itself and the sets the target of budget to SalesPY which is incorrect.**

**To reproduce**
Just set multiple measures and use one measure used  in the measure are also in the target area. The visual will ignore the order and set the same measure as the data and target.

**Affected environment**
 - Power BI Desktop (June 2021)
 - Card With States visual from appsource 1.6.5 (tested also on the imported version 1.6.7)

**REQUIRED: Repro file**
[issue card with states.zip](https://github.com/okviz/free-visuals/files/6776533/issue.card.with.states.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/7224106/124747738-8baa2d80-df22-11eb-8f96-06d2cfd9d398.png)

**Comment by janscas** [comment]
UPDATE: Same happens with the conditions (?) field.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
