### ISSUE TITLE
Sparkline: Not able to modify after creation

### ISSUE THREAD

**Issue by JaMaKo21465** [okviz/free-visuals#281]
**Describe the issue**
After creating a visual with your great sparkline, I'm not able to modify it after doing something else in the Power-Bi Report, like filtering or just switching to another visual and come back to the sparkline. The modify area is not re-appearing.

**To reproduce**
Create a sparkline; change to another visual and filter or modify; Try to come back to the former created sparkline to edit.

**Affected environment**
 - Power BI Desktop Mai 2021

**REQUIRED: Repro file**
 - sorry not able to share business-data but, error should be easy to be reproduced by your own - 
**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by danieleperilli** [comment]
I guess this is a temporary problem that should be fixed. If the problem persists, reopen it, but keep in mind that we cannot do any analysis without a sample report file.
