### ISSUE TITLE
Sparkline - Value Label formating applies the format of the first value to all values in sparklines

### ISSUE THREAD

**Issue by cpassuel** [okviz/free-visuals#283]
[Sparkline bug.zip](https://github.com/okviz/free-visuals/files/6969026/Sparkline.bug.zip)

Hello

I found an issue in the sparkline visual about value label formatting: it applies the format of the first value to all value labels in the sparkline.

In the attached pbix, I created 2 measures, one formated as percentage, the other one as a decimal number. I added 2 sparkline visuals, one with the decimal measure at first value, the other one with percentage measure at first value.

As you can see, in the first visual, all value labels are displayed as decimal and in the second one as percentage. I didn't find a way to change this behaviour. That's unfortunate because this visual is very usefull.

Thanks
Regards

**Comment by danieleperilli** [comment]
Sparkline is designed to share the same scale, so the suggested solution is to use two different instances of the visual.
