### ISSUE TITLE
Visual Name - Issue description

### ISSUE THREAD

**Issue by DawnHeMS** [okviz/free-visuals#285]
**Describe the issue**
Dear Team, 
We encountered a problem while using Synoptic Panel in our Power BI report. The report is embedded in a web page, and there's buttons to switch between two diagrams, namely, one is the Synoptic Panel map, and the other one is Shape map. Once we clicked the maps in Synoptic Panel for zooming, the switch buttons couldn't work properly. This problem only appears on the embedded report, and everything works properly in Power BI desktop.
Could you please help on this issue?

**To reproduce**
Steps to reproduce the behavior.
 - Open a web page through a browser, in which the report embedded
 - click "经销商分布” button
 - click on the map
 - click “按省份筛选” (not work)

**Affected environment**
 - Power BI service

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***
[Ticket.zip](https://github.com/okviz/free-visuals/files/7012537/Ticket.zip)

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
