### ISSUE TITLE
Independent Y Axis for Categories

### ISSUE THREAD

**Issue by leoguimaraes** [okviz/free-visuals#288]
In Bullet Chart, if the categories have values very different from each other, the component behaviour is similar to a barchart, because all categories use the same Y Axis.

Is that possible to have this chart using a Y Axis for each category? This way the bars will have it's own proportion as expected in Bullet Charts.

Example expected behaviour:
![image](https://user-images.githubusercontent.com/25464872/131358765-73d5fc96-78dc-4641-93eb-5bbd9aa2ea51.png)

Example current behaviour:
![image](https://user-images.githubusercontent.com/25464872/131359190-b65919e6-a699-4154-88dc-1f9fbef9c9b6.png)

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
