### ISSUE TITLE
Smart Filter not clearing when report is opened

### ISSUE THREAD

**Issue by bseefelt** [okviz/free-visuals#29]
I select 1 item in the filter list and report filters correctly.  The value I selected shows at top of filter box as expected.  I close report, re-open report.  The data is still filtered to that 1 value, but there is nothing the filter box to indicate it is filtered.  I have to click the eraser to get the filter to reset.  It is misleading since a user does not know the filter is active, so it appears the report has the wrong values.

**Comment by danieleperilli** [comment]
Can you provide a sample report, please?

**Comment by danieleperilli** [comment]
Which browser are you using? Have you tried another one?
**Can you please provide a sample report?**

**Comment by bseefelt** [comment]
It happens in Chrome and Edge.  I will try to mock up an example to send you.  Thanks.

**Comment by bseefelt** [comment]
This small example exhibits the behavior when published to powerbi.com.  Interestingly, it seems to even happen across sessions in this sample.  
[TestClients.zip](https://github.com/okviz/free-visuals/files/3397383/TestClients.zip)

**Comment by danieleperilli** [comment]
Unfortunately, your example works well for me. I selected a value in edit mode, I saved and I reloaded the page. The value is kept and the search box is pre-filled with that value. Have you tried to clear your browser's cache?

**Comment by bseefelt** [comment]
That's a little different than what I am doing.  I am not using Edit mode.  I am doing all of this in View mode only.

**Comment by danieleperilli** [comment]
If you are in View mode, the state is not saved. Anyway, in your sample there isn't any issue: if I had pre-selected something, change the selection without saving and I reload the report, the previous selection is displayed and the filter display it accordingly. 
At this point, perhaps a screencast would help :)

**Comment by bseefelt** [comment]
I agree it is fine that the previous filter state is still there.  My only issue is that it doesn't indicate the correct filter state.  The client's name disappears from the display, so it appears to the user that there is nothing selected in the filter.

**Comment by danieleperilli** [comment]
As I said, this **not** happens with the sample you provided on my browser.

**Comment by bseefelt** [comment]
Daniel, if you have time would it be possible to do a screen share so you can see what I am talking about?

**Comment by danieleperilli** [comment]
Sorry, we don't provide this kind of support for free visuals. You can record a screencast and post here.

**Comment by bseefelt** [comment]
Here is the screencast.  Thanks again for your help with this.

[Uploading ScreencastOKViz.zip…]()

**Comment by danieleperilli** [comment]
It seems the zip has not uploaded. Did you close the issue because is solved?

**Comment by bseefelt** [comment]
No, I didn't close it.  It went to closed when I tried to upload the file.

Trying 1 more time...
[Uploading ScreencastOKViz.zip…]()

**Comment by bseefelt** [comment]
Attaching zip file here…

**Comment by danieleperilli** [comment]
No way. Please send it support@okviz.com

**Comment by danieleperilli** [comment]
I received the screencast and recreated the conditions on the video – I had a different selection, so I couldn't see the problem before. 
This is what happens: you change the selection and Power BI saves the new selection **also if the report is in View Mode**.  
Unfortunately, this behavior is supported only by Smart Filter Pro, because it acts like Power BI bookmarks do. It's difficult to explain, but from the internal perspective is almost the same behavior. So, because the free version doesn't support bookmarks and we can't know if you are using a bookmark or the report is recalling a selection saved when it was in view mode, the visual doesn't restore the selection.

**Comment by bseefelt** [comment]
Ok.  Thanks for your time and for the explanation.
