### ISSUE TITLE
Visual Name - Issue description

### ISSUE THREAD

**Issue by gabrielndo** [okviz/free-visuals#296]
I wanted to show on a matrix, the tooltips of a report page, but in this visual, I can’t do this, we are just able to select columns.

I developed a risk matrix, using your visual off synoptic panel in Power Bi.

Is there any way to create tooltips like this?

 - Power BI Desktop (include the version: E.g.: April 2020)

![Sample](https://user-images.githubusercontent.com/92583470/137485384-5f6f6e3e-6a36-4265-966a-6d7e9c06a18d.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
