### ISSUE TITLE
Synoptic Panel - Feature request

### ISSUE THREAD

**Issue by deacaroo** [okviz/free-visuals#298]
![92364B46-CB5A-4641-B2E9-976CC0EFE359](https://user-images.githubusercontent.com/43534676/140604635-f8e92192-3b10-4017-8a1a-eec71205b820.jpeg)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
