### ISSUE TITLE
Card with States - Show Data Option sorts Descending 

### ISSUE THREAD

**Issue by rachelruiz** [okviz/free-visuals#3]
Hello - I am using the Cards with States to trend 12 months of data. The trend line sorts in the correct, ascending order, but when you click Show Data, the data column sorts descending (see attached)
![card with states sorting issue](https://user-images.githubusercontent.com/48289882/53893725-fd3cde80-3feb-11e9-86c6-fc64a5eccec7.PNG). This means you read the chart left to right at the top of the page, but right to left at the bottom of the page. Can you please either default the Show Data columnar data to sort ascending to match the chart or provide the option to do either? The ellipses does not provide a sorting option like other charts and clicking on the date column header on the below chart does not change the sort order. Thanks!

**Comment by danieleperilli** [comment]
Thanks for reporting it. We are working on an updated version of this visual and we will include a fix there. I will close the issue when we release the fix.

**Comment by danieleperilli** [comment]
The issue has been fixed in v1.5.0. We are waiting for Microsoft release in the marketplace.
