### ISSUE TITLE
Problem uploading svg file in Synoptic Panel & Synoptic Designer

### ISSUE THREAD

**Issue by iyneedham** [okviz/free-visuals#30]
My org's graphic team created an svg map for US States with initials, which I'm planning to use with The Synoptic Panel visualization.

When I try to upload the svg file into Synoptic Panel directly, nothing happens. When i try to upload it to Synoptic Designer, and hit **Export to Power BI**, the shapes are not black, so it looks like the shapes aren't mapping.  Any ideas about what's going on with the svg file?

![map1](https://user-images.githubusercontent.com/6756994/61379944-7ab80b80-a876-11e9-9e6c-36cd554cc251.png)
![exportmap](https://user-images.githubusercontent.com/6756994/61379943-7ab80b80-a876-11e9-975f-a4ac8cc6ffcd.png)

**Comment by danieleperilli** [comment]
Please, provide a sample report file **and** the map you created.

**Comment by iyneedham** [comment]
[map samples.zip](https://github.com/okviz/free-visuals/files/3402842/map.samples.zip)

**Comment by danieleperilli** [comment]
The visual doesn't work well with nested areas and groups. The problem here is you assigned an id to the <g> element that contains the areas. Here is a working version (I just removed the id attribute).
[USA Map.zip](https://github.com/okviz/free-visuals/files/3405266/USA.Map.zip)

**Comment by iyneedham** [comment]
Thank you for your help. I really appreciate the prompt response.  

When I use your revised svg file, all of the state areas show up, with the exception of  the 4 states that still have nested subgroups: AK, HI, MI, & MD.  For these 4, only the outlines are working, not the area inside the outlines.  Any ideas on how I can direct my graphics team to modify the svg sow the internal areas show up as well?

**Comment by danieleperilli** [comment]
Yes, it happens because you (or the editor you used) assigned several class to the areas: one of these defines a color that cannot be overwrited by the visual. To solve: just open the map in the notepad and delete the .cls-1 {...} from the file.... or use the revised version attached :)
[USA Map-2.zip](https://github.com/okviz/free-visuals/files/3416316/USA.Map-2.zip)
