### ISSUE TITLE
Bullet Chart - Drill Through on Phone

### ISSUE THREAD

**Issue by Barre91** [okviz/free-visuals#300]
Hi,

When selecting 'Drill Through' on a visual, i should be able to view the list of pages available for drill through, but in my case, the window just closes.

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
