### ISSUE TITLE
Dynamic Synoptic Maps - Change map with a button

### ISSUE THREAD

**Issue by HazRobinson** [okviz/free-visuals#301]
**Describe the issue**
I have multiple SVG files (They are floor plans/ maps) that I want to dynamically change with a button, rather than having each map on a separate tab in PowerBI. The maps could be stored in a cloud location somewhere.

**To reproduce**
When using Synoptic Panel, consider each SVG file to represent a different floor in a building and then try to switch between them using a button in PowerBI rather than a tab. 

**Affected environment**
- PowerBi in Azure, any version

**REQUIRED: Repro file**
Please see attached
***IMPORTANT: We don't consider issues without a sample report!***

[Example for Synoptic Developers.pbix.zip](https://github.com/okviz/free-visuals/files/7547105/Example.for.Synoptic.Developers.pbix.zip)
**Screenshots**
N/A

**Comment by bisvillallai** [comment]
What you need mate is to use the MAPS field of the Synoptic Panel, and fill it with a column that contains the URL of the SVG file.
Then in a table, i.e. Floors, you'll have a column that indicates the floor (1, 2, 3, etc.) and in the second column the URL.
Finally, create a slicer with the Floor name or number, and will work just fine.
*Note: The category of the URL field must be set as URL web under the properties section.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
