### ISSUE TITLE
Synoptic Panel - Local maps doesn´t work with "new format pane"

### ISSUE THREAD

**Issue by jmendoncas** [okviz/free-visuals#306]
**Describe the issue**
Local maps option (importing local SVG file) does not work if Power BI "new format pane" preview feature is on.
The above also applies to existing reports when one wishes to change the local map/file.
It works OK if this PBI "new format pane" preview feature is turned off.

**To reproduce**
Data assigned to visual, click "Local maps" (and/or "Change") button does not launch file browser, no action.

**Affected environment**
 - Power BI Desktop (version 2.100.785.0 64-bit (December 2021))
 - "New format pane" preview feature on.

**REQUIRED: Repro file**
[Column_Insp.zip](https://github.com/okviz/free-visuals/files/7813312/Column_Insp.zip)

**Comment by marcosqlbi** [comment]
I am not able to reproduce the issue reported.
I am using the same version of Power BI Desktop you described and I opened the repro file - it works regularly.
Are you able to try on another PC? It could be something specific to your environment, but it's hard to investigate without more details.

**Comment by jmendoncas** [comment]
Hi Marco,

Many thanks for your swift reply.
After an update & restart the issue is gone, all working OK. It must have been something related to my env as you mentioned.

Many thanks!
Rgds,
Joao
