### ISSUE TITLE
Synoptic Panel - Connect PowerBI filters to the Synoptic Filter when cycling through multiple SVG files

### ISSUE THREAD

**Issue by prestondelong** [okviz/free-visuals#307]
**Describe the issue**
I would like to be able to link PowerBI filters to the filter within the synoptic panel. This would eliminate the manual step of having to switch the PowerBI filter for your data/graphs and then switching the filter to match the PowerBI

**To reproduce**
No issue - enhancement request or steps on how to connect PowerBI filters to the Synoptic panel.

**Affected environment**
 - Power BI Desktop

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
