### ISSUE TITLE
Card with States

### ISSUE THREAD

**Issue by dafzali** [okviz/free-visuals#308]
Hello, I am using card with state for showing multiline text but wrap is not working at all can you please help with this issue. 

Thanks 

![image](https://user-images.githubusercontent.com/79652755/148362935-05cefafb-4858-45ac-830b-5847e5e7211e.png)

This is how it looks like.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
