### ISSUE TITLE
Cannot download okviz Synoptic Panel

### ISSUE THREAD

**Issue by DesanoiaCM** [okviz/free-visuals#309]
**Describe the issue**
I'm trying to download the okviz Synoptic Panel but the webpage shows this error: 
`{"code":"BadRequest","correlation":"OmexNodes000002__omexexternal-prod-wus2-000_2/a08a3f8f-9fde-496c-88ae-f8ccb5afa0ab","description":"Could not understand request because: No supported clients found","time":"01/13/2022 20:43:38","debugMessage":null,"stackTrace":null}`

**To reproduce**
Go to the webpage: https://okviz.com/synoptic-panel/ and click the download button

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)

**REQUIRED: Repro file**
Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If you can't publicly share it, send it to support@okviz.com, including a reference to this issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
***IMPORTANT: We don't consider issues without a sample report!***

Not Applicable. I'm just trying to download the file from the webpage.

**Screenshots**
If applicable, add screenshots or screencast to help explain your problem.
![image](https://user-images.githubusercontent.com/88508369/149407511-199eef0b-9729-4e11-9d9d-4bb98af714db.png)

**Comment by okviz** [comment]
Fixed.
