### ISSUE TITLE
OkViz Smart Filter : Single selection is not working 

### ISSUE THREAD

**Issue by zsshweta** [okviz/free-visuals#31]
From the June 2019 Power BI update, the OkViz smart filter is not working as expected. 
Previously the single select was working fine where in if 1 value is selected it would not allow the user to select another value till the previous selection was removed. 

But now, it allows the filter to select multiple values (1), even if the single selection mode is on (2) which is causing chaos for our users as its unclear on the selection that is affecting the visuals and its also overlapping (3) some important sections of the view.

Request you to look into it at the earliest and fix the issue.
Please refer to the attached screenshot for reference
![Smart Filter](https://user-images.githubusercontent.com/52826505/61525640-72a6ca00-aa36-11e9-87e0-143cd9304212.png)

**Comment by danieleperilli** [comment]
I checked  the issue reported and I can confirm is a regression. We will include a fix in the next update we release this week. Unfortunately, the review process by Microsoft is long and it could take up to 3 weeks.

**Comment by danieleperilli** [comment]
Fixed in the v1.2.5. Just sent to Microsoft for approval.
