### ISSUE TITLE
Synoptic Panel. Long rendering on a server without Internet

### ISSUE THREAD

**Issue by SamsonovAA** [okviz/free-visuals#310]
Hello. I use this element in a pile dashboard. From PBID works fast. Published on ReportServer with internet connected works fast. Published on ReportServer with the Internet disconnected, it works very slowly, rendering the element can take up to 60 minutes. What can this problem be related to and how can it be solved?

**Comment by hocky01** [comment]
Hi,
We have the same problem. Is there a solution for this?
All seems to work great but with the exception of a long initial loading time.
Seems to be a 30s timeout somewhere?!?
Regards Håkan

**Comment by hocky01** [comment]
Solution: Set EnableCDNVisuals to False with management studio on the report server.
