### ISSUE TITLE
Card with states Pro - Trendline feature is missing

### ISSUE THREAD

**Issue by KaterinaHubenakova** [okviz/free-visuals#311]
**Describe the issue**
Trendline feature is missing

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service

**Screenshots**
added
![card with states_trendline missing_1](https://user-images.githubusercontent.com/98159415/150518693-02fe9a29-c650-4d37-b650-de557286c155.jpg)
![card with states_trendline missing_2](https://user-images.githubusercontent.com/98159415/150518826-1c4fab34-1f34-417f-b33b-085086a31c20.jpg)

**Comment by neil1111** [comment]
I have the same issue. I just installed the premium version, from the MSFT store. My license also shows as valid as the OP.
![image](https://user-images.githubusercontent.com/28867423/150608224-0d92a75b-574f-4002-8aa3-f3b46a0a7e8f.png)

PowerBI Desktop Version: 2.100.1182.0 64-bit (December 2021)
Thank you.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
