### ISSUE TITLE
Card with States - incorrect display value

### ISSUE THREAD

**Issue by Novikov-MV** [okviz/free-visuals#312]
**Describe the issue**
The value 3.7 on the card is displayed as a value with 16 decimal places
3,6999999999999997

**To reproduce**
1. Create a measure = 3.7 and leave General format (this format need for automatic decimal placas - when value is integer card display it without decimal places).
2. Use the measure in the Measures field of the Card with States (with automatic decimal placas).

**Affected environment**
 - Power BI Desktop (version: 2.100.785.0 64-bit (December 2021))
 - Power BI service

**REQUIRED: Repro file**
[Report.zip](https://github.com/okviz/free-visuals/files/7960093/Report.zip)
***IMPORTANT: We don't consider issues without a sample report!***

**Screenshots**
![image](https://user-images.githubusercontent.com/98603910/151581118-adeab266-7c20-4ca4-8b22-5fe11f2b77ed.png)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
