### ISSUE TITLE
Card with States not formatting Percentage with Calculation Group

### ISSUE THREAD

**Issue by Jake-BIV** [okviz/free-visuals#313]
Describe the issue
**IS:** Card displays a decimal Value
**Should/be:** Card should display a percent formatting per the Measure Formatting and Calculation Item Formatting.

To reproduce

1. Create a measure and set formatting to percentage
2.  Create a calculation group (in tabular editor) and calculation item. Set the item format to Percent.

Affected environment

Power BI Desktop: Version: 2.100.1401.0 64-bit (December 2021)

Tabular Editor: v2.16.5

REQUIRED: Repro file
[TestModel.zip](https://github.com/okviz/free-visuals/files/8061186/TestModel.zip)

IMPORTANT: We don't consider issues without a sample report!

Screenshots
![image](https://user-images.githubusercontent.com/92316999/153875458-452b9b32-950e-46a4-875d-a23057e6ab4b.png)

**Comment by dainiusbw** [comment]
Hello,

I can confirm, that there is issue in handling of formats of measures in Card with States.
Not only in case of percentages, but in general (maybe side-effect of "hardcode" in script of visual).
Not only in case of calculation groups, but in case of native format of measure (same percentage). 

Here examples when measure as "%"
Firs Microsof card, second - Card with states
![Percents](https://user-images.githubusercontent.com/84070456/159780689-167f4635-80b1-4dd9-ace3-b368174f3aa8.PNG)

Please check and fix.

sqlbi student,
Dainius B

**Comment by dainiusbw** [comment]
My credentials:
Desktop: Version: 2.103.661.0 64-bit
Card Pro version:1.6.8

**Comment by Guido2022** [comment]
This is a serious issue and it is definitely affected as soon as there are calculation groups and a format string at least on one of the items. The measure involved in the calculation group isn't even the same as used in the Card with States. This means, the % number gets lost and a decimal is displayed.
Please fix this otherwise the card can never be used along with calculation groups. Thank you.

**Comment by Jayclaw** [comment]
Having this problem as well and since we use this visual on the front page of most of our reports it currently means that we can't use any format string expressions in calculation groups.

Please fix!

**Comment by alexdc-24** [comment]
This will become more apparent now with the release of dynamic formats for measures. I have a calculation group for now but have also tested with the dynamiic format preview feature and it doesn't work.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
