### ISSUE TITLE
Smart Filter crashes the report page

### ISSUE THREAD

**Issue by igzes** [okviz/free-visuals#316]
Visual fails to load and crashes the report page when data elements exceed 10k

**Comment by Juan2022-Nuez** [comment]
Hello Team, We have been using the smartFilter in some BI Reports but after a version update it started to not working anymore, we have a couple of management reports that are crashing and are not readable.. We need a prompt solution to this issue.. Which is the plan to be fixed asap?? Do you have a fixing deployed planned? Thanks in advance.. BR

**Comment by danieleperilli** [comment]
Provide a sample.

**Comment by Juan2022-Nuez** [comment]
Ari/Axel,

Hi.

Please provide an example of this issue from a report.

Remember that we are in a critical situation with our customer and this issue getting worse as time passes, reports are not visible and people needs to access them..

Thanks.-

BR.-
Juan J. Nuez
 Juan J. Nuez  | Senior Specialist, IT Plantation & Pulp Operations
Tel. + (598) 456 20100 |  Fax:+ (598) 456 26971 | ***@***.******@***.***>
UPM | Ruta Vladimir Roslik Bichkov Km. 307 | Fray Bentos, URUGUAY
 www.upm.uy<http://www.upm.uy/>|  Follow Fundación UPM in Facebook <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FFundacionUPMUY&data=02%7C01%7Cjuanjose.nuez%40upm.com%7C7d37d553cadb421d41fa08d706fe16c9%7C9eab37f091c647e39c00fe8544bd272e%7C0%7C0%7C636985560719373093&sdata=anEPBdP4l%2F6pmg%2FQaS9sdg1L%2Fd%2BZabLypCyJMfRt9Nk%3D&reserved=0>
 UPM Biofore - Beyond fossils
We delive renewable and responsible solutions and innovate for a future beyond fossils.
 Join us. Be Biofore.

**Comment by Juan2022-Nuez** [comment]
Hello,

Find enclosed an error case..

BR.-.

***@***.***
Juan J. Nuez
 Juan J. Nuez  | Senior Specialist, IT Plantation & Pulp Operations
Tel. + (598) 456 20100 |  Fax:+ (598) 456 26971 | ***@***.******@***.***>
UPM | Ruta Vladimir Roslik Bichkov Km. 307 | Fray Bentos, URUGUAY
 www.upm.uy<http://www.upm.uy/>|  Follow Fundación UPM in Facebook <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FFundacionUPMUY&data=02%7C01%7Cjuanjose.nuez%40upm.com%7C7d37d553cadb421d41fa08d706fe16c9%7C9eab37f091c647e39c00fe8544bd272e%7C0%7C0%7C636985560719373093&sdata=anEPBdP4l%2F6pmg%2FQaS9sdg1L%2Fd%2BZabLypCyJMfRt9Nk%3D&reserved=0>
 UPM Biofore - Beyond fossils
We delive renewable and responsible solutions and innovate for a future beyond fossils.
 Join us. Be Biofore.

**Comment by danieleperilli** [comment]
Please attach the file to this thread on github.com or send the attachment to support@okviz.com, any attachments are lost if you reply to the Github email notification.

**Comment by Juan2022-Nuez** [comment]
Hi,

Sending again the file..

BR.-


***@***.***


Juan J. Nuez
 Juan J. Nuez  | Senior Specialist, IT Plantation & Pulp Operations
Tel. + (598) 456 20100 |  Fax:+ (598) 456 26971 | ***@***.******@***.***>
UPM | Ruta Vladimir Roslik Bichkov Km. 307 | Fray Bentos, URUGUAY
 www.upm.uy<http://www.upm.uy/>|  Follow Fundación UPM in Facebook <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FFundacionUPMUY&data=02%7C01%7Cjuanjose.nuez%40upm.com%7C7d37d553cadb421d41fa08d706fe16c9%7C9eab37f091c647e39c00fe8544bd272e%7C0%7C0%7C636985560719373093&sdata=anEPBdP4l%2F6pmg%2FQaS9sdg1L%2Fd%2BZabLypCyJMfRt9Nk%3D&reserved=0>
 UPM Biofore - Beyond fossils
We delive renewable and responsible solutions and innovate for a future beyond fossils.
 Join us. Be Biofore.
