### ISSUE TITLE
Okviz Bullet Chart - Too few Target markers

### ISSUE THREAD

**Issue by Hampus1990** [okviz/free-visuals#318]
Hi!
To start off, I really enjoy the OKVIZ Bullet chart, helps me alot!. However, I got one issue, when creating the Bullet Chart Im only able to set 4-5 target markers successfully, If I try to add more than that they are not applied to my visual. Is there some way for me to add more target markers? I'm going to need at least 10 target markers.

Kind Regards
Hampus

**Comment by danieleperilli** [comment]
Added in v2.2.9.4.
