### ISSUE TITLE
Synoptic Panel Power Bi

### ISSUE THREAD

**Issue by LILASamu41** [okviz/free-visuals#320]
I have a problem with the visual. I have created a layout with 4000 spaces for Power Bi. The reference is an Excel list with 4000 lines. After I put everything in Power Bi the visual spaces are still black and don't show Data but if I try it with the same list but has only 700 lines then it works and the visual is showing data and is don't black anymore. Do you know any fix for this issue and can help me?

**Affected environment**
 - Power BI Desktop Version: 2.100.1381.0 64-bit (January 2022)

**Screenshots**
![image](https://user-images.githubusercontent.com/101877949/159012189-76f06a0a-5694-4916-8052-de391f17e998.png)
First Image is a Layout with 4000 spaces and reference Excel-List 4000 lines

![image](https://user-images.githubusercontent.com/101877949/159012399-2e7b92b0-8394-4edf-bca7-ffa4467dda7e.png)
Second Image Layout with 4000 Spaces and reference Excel-List 770 lines

**Comment by NickDMBE** [comment]
@LILASamu41 : did you create the layout manually ? or do you have way to map the blocks automatically and to rename them ?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
