### ISSUE TITLE
Card with States by OKVIZ - boxes are blank

### ISSUE THREAD

**Issue by HassePersson** [okviz/free-visuals#321]
**Describe the issue**
We have used the "Card with States by OKVIZ" in PowerBI in our organization for years and it has worked brilliant untilnow . But since last week all boxes are blank. it works fine in the Desktop enviroment but all published "OKviz" onbjects to www.powerbi.com are blank, you can see the header but no figures.

We have found a workaround, if you just zoom out and zoom in you get the figures in the boxes but we need of course find a solution without be able to zoom out <=> zoom in

Anyone else that has expired the problem or even better has a permanent solution?

Thanks

Hasse

![image](https://user-images.githubusercontent.com/104343180/165045170-70654e99-5a91-479c-b2b3-efcc68842409.png)

**Comment by Moussa4410** [comment]
I have the same issue since Thursday. I think that it's a version problem (in this case OKVIZ should launch a new one soon). Please let me know if you find something (will do the same)

**Comment by Moussa4410** [comment]
ok thanks , I do not know what to do :(

**Comment by HassePersson** [comment]
neither do I, but I will wait for a few days and see what happens before I try to find a similar "plug in" as Okviz

**Comment by HassePersson** [comment]
@Moussa4410 , the problem seems to be solved, everything works fine in my reports. Have a great day

**Comment by Moussa4410** [comment]
Yes for me too. Thanks for the follow-up and have a great day
