### ISSUE TITLE
Synoptic Panel - Using  Custom Visual in PowerBI Report Server without Internet

### ISSUE THREAD

**Issue by Jacky202107** [okviz/free-visuals#325]
I am using Synoptic Panel for reporting in PowerBI report server on premised
However, in certain area in office, we do not have internet access and only intranet, the custom visuals loaded very slow which is not desired for our users. 
We have did some troubleshooting by inspecting the web page with the browser when we load the report and seems like it requires internet to have a fast access to load the custom visual.
It looks like it keep retrying to access https://pbivisuals.powerbi.com/  several times and it took quite awhile until the custom visual to show up.  
![image](https://user-images.githubusercontent.com/92076970/170956746-df2b67e0-7bfb-450a-8ee6-7c7cd0012ac1.png)

I also did tried adding the PBI_userFavoriteResourcePackagesEnabled to environment variables and set it to 0.
https://docs.microsoft.com/en-us/power-bi/report-server/custom-visuals-troubleshoot
As the Microsoft recommended above, however this does not work for me either.
I wonder if your team or anyone knows how we can bypass or let the powerbi report server keep retrying to get into the internet [https://pbivisuals.powerbi.com:443](https://pbivisuals.powerbi.com/) to get the latest copy of the visuals?
Or is there any way that your team can suggests that we could resolved such issue?

Hope you would reply and thanks in advanced!

**Comment by Jacky202107** [comment]
@danieleperilli hope you could help if you know the solution for this, thanks!

**Comment by danieleperilli** [comment]
It's not something called by our visual, but by Power BI. Sorry, we cannot help.
