### ISSUE TITLE
OkViz - Bullet Chart v.2.2.8 - Not supporting Drill through ? 

### ISSUE THREAD

**Issue by EmilGJorgensen** [okviz/free-visuals#328]
I¨ve used the OKviz Bullet Chart (v.2.2.8) in my report and does not seem to support the drill through feature. 
I am doing something wrong or is there a work around?

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
