### ISSUE TITLE
Cards with States - Behaviour of Culture Code

### ISSUE THREAD

**Issue by danielemicera** [okviz/free-visuals#329]
I am using Cards with States v1.6.8 (also tried on v.16) and I want to use thousands separator for my measure according to the user's regional settings.
Example: 
-In Italy, the decimal separator is the comma (,) while the thousands separator is the dot (.) --> 1.234,56
-In the US, the decimal separator is the dot (.) while the thousands separator is the comma (,) --> 1,234.56
Based on this, when I release the report in Power BI Service, I want the card to update the format according to the Power BI Service settings.
This works fine with default PBI views but not with Cards with States. I found out the Culture Code option: modifying it to Italian let me use the italian format; modifying it to English (United States) let me always use the US format.
I thought that the 'Auto' setting automatically decided which format to use based on the machine settings: however, it is not the case as it always use the US (or similiar) format (comma for thousands, dot for decimals).

**Affected environment**
 - Power BI Desktop 2.105.923.0 64-bit (May 2022)
 - Power BI service

Dummy file for reproduction:
[dummy_cards.zip](https://github.com/okviz/free-visuals/files/8876870/dummy_cards.zip)

Screenshots for PBI Service (both Italian and US settings): as you can see, the standard PBI visual (the last one) changes dynamically based on the settings, the others (Cards with States) stick with the Culture Code.
![it](https://user-images.githubusercontent.com/49712519/173017776-0ea63088-b970-4843-a234-03394ed34287.PNG)

![us](https://user-images.githubusercontent.com/49712519/173017796-f25b8a89-0c5a-43a0-9b70-e9c83c13d2fd.PNG)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
