### ISSUE TITLE
Smart Filter - Label Changes from custom entry to field name

### ISSUE THREAD

**Issue by JoshSJoshS** [okviz/free-visuals#33]
After the pro update I realized that I needed to input custom labels.  No big deal, however, I don't like how they change back to the default field name after selection various filters using a Chiclet Slicer.  It also typically flashes with the default before rendering the custom text when that works.  This can be misleading to our teams.

![Filter label change](https://user-images.githubusercontent.com/53184420/61641652-796b5200-ac6d-11e9-84ea-e9b5aa999d06.png)

**Comment by danieleperilli** [comment]
Sorry, can you give us more information? Are using the Free or Pro version? This space is for free visuals. Anyway, can you provide a sample report file highlighting what is the issue?

**Comment by JoshSJoshS** [comment]
Free.  I meant that with the update splitting the features into free/pro I had to adjust the labels on the free version because you guys got ride of the other labels (see issue #24 ).  The file I have doesn't have a dataset, but rather connects to one on a server.  Not sure that will work to share.

**Comment by danieleperilli** [comment]
Ok, so the first part of the problem is solved? 
For the other part I need a sample, so please create a working mockup.

**Comment by JoshSJoshS** [comment]
Yes.  Just giving context.
I'll work on a mockup when I have some time.
