### ISSUE TITLE
Should I need to enter license key each time I drag the visual to a page?

### ISSUE THREAD

**Issue by juliaboston** [okviz/free-visuals#336]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure if this is how it is expected to behave or not, but each time I add another card with states to my report, I need to re-enter my license key. Is that to be expected?

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.106.883.0 64-bit (June 2022)

### Sample report

na

**Comment by danieleperilli** [comment]
I'm afraid yes.
