### ISSUE TITLE
Unable to add a local map

### ISSUE THREAD

**Issue by ctellal** [okviz/free-visuals#337]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Certainly after the recent updates of PowerBI, it is now impossible to add a local map in the visual. When clicking on the "local map" button, no window opens.

### Power BI

Power BI Desktop

### Power BI Version

2.105

### Sample report

Easy to reproduce

**Comment by Uki99** [comment]
I have the same bug. When can we expect the fix for this?

**Comment by audreySEPT** [comment]
Hi, I have the same issue
