### ISSUE TITLE
Support for other languages (accents)

### ISSUE THREAD

**Issue by renatcheeeenho** [okviz/free-visuals#338]
### Visual

Synoptic Panel

### The feature request

Greetings from Brazil! =) 

I'm a acoustic architect so I'm using Synoptic Panel + Illustrator to make interactives reports with my data, so Synoptic Panel its my best tool to do that. However I find some troubles with idioms. Here in Brazil we have "accents", that are kind of "symbols" that represents a tone, like "não" (no) or você (you). So when I have a column "Não atende" (does not meet the criteria) Synoptic Panel cannot link because I guess it doesn't understand the "~" above a. So, if there is any configuration that I'm missing and this app already has this support, can you please help me? If it doesn't, here's my suggestion for the future =) 

### Proposed solution

Configuration with another countries language standards

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
