### ISSUE TITLE
Bullet Chart doesn't work

### ISSUE THREAD

**Issue by smatsonamcor** [okviz/free-visuals#339]
### Visual

Bullet Chart

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Bullet Chart visual started acting unusual starting on 7/20, even on reports that were already in production and have had no recent development updates.  The color scheme of the visual changed without any developer interaction.  The Category field isn't allowing certain fields to populate any data.  We have used this field in reports for years and have not had any issues.  This is happening both in the Power BI Service and in Power BI Desktop.  It is happening in the service to reports that we have not made changes to for some time.

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

 2.107.683.0 64-bit (July 2022) but also June 2022 and May 2022

### Sample report

Our report connects to a tabular model and I can't upload an equivalent

**Comment by danieleperilli** [comment]
Issues with Bullet Chart have been moved to a dedicated repo: https://github.com/okviz/bullet-chart-issues
