### ISSUE TITLE
The Existing Bullet Visuals broke!

### ISSUE THREAD

**Issue by mshparber** [okviz/free-visuals#340]
### Visual

Candlestick

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Suddenly the visuals show only one category instead of 8 as usual.
The problem is in the horizontal format!
Also, the concatenate labels doesn't work... :(
Please fix

### Power BI

Power BI Desktop

### Power BI Version

las

### Sample report

private data
<img width="352" alt="image" src="https://user-images.githubusercontent.com/33099597/180259116-63123a57-431e-4fec-a413-c4a7938d09e3.png">

### Screenshot

<img width="352" alt="image" src="https://user-images.githubusercontent.com/33099597/180259090-f34028e1-a104-4509-b209-e5e68fa038bd.png">

**Comment by mshparber** [comment]
Now I noticed that it happens if I try to turn on the Data Labels!!!

**Comment by danieleperilli** [comment]
This is a known issue, fixed with v2.2.9.4 that will be release on July 27th.

Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
