### ISSUE TITLE
The bullet chart visual suddenly shows only one Item in Category when Copy-Paste

### ISSUE THREAD

**Issue by mshparber** [okviz/free-visuals#341]
### Visual

Candlestick

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are many bugs in the new Bullet chart visual!!!!!!!
Existing visuals are broken. Please fix !!!!
I am urgently changing to other visuals because the bullet chart is sooooo broken!!!!
Please contact me if you need more information

### Power BI

Power BI Desktop

### Power BI Version

latest

### Sample report

![image](https://user-images.githubusercontent.com/33099597/180266954-7ff0b2dc-8b9e-4092-b2ba-c31c9924110d.png)

### Screenshot

![image](https://user-images.githubusercontent.com/33099597/180266970-566d682e-5d31-4068-b7d8-df919b2f1e86.png)

**Comment by danieleperilli** [comment]
It's a known issue that will be fixed on July 27th.

Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
