### ISSUE TITLE
Bullet Chart Bug with Data Labels

### ISSUE THREAD

**Issue by dilbertospicks** [okviz/free-visuals#343]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just recently the bullet chart offered by OKVIZ began acting buggy. It will either show only the first Value added to the visual or will show completely blank. I originally thought it was our data but I changed the visual to a bar chart and it worked as expected. I have used this visual for about 2 years now with no issues and have made no changes to the data, measures or visual itself. The issue popped up out of nowhere.  

****After an hour of investigation I found the culprit!! When I turn off the data labels option, it fixes itself. But I need the data labels so this is not an option.**** I attached sample report

I am using Power Bi July 2022 version (Version: 2.107.683.0 64-bit (July 2022)) and using the following visual:

Name: Bullet Chart by OKVIZ

Publisher: OKVIZ corp.

Id: PBI_CV_9272D058_BEA0_476A_B090_A712545F92FA

Version: 2.2.9.2

![image](https://user-images.githubusercontent.com/109698613/180472863-11261c71-dd33-4c75-a8b8-a207edc64125.png)
![OKVIZ BulletChart bug](https://user-images.githubusercontent.com/109698613/180472951-61d763fc-9798-4605-8e8c-790f169ac607.jpg)

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

Version: 2.107.683.0 64-bit (July 2022)

### Steps To Reproduce

In Power Bi Desktop, I created 5 measures. Added each one to the "Values" section of the visual. And only the first value will show within Power Bi Desktop. When published to Service non of the values show, just completely blank. I figured out that if I remove the data labels option then the issue gets fixed... but I need the data labels. 
Desktop:
![OKVIZ BulletChart bug](https://user-images.githubusercontent.com/109698613/180473281-889dc088-df98-4958-9bb4-fa404059969f.jpg)

PBI Service: 
![image](https://user-images.githubusercontent.com/109698613/180473434-f8c81f09-c4d0-478d-89df-155b53b8c6ff.png)

### Sample report

[Bulletchart Data Labels BUG.zip](https://github.com/okviz/free-visuals/files/9169084/Bulletchart.Data.Labels.BUG.zip)

### Screenshot

![image](https://user-images.githubusercontent.com/109698613/180476364-d8be02d2-b4b7-4dbe-becb-85b07240bc50.png)

**Comment by danieleperilli** [comment]
It's a known issue, fixed in v2.2.9.4 that will be available July 27th.

Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.

**Comment by dilbertospicks** [comment]
My bad! I looked through the existing issues and couldn't find anything related. Thank you much!
