### ISSUE TITLE
Cards with states //Data not shown in Power BI service

### ISSUE THREAD

**Issue by Moussa4410** [okviz/free-visuals#345]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deja vue & recurring issue : Data does not show in Power Bi Service. Not fixed till this moment ? Any updates ?

### Power BI

Power BI service

### Sample report

No data shown in Power BI service (cards with states)

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
