### ISSUE TITLE
Data Labels not centered

### ISSUE THREAD

**Issue by halo1979** [okviz/free-visuals#346]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The data labels are not centered when choosing the middle position.

### Power BI

Power BI Desktop

### Power BI Version

2.108.603.0 64-bit (August 2022)

### Sample report

[Fake Factory.zip](https://github.com/okviz/free-visuals/files/9311380/Fake.Factory.zip)

### Screenshot

![Not Centered](https://user-images.githubusercontent.com/111083743/184217228-de2c1701-f3da-4cda-96a5-578a0041fe09.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
