### ISSUE TITLE
Can you send me the pbix file of this case for study? Thank you very much.

### ISSUE THREAD

**Issue by shyke2020** [okviz/free-visuals#348]
### Visual

Synoptic Panel

### The feature request

Hello! I am studying the case described in the following link. However, some details have not been fully understood. 
https://okviz.com/blog/states-in-custom-visuals/ 

Can you send me the pbix file of this case for study? Thank you very much.

### Proposed solution

Can you send me the pbix file of this case for study? Thank you very much.
My Email:shyke@163.com.

**Comment by danieleperilli** [comment]
I guess you can use the sample file available on AppSource: https://appsource.microsoft.com/it-it/product/power-bi-visuals/WA104380873?tab=Overview
