### ISSUE TITLE
Synoptic Panel - Labels alignment

### ISSUE THREAD

**Issue by acl00679** [okviz/free-visuals#35]
Labels are not aligned properly.

Is it possible to get a feature to center align the labels?

**Comment by danieleperilli** [comment]
Can you provide a screenshot? Have you tried all the alignment options?

**Comment by acl00679** [comment]
Hi Daniele,

Firstly, I thank you for contacting me on this matter.

Please find the screenshot of alignment, which is by default set to
upper-middle.

We would like to know if the labels can be center-aligned.


[image: image.png]

Your help on this will be highly appreciated.

Thanks
Sahil

**Comment by danieleperilli** [comment]
No images attached. Please attach in Github, not by replying to the notification you receive.

**Comment by acl00679** [comment]
Please find the screenshot of alignment, which is by default set to upper-middle. 

![aligment](https://user-images.githubusercontent.com/49751184/62004200-02353280-b133-11e9-95de-6f3597ad2b68.png)

![aligment](https://user-images.githubusercontent.com/49751184/62004196-fa758e00-b132-11e9-90ff-02cae6237a6e.png)

**Comment by danieleperilli** [comment]
It seems you're right. I will include a fix in our backlog. The bad news is that the new version doesn't be released before a couple of months.

**Comment by acl00679** [comment]
Not an issue. 

Thank you once again for following up quickly.

We would love to wait for the next update.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
