### ISSUE TITLE
More than 5 conditions

### ISSUE THREAD

**Issue by thetrueeagle** [okviz/free-visuals#350]
### Visual

Card with States

### The feature request

Hello, is it possible to have more than 5 conditions for the visual? I have >5 states for my measure, and it would be ideal to add all of these into one visual.

### Proposed solution

More flexibility to add more conditions if the measures used have more than 5 values.

### Additional context

![image](https://user-images.githubusercontent.com/35799489/192797384-73dd95ba-fcdc-4122-96e1-553724da5241.png)

**Comment by bisvillallai** [comment]
I solve this by adding the State field into **Category**, the ID field into **Subcategory** and a measure with the estatus ID into the **Measure** field.
Then in the format pane, you can manage all the state colors inside **Data colors**

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
