### ISSUE TITLE
Exporting to Microsoft PowerPoint as embedded image errors out

### ISSUE THREAD

**Issue by ScottKohlmorgen** [okviz/free-visuals#352]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When exporting a Synoptic Panel Panel Map to PowerPoint as a embedded image, the image is shown as an error.

REMOTE MAP ERROR
The provided image cannot be displayed for one of the following reasons: you are offline, the remote URL is not accessible, the remote URL has not the HTTPS protocol, the remote server disallows Cross-Origin resource sharing.  (CORS).

The process of exporting to a PowerPoint Live Embedded Data works.

### Power BI

Power BI service

### Power BI Version

N/A

### Steps To Reproduce

- In the Power BI Service
- Export Report with Synoptic Panel to PowerPoint -> Embed an image
- Open up downloaded report in PowerPoint
- All visuals export correctly except the Synoptic Panel Map which errors out with the following message.

REMOTE MAP ERROR
The provided image cannot be displayed for one of the following reasons: you are offline, the remote URL is not accessible, the remote URL has not the HTTPS protocol, the remote server disallows Cross-Origin resource sharing.  (CORS).

### Sample report

N/A  the error occurs in the Power BI Service not in the desktop.

### Screenshot

![Synoptic Panel PowerPoint image embed](https://user-images.githubusercontent.com/20684294/197022887-51ce33ec-f6da-4864-b2ff-9a3a94617096.png)

**Comment by riccard0russ0** [comment]
Since we are working on a **New Premium Version** of the visual, we have created a new repo dedicated to Synoptic Panel, if you are still experiencing this problem I would ask you to open a new issue here:

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
