### ISSUE TITLE
Synoptic Panel - Data Color, add ability to get color from the data [fx] button

### ISSUE THREAD

**Issue by sternman** [okviz/free-visuals#353]
### Visual

Synoptic Panel

### The feature request

In the version of the synoptic panel that I am using, under the format visual, data colors section, there is a drop down for the default color. When in saturate mode, it would be nice to be able to have the color come from the data. I have branding requirements for Power BI and with only one colour to use for this viz, it limits how I can apply the branding colors.

### Proposed solution

Its permits more flexibility with the panel. I often take advantage of the dynamic color capabilities of viz to get things to look exactly as desired.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
