### ISSUE TITLE
Select All Feature

### ISSUE THREAD

**Issue by Kraken32** [okviz/free-visuals#354]
### Visual

Smart Filter (FREE)

### The feature request

A Select All feature for each dropdown menu to select the entire list after filtering from previous dropdowns.

### Proposed solution

This is a major problem for PowerBi's default slicer as it selects all values from the slicer regardless of other slicer's filtering and whether it displays in the slicer list or not. This slicer already has so many great features, but this would really top it off!

**Comment by danieleperilli** [comment]
Not selecting any value actually means selecting all items, so you can just clear the selection.
