### ISSUE TITLE
Unable to see card when published to Power BI Report Server

### ISSUE THREAD

**Issue by garnettepereira** [okviz/free-visuals#355]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting the following error when I publish my dashboard which uses the Card with States custom visual:

To see this custom visual, add it to this report first: PBI_CV_7B952816_A48F_49B4_9E13_15E3BB2C0337
Please try again later or contact support. If you contact support, please provide these details.
Request ID1c006587-38b1-4979-f654-659afd1f2286
TimeFri Nov 11 2022 17:21:06 GMT-0500 (Eastern Standard Time)
Service version/powerbi/libs

### Power BI

Power BI service

### Power BI Version

2.109.1021.0 32-bit (September 2022)

### Sample report

![Cards with States error](https://user-images.githubusercontent.com/12835361/201439222-d4726f33-5f20-4229-9f0d-e0acfd87da89.JPG)

### Screenshot

![Cards with States error](https://user-im
![Cards with States error message](https://user-images.githubusercontent.com/12835361/201439176-aacd468d-4edc-4f1d-9a62-c98d475a7c8e.JPG)
ages.githubusercontent.com/12835361/201439169-5ee5acbc-ee53-4ff5-a2a8-0905504153ec.JPG)

**Comment by LChannon** [comment]
Hi, I am experiencing the same problem, has this issue progressed at all?
Thanks

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
