### ISSUE TITLE
Multiple Columns doesn't allow specification of Conditions

### ISSUE THREAD

**Issue by LobeTron** [okviz/free-visuals#356]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the Card with States and have three measures that I wrote in it. I want each measure to react based on its value and change colors.

However, regardless of how I specify the "If the value of" box, only the middle measure changes colors. If I try and keep the "*multiple values*", still the middle measure is the only one that changes values.

This may be user error but I've tried looking through GitHub and the internet. I am lost. Please help.

### Power BI

Power BI Desktop

### Power BI Version

2.110.1161.0 64-bit (October 2022)

### Sample report

I hope screenshots will suffice.

### Screenshot

<img width="300" alt="image" src="https://user-images.githubusercontent.com/118239390/201821524-c2cf4daa-ac7b-46bc-ad8a-0fdf09f65cc6.png">
<img width="134" alt="image" src="https://user-images.githubusercontent.com/118239390/201821577-4fce4c33-9bd4-4a28-883d-ec0d1240d0bc.png">
<img width="133" alt="image" src="https://user-images.githubusercontent.com/118239390/201821607-a8fc1813-28b6-4a47-8293-c58d3ba23dba.png">

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
