### ISSUE TITLE
Static Y-axis in the candlestick chart ?

### ISSUE THREAD

**Issue by marcl11** [okviz/free-visuals#357]
### Visual

Candlestick

### The feature request

Hi,

in the candlestick chart, if many data are passed, we need to scroll on the left to see the values of the Y-axis whereas usually the important data are on the right. Would it be possible to get an Y-axis always visible?

thx in advance

### Proposed solution

Having the values of the Y-axis would be great because it would avoid constantly to shift the left-right lift to see the interesting candles and the values of the grid Y-axis at the same time :-)
![2022-11-16_16-12-15](https://user-images.githubusercontent.com/112061285/202219719-4b45503e-6d7b-4982-a71d-7f3aac16e43d.jpg)

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry.
