### ISSUE TITLE
Smart Filter box height expands even when in compressed mode

### ISSUE THREAD

**Issue by rachaelclee** [okviz/free-visuals#359]
### Visual

Smart Filter (FREE)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting an item from drop down menu, it changes the height of the white box which is not visually appealing. I am using compressed mode but that only works when I click 2+ options in the drop down. 

### Power BI

Power BI Desktop

### Power BI Version

2.111.590.0 

### Steps To Reproduce

1. Click drop drown menu
2. Select item
3. Text field becomes larger and expands height. Does not compress. (compressed mode is on)
4. Select another option and the box goes back to normal

If the option is less than 5 characters, it doesnt change and looks good. 
I do understand and I can increase the width but that takes up so much space for even small words. 

### Sample report

[Smart Filter Issue.zip](https://github.com/okviz/free-visuals/files/10177996/Smart.Filter.Issue.zip)

### Screenshot

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/63001923/206236591-28e31276-81a5-4e4f-a0bd-cb2c5f1a8949.png">

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/63001923/206235305-3f07d239-21f5-4616-bd9c-f7dab9c94ce0.png">

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/63001923/206236501-12a009cd-1e16-4a6d-95a8-708f26e49fcd.png">

**Comment by coderEm** [comment]
+1 
Having exact same issue.

**Comment by danieleperilli** [comment]
Just enlarge the input box. There is a minimum space required to allow users to insert text.
The Pro version includes a Max item width option to avoid this.

**Comment by rachaelclee** [comment]
It waste so much space though just wish it compressed it. Thank you for your time though!


Rachael Lee
  |  Application Specialist II
2200 N Main St., Normal IL 61761
HQ (309) 451-3999 | Direct (309) 451-4437
Cell (309) 202-1223
www.roomready.com
This email may contain information that is confidential and may constitute inside information. The contents of this email are intended only for the recipient(s) listed above. If you are not the intended recipient, you are directed not to read, disclose, distribute or otherwise use this transmission. If you have received this email in error, please notify the sender immediately and delete the transmission. Delivery of this message is not intended to waive any applicable privileges.
