### ISSUE TITLE
Smart Filter - Still not filtering on whole numbers

### ISSUE THREAD

**Issue by cmcubism** [okviz/free-visuals#36]
Hi there,
I have had the smart filter bug a while ago andd updated to the newest Power BI Desktop version (24.07.2019) and the newest Smart Filter Free version via Marketplace (1.2.3) today. But I am still not able to filter on whole numbers in my reports.

Could you please check?

Kind regards
Christian

**Comment by danieleperilli** [comment]
https://github.com/okviz/free-visuals/issues/31
