### ISSUE TITLE
Sparkline - add automatic or manual horizontal scaling option to account for scroll bar

### ISSUE THREAD

**Issue by mcleanle** [okviz/free-visuals#360]
### Visual

Sparkline

### The feature request

For sparkline visuals with many categories, a vertical scroll bar may be needed. The scrollbar overlaps the rightmost point on the line. This looks messy and can interfere with interpreting the data since the endpoint of the trend is difficult to see.
![Capture2](https://user-images.githubusercontent.com/31260248/207699542-8c6cfc78-de63-415e-9d85-63d79fe1d75f.JPG)

### Proposed solution

Either automatically scale the viz to account for a scrollbar when one is present, or add an option for the user to increase padding manually.

**Comment by danieleperilli** [comment]
Unfortunately, we have no plans to add this feature in the near future, sorry. I will reopen this issue if we change our plans.
