### ISSUE TITLE
Synoptic Panel Crashes Power BI when Data labels enabled

### ISSUE THREAD

**Issue by JohnW3NZ** [okviz/free-visuals#361]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm seeing an issue with the Synoptic Panel where it just crashes Power BI any time I enable the show Data Labels for the graphic.

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.112.603.0 64-bit

### Sample report

will send sample report

**Comment by Darren-McMonigal** [comment]
i can also confirm that this issue exists.

**Comment by ferarroyohernandez** [comment]
Any updates on this?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
