### ISSUE TITLE
Synoptic Panel State colours not applied for >= or > comparison options

### ISSUE THREAD

**Issue by JohnW3NZ** [okviz/free-visuals#362]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set up a graphic to show injuries on a body. I selected the comparison for the state to be >= to change the colour of the body part based on the number of injuries. This filter seems to work on all other comparisons other than the >= & > options

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.112.603.0 64-bit

### Steps To Reproduce

Add visual
Map to body parts
Select Comparison option of > or >= to
Change comparison colours at steps to various colours

### Sample report

one can be set.

### Screenshot

![image](https://user-images.githubusercontent.com/121408642/209485322-cb153b18-c766-4690-be8e-2f247e43a72e.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
