### ISSUE TITLE
Expand All Levels Down One Level Not Working With Date Hierarchy

### ISSUE THREAD

**Issue by sebtaylorbida** [okviz/free-visuals#363]
### Visual

Candlestick

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the candlestick visual.
I have a date hierarchy of Year, Quarter, Month & Date on the Axis.
After populating the rest of the fields, I am having trouble using the "expand all down one level in the hierarchy".

Instead of seeing each year and it's respective quarters broken down, I see an aggregated view of all Q1s, all Q2s etc.

FYI:
My price data is on a daily granularity. I realize that the visual does not by default create an aggregated measure of open, close, low and high on anything other than a daily level (I have dealt with that separately with a simple measure for each). For now I'm just hoping I can get the expand all dates to expand correctly.

### Power BI

Power BI Desktop

### Power BI Version

Dec 2022

### Steps To Reproduce

The easiest way to replicate this behaviour is to simply use default date hierarchy on the axis, and then add the open prices.

"Expand all down one level" now does not produce the intended result.

### Sample report

![image](https://user-images.githubusercontent.com/81657369/213165721-b0ba3ee9-ed37-4ebb-9bf9-3684f126b8bd.png)

**Comment by sebtaylorbida** [comment]
To get an aggregated view of Open for example at a yearly view. You simply have to create a measure to find the Open price on the first available date in that year. That part is reasonably easy. But the candlestick seems to display each year separately, within the same quarter.

**Comment by danieleperilli** [comment]
Please provide a sample report.
