### ISSUE TITLE
Smart Filter PRO: Issue with the DropDown Viz for more fields

### ISSUE THREAD

**Issue by psraman3** [okviz/free-visuals#364]
### Visual

Smart Filter (FREE)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently we are encountering issues in the DropDown Mode viz, when using more than 6 Fields. Upon increasing the fields to more than 6, we notice that the filter under a specific dropdown is not loading up all the sub-categories. For e.g, when there are 10 sub-categories under “Department” field, upon loading more than 6 fields (in which “Department” is one of them), then we will not see all 10 sub-categories (instead we will see only 6 or 7 sub-categories). Is there a numerical restriction on the number of Fields that can we use in one Smart Filter PRO DropDown viz mode?
   Kindly help with this. I really appreciate any help you can provide.

### Power BI

Power BI Desktop

### Power BI Version

2.98.1025.0

### Sample report

...

**Comment by danieleperilli** [comment]
Each field added increases the number of rows.
Smart Filter Free is limited to 30,000 rows. Smart Filter Pro can load more data incrementally, although it is not recommended to load too many data points because it slows down the entire report.
