### ISSUE TITLE
Thousand separator missing with SSAS live connection and PBI (Desktop) Report Server

### ISSUE THREAD

**Issue by Markoff79** [okviz/free-visuals#365]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Versions we use…
SSAS-Server: 15.0.35.0
SSAS Compatibility Level: 1500
Power BI (Desktop for) Report Server: 2.112.1421.0 64-bit (Januar 2023)
card with states: 1.6.7

Problem is as follows…
We use a live connection to an SSAS (tabular) database with a measure with the format string „#,##0“ (with thousands separator):
 
With the standard visuals this works fine. Unfortunately this measure is displayed without thousands separator in the „card with states“:
 
This behavior is also the same after saving the pbi report to the PBI report server (so not only in the desktop version but also in the web interface of the report server).
Can you help us with this? We couldn’t find a settings, where we could activate the thousands separator in the formatting options in the card with states…
Strange is that when we create a local measure in the pbix with a simple reference to the measure from the live connected SSAS-DB and format this measure with a thousand separator, it seems to work (so it is only an issue with the live connected measure from SSAS-DB?!!):
 
Strange is also that in this case the locale / culture code  is also differently derived than in other visuals: the normal column chart uses a german locale with „.“ as thousands separator while the card with states uses „,“ as thousands separator (although in the card with states „Culture Code = Auto“ is set). „Culture Code = Auto“ seems to have a different behavior than other culture code derivations in normal visuals… This can be change by settings the culture code manually to de-DE. We only mention it here because we find this behavior also a little bit strange…

For screenshots see attached dcoument:
[ProblemDescription.docx](https://github.com/okviz/free-visuals/files/10704662/ProblemDescription.docx)

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

2.112.1421.0 64-bit (Januar 2023)

### Steps To Reproduce

See problem description...

### Sample report

not possible due to live connection

### Screenshot

See problem description...

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
