### ISSUE TITLE
Export issue on Synoptic designer tool 

### ISSUE THREAD

**Issue by gabrielmabelly** [okviz/free-visuals#367]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to export the work I've done using synoptic designer tool it leads me to a blank page

### Power BI

Power BI Desktop

### Power BI Version

N.A

### Steps To Reproduce

- Import an image of your choice on the tool
- Draw zones
- Try to export the image to be used in PowerBI 
- Fails

I tried on 2 different computers and browers, also tried on phone and didn't work too.

### Sample report

[content.txt](https://github.com/okviz/free-visuals/files/10723856/content.txt)

### Screenshot

![image](https://user-images.githubusercontent.com/78576149/218505108-fa475073-2a80-4774-bd52-f34afc0a0287.png)
![image](https://user-images.githubusercontent.com/78576149/218505305-e33f998a-c8a9-4863-b525-9367881108f5.png)

**Comment by gabrielmabelly** [comment]
Don't click on the image to open it, just right click and save as (as written by okviz...).

**Comment by CandiiiiceGe** [comment]
Hi I met the same issue and if I right click and save as, there is only html file saved locally. Please support.
![Uploading Snipaste_2023-11-07_14-57-18.png…]()
![image](https://github.com/okviz/free-visuals/assets/130436388/fbdda89b-ccf6-46d3-a789-442ca0f24c67)
