### ISSUE TITLE
Blank Synoptic Panel on Power BI Online

### ISSUE THREAD

**Issue by chbgiorgenon** [okviz/free-visuals#368]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a report published on Power BI online (pro account) that was working fine with a Synoptic Panel visualization. It stopped showing that visual on Power BI Online, but I can still see that visual perfectly on Power BI Desktop and on the automatically emails being sent by the Subscribe option. On Power BI Online the map don't load but any other attributes like visualization tittle appear... Any idea on what could be happening? Thanks!

### Power BI

Power BI service

### Power BI Version

2.112.1161.0 64-bit 

### Steps To Reproduce

1. Create the visualization on Power BI Desktop
2. Assign attributes only on Category (text) and Measure (sum of value)
3. Publish to an environment on Power BI Service (Online)
4. Open the dashboard on Power BI Service
5. The visual will be blank...

### Sample report

The data is internal...

### Screenshot

![Capture_Desktop](https://user-images.githubusercontent.com/125393400/218814515-c5bcfad1-bd83-4c5d-99ab-e53f12268de8.JPG)
![Capture_Online](https://user-images.githubusercontent.com/125393400/218814552-6a16789d-89d9-4a16-9edd-7fa539675706.JPG)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
