### ISSUE TITLE
No dynamic map update

### ISSUE THREAD

**Issue by al386** [okviz/free-visuals#369]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, on the documentation is explained that it's available the dynamic selection of maps adding a measure in the map fields, however in the current version of the visual we can't add measure on that field therefore we have static map selection. Please, could you provide a solution about that. thanks

### Power BI

Power BI Desktop

### Power BI Version

2.114.664.0 64-bit 

### Steps To Reproduce

Add image to a folder,
Load binary content of the image
Create a measure top select the right image based on a filter
Not allowed to add the measure in the maps field of the component.

### Sample report

[test_synoptic.zip](https://github.com/okviz/free-visuals/files/10806289/test_synoptic.zip)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
