### ISSUE TITLE
Synoptic Panel - ToolTips not showing up

### ISSUE THREAD

**Issue by BTSSCarol** [okviz/free-visuals#37]
I am using the same data trying two different visuals for end users. They prefer the first visual but I cannot see the Tooltips like I can in the second visual. If I put word wrap on I can see that they have been mapped to the data. Wondering what I am doing incorrectly? I have checked all the settings many times. 

![image](https://user-images.githubusercontent.com/26610921/62056657-81d70600-b1f4-11e9-8f87-abd59866ec82.png)

![image](https://user-images.githubusercontent.com/26610921/62056784-ba76df80-b1f4-11e9-9f74-58afa1377dbe.png)

**Comment by danieleperilli** [comment]
Please, provide a sample report.

**Comment by BTSSCarol** [comment]
Is there an email address I can send it to? Would rather not post clients data here.. LOL

**Comment by danieleperilli** [comment]
Of course: support@okviz.com

**Comment by BTSSCarol** [comment]
Just sent it... THANKS for the fast response. I have been banging my head all morning.

**Comment by danieleperilli** [comment]
I see 0x0 areas in the map. I suggest you to use Synoptic Designer with high-resolution images or vectors, otherwise you can't obtain anything usable...
<img width="1147" alt="Season_Seating_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/62058424-b9a87280-b221-11e9-86b1-2552afda9ebd.png">

**Comment by BTSSCarol** [comment]
Ok, will retry with better graphic.It looked like the area had mapped in the synoptic designer and when i put the labels on it shows up.

**Comment by danieleperilli** [comment]
Yes, but the mouse has not enough room to trigger the on-hover event and to show the tooltips. I close the issue for the moment. Feel free to re-open if you need it.

**Comment by BTSSCarol** [comment]
Oh....THANKS.. Daniel!! That explains it.. I will get better graphics.
