### ISSUE TITLE
Card with States - show as percentage

### ISSUE THREAD

**Issue by summerforvis** [okviz/free-visuals#370]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I need to show my value as a percentage WITH a trendline.

It appears that the only way I can figure out how to show my value as a percentage is by using a FORMAT text measure, but this renders the trendline useless.

### Power BI

Power BI Desktop

### Power BI Version

2.115.663.0 64-bit (March 2023)

### Sample report

This appears to be common issue, I am simply dropping a percentage measure into the Measures (?) field, and the date field into the Trendline axis (?) field.

**Comment by samusaran** [comment]
I have this issue too. Can't use Card with States because any formatting is broken. Even for Whole Numbers, if I want to have thousand separators, the visual simply ignores the formatting.

I think the issue impacts more that simply percentages.

**Comment by danieleperilli** [comment]
Closed since missing report file.

**Comment by danieleperilli** [comment]
@samusaran we are not able to fix issues without repro files, as specified in the "Submit Issue" form. It's our policy to close any issue without a repro file within 14 days.
