### ISSUE TITLE
Candlestick Visual - Conditional Formatting

### ISSUE THREAD

**Issue by rohit08491** [okviz/free-visuals#374]
### Visual

Candlestick

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team

We're using Candlestick visual (https://okviz.com/candlestick/) provided in the Marketplace. It works fine with input for Open, Close, High, and Low parameters in the candlestick. 

We need the capability to change the colour of the candles or have marker circles on the candles with color based on the 5th parameter value i.e. conditional formatting using another rating field. At the moment, we can only select a static colour for the candles as highlighted in the below screenshot on the right side.

Could you please confirm if this functionality is possible for the candlestick visual? If yes then please steps to achieve the same or any other solution you can think of?

Thanks in advance for your time and help 🙂

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

Latest Version

### Steps To Reproduce

Steps are just to add Candlestick along with required parameters and then try to see if any option for conditional formatting the 'Bullish' and 'Bearish' color

### Sample report

[Sample File.zip](https://github.com/okviz/free-visuals/files/11581637/Sample.File.zip)

### Screenshot

<img width="1703" alt="image" src="https://github.com/okviz/free-visuals/assets/134778988/daf6b6bf-0c2c-4402-b071-a5ec1f27581a">

**Comment by danieleperilli** [comment]
No, unfortunately it's not supported and we don't plan to support it in the near future.
