### ISSUE TITLE
Text in tooltips, how to change it?

### ISSUE THREAD

**Issue by mjp190** [okviz/free-visuals#375]
### Visual

Synoptic Panel

### The feature request

Synoptic shows when I add a map to PowerBI eg. in area tooltips "Area:  xxxxxx " oder "Subcategory: xxxx " Quantity.....
Where can I change such texts eg. into German. Is that possible by txt editor anywhere in a specific file?

### Proposed solution

We add German data, states, zipcodes and tooltips should also show german labels then.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. 
The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
