### ISSUE TITLE
Synoptic Panel - transparent area

### ISSUE THREAD

**Issue by CRaDeRa** [okviz/free-visuals#376]
### Visual

Synoptic Panel

### The feature request

It would be very beneficial if the selected area in the synoptic panel could be fully transparent. I want the user to hover over graphics to get information, and as the area in the panel has to have a color this ruins the look and feel. I`ve also tried to use the hex code for transparency with no luck.

### Proposed solution

Open the possibility for the color of the area with data to be fully transparent

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)

**Comment by JediBrooker** [comment]
It's definitely been a few months. I desperately need this feature to have transparent colours. Any chance of an ETA?
