### ISSUE TITLE
Synoptic panel how see level of svg in powerbi 

### ISSUE THREAD

**Issue by fanchmat974** [okviz/free-visuals#377]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello. first please sorry for my engish,

i have an issue with synoptic panel, 
i want to manage my warehouse in power bi .  i have a racking plan witch work perfectly for the first level but i'm not abble to see the second and the 3rd level . i woul like to have a color per level but i don't know how to achieve this.
- I'll try to import 3 svg racking plan, it works but i can't differentiate them 
- i'll try to affect the same storage placement with level but it don't works 

the only way i find is create 3 sheet in power bi but it's not very usefull

is there a way to do this?

thank you for you're response 

Francois
 from réunion island / indian ocean

### Power BI

Power BI Desktop

### Power BI Version

RS

### Sample report

[testRack.zip](https://github.com/okviz/free-visuals/files/12142047/testRack.zip)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
