### ISSUE TITLE
Card with States Issue Publishing Online

### ISSUE THREAD

**Issue by miccckkkkeeyyyyy** [okviz/free-visuals#378]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I previously had reports which utilised the Card with States visualisations.
Last week we noticed that now online this visual will only load properly once on a page and any additional Card with States visuals show blank.

I went to the OK Viz website and noted that there is now an Unlock Premium Features For Free (not sure if this was always there), but I wondered if that was the issue, so I signed up and received the licence key and went and changed all the visuals to premium and put in the licence key.
But when I publish online, the old problem still occurs where the visual works once on a page and then is blank for the rest. Note that it looks OK on my desktop version.

I reached out to info@okviz.com, who issued me new credentials which I tried but this still did not fix the issue. They have now suggested I post here. Any assistance would be appreciated.

### Power BI

Power BI service

### Power BI Version

2.119.986.0

### Sample report

[OKViz Example.zip](https://github.com/okviz/free-visuals/files/12423917/OKViz.Example.zip)

### Screenshot

![Desktop](https://github.com/okviz/free-visuals/assets/143042935/0bb3e736-90b5-440a-ad81-148dc448bef3)
![Online Service](https://github.com/okviz/free-visuals/assets/143042935/1a9103f6-5e2a-46e9-957c-0fc088d40185)

### Anything else?

•	For the online version of the report, if I go into focus mode and then back out the visual now appears

**Comment by marcosqlbi** [comment]
You should scale this issue to Microsoft, as we did not change anything in the visual and it seems a regression of the host environment. I forwarded this to Microsoft but only if you open a ticket with Microsoft support this could escalate.

**Comment by marcosqlbi** [comment]
@miccckkkkeeyyyyy did you open the ticket with Microsoft? Do you have any update?

**Comment by miccckkkkeeyyyyy** [comment]
Hi @marcosqlbi. I raised the [following ](https://community.fabric.microsoft.com/t5/Service/Card-with-States-Issue-Publishing-Online/m-p/3401194)on the Power BI forum with no response (unsure if this is different from raising a ticket). But I have been too pressed for time, so have I have just ended up using another visual instead,
