### ISSUE TITLE
Synoptic Panel- on mouse click question

### ISSUE THREAD

**Issue by BTSSCarol** [okviz/free-visuals#38]
Is it possible "on mouse click" to trigger a workflow in CRM or a plugin or perhaps some javascript? I understand "on hover" we get the Tooltips, so I was wondering about making something happen.

**Comment by danieleperilli** [comment]
No sorry, the click event can only perform a data selection - it filters other charts on the report.

**Comment by BTSSCarol** [comment]
ok thanks. Would be soooo cool to be able to do something other than filters.
