### ISSUE TITLE
Synoptic Panel does not honor Line Feed or Carriage Return in value

### ISSUE THREAD

**Issue by DeniseTucker-eaton** [okviz/free-visuals#380]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We really like the Synoptic Panel and would like to see some improvements in it.  Our company would be willing to pay for this tool.  

We have added both line feed and carriage return but cannot get our string content to add lines between the pieces of data in the display.  (Note the tooltip shows the existence of these characters.)

The only way we could even get it to wrap once was to turn on the Display as "Column and value" or "Area and value", which we do _not_ want to have turned on.  We just want to display the value and have it honor the line feeds and carriage returns in that string in the display.

We will deploy this in the PBI Service, too once this works.

![2023-08-28_13-58-22](https://github.com/okviz/free-visuals/assets/76052764/2ef42e71-ce9b-45c6-96a9-d40e50fd6f3d)

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.114.864.0 64-bit (February 2023) / Version: 2.118.828.0 64-bit (June 2023)

### Steps To Reproduce

1. PBI Desktop (Version: 2.114.864.0 64-bit (February 2023)) or Version: 2.118.828.0 64-bit (June 2023)
2. Value is a string that contains line feed and carriage return between 3 pieces of data. (The idea is to have 4 pieces of data on 4 different lines in the display
3. na
4. No error occurs.  It just does not display the data the way we would like.
[Word Wrap Example (1).zip](https://github.com/okviz/free-visuals/files/12457877/Word.Wrap.Example.1.zip)

### Sample report

[Word Wrap Example (1).zip](https://github.com/okviz/free-visuals/files/12457889/Word.Wrap.Example.1.zip)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
