### ISSUE TITLE
multiple comparisons for single measure

### ISSUE THREAD

**Issue by aleksey-vershinin** [okviz/free-visuals#381]
### Visual

Card with States

### The feature request

Hi! Would it be possible to have multiple comparisons available for a single main measure? ex. "last year" and "plan"

### Proposed solution

by giving an "at a glance" understanding of main measure development in different contexts without the need to switch the comparison

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
