### ISSUE TITLE
Add Drill through options to Card with States

### ISSUE THREAD

**Issue by JTumino** [okviz/free-visuals#382]
### Visual

Card with States

### The feature request

Hi, the Cards with States works amazing for me, it would be very useful if the multiple card layout could act as individual buttons, so that I could use the Drill Through feature. Is that already possible and I missed it?  

### Proposed solution

The formatting of Cards with States is incredible, adding this feature would make any Power BI more dynamic for its users.

**Comment by danieleperilli** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
