### ISSUE TITLE
Card with State Drilldown not showing

### ISSUE THREAD

**Issue by StephanJenner-KITT** [okviz/free-visuals#383]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set a drilldown Page that references the measure in the Card State but I dont see the drill down option I have tested this in a original PowerBi Card and the drillthrough option shows so it works

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.121.782.0 64-bit (September 2023)

### Steps To Reproduce

1. Added a Card with States
2. Added a Count ID
3. Set Up Filters
4. On the Detail Page visual added any Summarise of ID

### Sample report

[DrillthroughTest.zip](https://github.com/okviz/free-visuals/files/12707694/DrillthroughTest.zip)

**Comment by danieleperilli** [comment]
Duplicate #382
