### ISSUE TITLE
Error Synoptic Panel

### ISSUE THREAD

**Issue by josue-eusoj** [okviz/free-visuals#384]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Synoptic panel visual is no longer working on the Power Bi Report Server platform. I believe that Power Bi updated the platform and the visual needs an update so it can work. I have always used Synoptic for BI Reports and unfortunately I am no longer able to do so. I kindly ask that you please carry out this update so that we can continue to use your look. This problem doesn't just happen to me, as you can see in the links below.

### Power BI

Power BI service

### Power BI Version

Setembro de 2023

### Steps To Reproduce

When uploading any panel with a Synoptic by Panel visual on the Power BI Report Server platform, the visual is not displayed... It is blank without displaying the image or features. Needing to update along with the platform update.

### Sample report

[Syno.zip](https://github.com/okviz/free-visuals/files/12820077/Syno.zip)

### Screenshot

![Error](https://github.com/okviz/free-visuals/assets/147077982/d1e332de-6cc8-42c3-82d2-610435552a91)
![OK](https://github.com/okviz/free-visuals/assets/147077982/999a63c3-254f-4a66-bac4-2bd8086aa498)

**Comment by danieleperilli** [comment]
Hi @josue-eusoj, since it sounds like an error in the version of Power BI server you are using (not directly related to our code), we have asked Microsoft to investigate. It may be necessary to open a ticket with them. I will update you when we receive a response.

**Comment by danieleperilli** [comment]
Moved to the correct repo: https://github.com/okviz/synoptic-panel-issues/issues/3
