### ISSUE TITLE
Data labels causes PBI to freeze

### ISSUE THREAD

**Issue by carlblunck** [okviz/free-visuals#385]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When toggling the data label to on, PBI will freeze and it can only be closed by ending the task

### Power BI

Power BI Desktop

### Power BI Version

2.121.942.0 64-bit (September 2023)

### Steps To Reproduce

![Capture](https://github.com/okviz/free-visuals/assets/147794201/69613dd1-f9b3-4b5f-b523-40984ccee715)

### Sample report

[WHS-SampleError.zip](https://github.com/okviz/free-visuals/files/12889962/WHS-SampleError.zip)

**Comment by danieleperilli** [comment]
We are actively working on a **new premium version of the visual**, slated for release in the coming months. This new version aims to address various bugs (including the one you reported) and integrate new functionalities that would enhance the user experience significantly.

**Unfortunately, the current free version will not receive updates in the near future, except for security issues.**
