### ISSUE TITLE
Bullet Chart - Tooltips have no formatting if Calculation Group Format String Expression is used

### ISSUE THREAD

**Issue by muhammad-s-zainal** [okviz/free-visuals#388]
### Visual

Bullet Chart

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If Format Strings in Calculation Groups are created, hovering over a bullet chart displays a tooltip that is not formatted. This occurs even when the Calculation Group is not used in the visual.

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

2.123.684.0 64-bit (November 2023)

### Steps To Reproduce

1. Create a bullet chart and include a measure with a Currency formatting.
2. Navigate to External tools and open Tabular Editor.
3. Create a Calculation Group and create a Calculation Item where Expression is **SELECTEDMEASURE()** and Format String Expression is **"$#0.00"**
4. The moment this Calculation Item is created, the bullet chart tooltip will display figures which are not formatted.

### Sample report

[Okviz Bullet Chart Tooltip Issue.zip](https://github.com/okviz/free-visuals/files/13434008/Okviz.Bullet.Chart.Tooltip.Issue.zip)

### Screenshot

Before creating Calculation Item:
![image](https://github.com/okviz/free-visuals/assets/43106089/5004eca7-2d34-4d97-806e-58cf1d0f129f)

After creating Calculation Item:
![image](https://github.com/okviz/free-visuals/assets/43106089/7f214354-1f33-4927-a56e-76a4d79db6e5)

**Comment by danieleperilli** [comment]
The bug has been already fixed and a new version sent to Microsoft. I will be released in a couple of weeks. 
I'm closing the issue since this is not the repo for Bullet Chart. Please use https://github.com/okviz/bullet-chart-issues/issues
