### ISSUE TITLE
Key Licence problem Card with States

### ISSUE THREAD

**Issue by Kira3198** [okviz/free-visuals#389]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hello, I am contacting you because I obtained a license key for Card with States but when I paste it into PowerBI in the "license" box it does not work, I restarted PowerBi but it still does not work.
What to do please?
Sincerely,
THANKS,

### Power BI

Power BI Desktop

### Power BI Version

Version : 2.112.1421.0 64-bit (janvier 2023)

### Sample report

[test carte dynamique.zip](https://github.com/okviz/free-visuals/files/13778983/test.carte.dynam
[test carte dynamique.zip](https://github.com/okviz/free-visuals/files/13778986/test.carte.dynamique.zip)
ique.zip)

### Screenshot

![image](https://github.com/okviz/free-visuals/assets/154990801/34fdd4ad-66a9-471f-a9f2-ea946c4a2fda)

**Comment by danieleperilli** [comment]
Hi dwfgxw xwcbv,
I just resent you an updated license code.
