### ISSUE TITLE
Synoptic Panel - Saturation doesn't work if States are disabled

### ISSUE THREAD

**Issue by danieleperilli** [okviz/free-visuals#39]
Verified. If you disable States the Saturation is disabled. Workaround: leave States enabled. To fix in the next version.
<img width="987" alt="Development_-_Synoptic_Panel_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/62112503-1dc74700-b2b3-11e9-8c13-3088b103f2af.png">

**Comment by DavidRPitts** [comment]
Is this resolved?

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
