### ISSUE TITLE
Card with States - Cards Collapse with Null

### ISSUE THREAD

**Issue by cassidyks20** [okviz/free-visuals#392]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a row of Cards has a card where the value is NULL, the card collapses and all cards after it shift to the left.  The expected result is for the card to stay intact and show the NULL / Blank.  Please provide direction on how to solve this, thanks!

### Power BI

Power BI Desktop, Power BI service, Power BI iOS app

### Sample report

[SampleOKVIZ.zip](https://github.com/user-attachments/files/16146974/SampleOKVIZ.zip)

### Screenshot

![image](https://github.com/okviz/free-visuals/assets/139180446/8b6d12e1-0b67-4f75-8c32-d21000b861a6)

**Comment by danieleperilli** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.

**Comment by cassidyks20** [comment]
Thanks for the response. That’s a bummer, Cards with States is still far superior. I’ve tried to replicate my setup with the built in visual but it’s not quite there. Hopefully one day. Sent from my iPhoneOn Jul 26, 2024, at 9:56 PM, Daniele Perilli ***@***.***> wrote:﻿
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.

**Comment by danieleperilli** [comment]
I know, but since they are investing in that direction, it will improve at some point, so it is better for us to put our resources on other projects.
