### ISSUE TITLE
Card with States No Longer Functioning!

### ISSUE THREAD

**Issue by CalebJsN** [okviz/free-visuals#393]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had about 75-80 cards in a multi-page report that worked fine. Upon opening the pbi file today, all cards are blank. The formatting tab on all cards are blank. The "Build visual" fields show when first creating a card, but disappear returning to it again. Dragging columns or measures into the value fields after creating a new one doesn't take. Opening a fresh file and downloading the visual yields the same results.

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.131.1126.0 64-bit (July 2024)

### Steps To Reproduce

Happens with fresh, blank file.

### Sample report

Github will not take the sample pbix file. Will email the support email with a copy.

### Screenshot

![CardNoBuild](https://github.com/user-attachments/assets/3d928e0f-a52c-48c4-9d7a-2245f951fe76)
![CardNoFormat](https://github.com/user-attachments/assets/400a23d2-a8c0-4d3a-8cb3-c2d77739c506)

**Comment by danieleperilli** [comment]
I think it's a general problem of Power BI with custom visuals, since other users reported the same with other visual. Please report it to Microsoft.
