### ISSUE TITLE
New Synoptic visual not working in Power Bi

### ISSUE THREAD

**Issue by SEdmonston970** [okviz/free-visuals#395]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2024-08-02 Synoptic](https://github.com/user-attachments/assets/dd591551-4e77-487b-944c-b5fd5ed0ecaa)
![Screenshot 2024-08-02 Synoptic 2](https://github.com/user-attachments/assets/d019c776-cc1e-4720-82e0-b43c8fc0ec58)
The first file shows the original file I created that works in Power Bi
The second file shows the same file created today that does not work in Power Bi 
I am new to Synoptic Designer so please excuse my lack of knowledge  

### Power BI

Power BI Desktop

### Power BI Version

2.131.1203.0

### Sample report

[ROOF WO TRACKING By BLDGzip.zip](https://github.com/user-attachments/files/16469754/ROOF.WO.TRACKING.By.BLDGzip.zip)

### Screenshot

![Screenshot 2024-08-02 Synoptic](https://github.com/user-attachments/assets/5eb96173-7bd6-4c08-aae6-73e8e06d3d0d)
![Screenshot 2024-08-02 Synoptic 2](https://github.com/user-attachments/assets/c47a6fd5-5f8a-417f-9335-30324741821d)

**Comment by danieleperilli** [comment]
The current version of synoptic panel is not able to work with nested areas. The next version (that will planned to release by the end of September) is able to work with your file.
![screen2024-08-03-000618](https://github.com/user-attachments/assets/a6db1ee3-83b4-4e31-99ff-830425e0121a)

**Comment by SEdmonston970** [comment]
Thank you so much

                            Stephen Edmonston
             Facilities / UTILITIES Engineering INNOVATION
                                      407-224-8362
                                      [31-universal-blog]

“Learning and innovation go hand in hand. The arrogance of success
is to think that what you did yesterday will be sufficient for tomorrow.” –William Pollard

From: Daniele Perilli ***@***.***>
Sent: Saturday, August 3, 2024 2:43 AM
To: okviz/free-visuals ***@***.***>
Cc: Edmonston, Stephen (UDX) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [okviz/free-visuals] New Synoptic visual not working in Power Bi (Issue #395)


The current version of synoptic panel is not able to work with nested areas. The next version (that will planned to release by the end of September) is able to work with your file.
screen2024-08-03-000618.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/a6db1ee3-83b4-4e31-99ff-830425e0121a__;!!PIZeeW5wscynRQ!vr5Ls_Qr_P-jWlAH7wUfTMDMSsSbKdgDGLBpzdABXJ_gHbQ4Eo4x33ux3HXOUJ0oqF9o7I8xgH0ZfrLHKXZkTuhfHB_spCStkGCS_w$>
