### ISSUE TITLE
Can the Card with States visual drill through? If so, I'm unable to drill through.

### ISSUE THREAD

**Issue by janet-erdman** [okviz/free-visuals#396]
### Visual

Card with States

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

General Question right now. New to GitHub so I'm not sure how things work here.

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.131.1203.0 64-bit (July 2024)

### Sample report

N/A

### Screenshot

N/A

### Anything else?

N/A

**Comment by danieleperilli** [comment]
No, it's not supported.
