### ISSUE TITLE
Card with States Titles Not Displaying in Power BI

### ISSUE THREAD

**Issue by BrettP76** [okviz/free-visuals#4]
At some point in the past 24 hours the titles for the Card with States custom visual have stopped displaying in reports in the Power BI service. The number and colors appear, the titles do not. 

Did a new change in the Power BI service cause this visual to break?

Can someone advise on whether a fix will be made available soon?

**Comment by okviz** [comment]
Unfortunately, it is something we are not aware of. It should be caused by to the Power BI service. Probably the best thing to do is opening a ticket with Microsoft support.
