### ISSUE TITLE
Card with States - Hide Data Label Value

### ISSUE THREAD

**Issue by milbeck** [okviz/free-visuals#40]
As a Power Bi User (with Card with States installed)
I would like to hide the Data Label
So that I can use your visual to show different colored states along with Messages, but not show the Data Label value.

![1](https://user-images.githubusercontent.com/53492814/62157848-136d7300-b2dc-11e9-98e8-6c69ada69075.JPG)
![2](https://user-images.githubusercontent.com/53492814/62157849-136d7300-b2dc-11e9-9a82-b1760f51294a.JPG)

**Comment by danieleperilli** [comment]
This feature has been added to the version 1.5.4, currently under review by Microsoft.
