### ISSUE TITLE
Bullet Chart - Category labels behaviour

### ISSUE THREAD

**Issue by cpassnat** [okviz/free-visuals#44]
Hello,

It would be nice that category label behaves like X-axis in stacked colum chart (smarter disposition) to optimize space and for better readibility.

![category labels disposition](https://user-images.githubusercontent.com/43177082/62630946-2ad9db00-b930-11e9-8779-dbb8253811d7.png)

**Comment by danieleperilli** [comment]
The orientation is automatically defined according the visual size. You can try to disable the Auto fit option in the Category label section to enable rotation.

**Comment by cpassnat** [comment]
I tried with auto fit off but it will display labels horizontaly and truncate them. I tried several options but I cannot get the same behaviour as stacked colum chart.
I included a sample pbi file as example
[BulletChartTest.zip](https://github.com/okviz/free-visuals/files/3486954/BulletChartTest.zip)

![BulletChartTest](https://user-images.githubusercontent.com/43177082/62789642-a6bb5b00-bac9-11e9-825e-3a6e48b24609.png)
