### ISSUE TITLE
Smart Filter - Sorting when adding multiple filter variables

### ISSUE THREAD

**Issue by indepthinsight** [okviz/free-visuals#45]
Morning,

when you have multiple fields listed in the Smart Filter, it only sorts the top one. The rest seem to be in a random order.

you can switch order of the fields and which ever is top, is sorted.

Is there something we can do to enable all the fields to be sorted individually.

**Comment by indepthinsight** [comment]
![sort4](https://user-images.githubusercontent.com/53933349/62763260-05111b00-ba83-11e9-9d11-b25ce65b04a9.JPG)
![sort1](https://user-images.githubusercontent.com/53933349/62763261-05111b00-ba83-11e9-9848-c02fb65b67aa.JPG)
![sort2](https://user-images.githubusercontent.com/53933349/62763262-05a9b180-ba83-11e9-8258-a157a11b13d1.JPG)
![sort3](https://user-images.githubusercontent.com/53933349/62763263-05a9b180-ba83-11e9-9bc1-d0ca50dd9d9e.JPG)

**Comment by indepthinsight** [comment]
Wouldn't let me add a .pbix file, so have attached screen shots of a sample file.

**Comment by danieleperilli** [comment]
Smart Filter Free sorts records only by the first field whereas Smart Filter Pro uses the standard sorting method, in which you can define the sorting field. I suggest you to try the Pro version and let me know if it works as needed.

**Comment by indepthinsight** [comment]
appreciate the quick response - the Pro version isn't an option for me but appreciate you clearing that up.

Thanks.
