### ISSUE TITLE
Card with States - Background state not applying

### ISSUE THREAD

**Issue by jpkgcp** [okviz/free-visuals#47]
I am using version 1.4.2.  In my attached example, I have a measure totaling 1,836,274 and a State equaling 1,860,000.  Under States formatting I have set a comparison of >= for the Background with the color set to green and a defined base color of red, but the background remains white.  However, the Data Label is changing color even though I have not assigned these colors to Data Label.
However, in the example, the card displaying Last Week is changing background colors as expected using the State formatting.
Any suggestions?
[BkgndErrorSample.zip](https://github.com/okviz/free-visuals/files/3494282/BkgndErrorSample.zip)

**Comment by chenvoo** [comment]
I have the exact same issue

**Comment by danieleperilli** [comment]
We already fixed this issue in the latest version of the visual, currently under review by Microsoft (we don't know the ETA).
