### ISSUE TITLE
Synoptic Panel - SVG file Objects not working correctly.

### ISSUE THREAD

**Issue by mkinnunen99** [okviz/free-visuals#49]
I cannot get any custom SVG visuals to work within Synoptic Panel. I've tried updating the ID in InkScape and Illustrator. 

Are there any example SVG files with a small dataset to check if this is a configuration issue on my end?

**Comment by danieleperilli** [comment]
Have you followed the tutorial here? https://okviz.com/blog/introducing-synoptic-panel-v1-4/

**Comment by mkinnunen99** [comment]
Yes, several different times and ways. Do you have an SVG visual configured
with a dataset that you can confirm works. Just three data points would be
fine.

Regards.

**Comment by danieleperilli** [comment]
You can get the sample file from this link: https://store.office.com/addinsinstallpage.aspx?rs=en-US&assetid=WA104380873

**Comment by mkinnunen99** [comment]
My apologies for the delay. That helped a lot and I got it working.

As a side note, I don't know if this is the right forum but I did come
across two bugs which I'm not sure if you're aware of:
1. The dropdown map option, when you have several maps in the visual,
doesn't seem to work on the mobile app
2. The image gets cut off at the bottom when you activate the legend and
doesn't resize/center properly. If you're going to use the Legend you need
to create an image that has space at the bottom (i.e. an invisible object
below the image to make sure the entire image stays visible)

Thanks again for all your help.

Mike Kinnunen
Tel: 647-216-2525

**Comment by modi123p** [comment]
Hi,
 I have embed multiple svgs as data uris.
Each one dispalys fine individually. However, when the maps field is bound, only one image gets displayed and option to filter is not displayed in the toolbar.

Using the latest version of Synoptic panel and PNG/ SVG files are attached for reference.
The SVGs were designed using Synoptic Panel designer. Any suggestions would be very much appreciated

[For Query (2).zip](https://github.com/okviz/free-visuals/files/4400893/For.Query.2.zip)

Question posted in PBI Communities:

https://community.powerbi.com/t5/Desktop/Synoptic-panel-by-OkViz-Selecting-embedded-image-to-filter-data/td-p/997620

**Comment by danieleperilli** [comment]
@modi123p  Please provide the sample file

**Comment by ba325** [comment]
@danieleperilli @modi123p was this problem ever resolved? I'm having a similar situation with dynamic embedded maps, where the map doesn't change when I filter with a slicer, only if I select by drop down.
