### ISSUE TITLE
Card with States - Layout broken/ layout options disappear when not connected to internet

### ISSUE THREAD

**Issue by Xtinction** [okviz/free-visuals#50]
I think I found an amusing bug in the Cards with states visual. When I'm not connected to the internet and I open a report with the "Cards with states" visual, it resets some of the layout settings, most importantly the Variance - Bottom option, which puts the variance number below the main value. When you go to the details of the visual, the option to put the variance below the value is no longer there.

When I reopen the file when connected to the internet again, all is well. Maybe this is something connected to licensing? If it cant check for a licence, it removes some options? Shouldn't happen on the free version I guess.

Thanks for an otherwise great visual!

**Comment by danieleperilli** [comment]
Please provide a sample report/screenshot/screencast. The visual is free, no license is issued. It could be a platform bug.

**Comment by Xtinction** [comment]
Sorry for the long wait. I first made a screencast but wasnt happy with it, and then when i made a new one, this bug dit not occur again. Lucky me :(. It might have something to do with having another powerBI file open at the same time, because later I was able to make a new screencast with the bug in it :)

https://youtu.be/x2la2iFJP1o

Sorry for the noisy office, didn't know it was recording that too. Sound off :D

**Comment by danieleperilli** [comment]
Strange... never saw before. Anyway, we already sent a big update to Microsoft a few weeks ago (they are reviewing it). I suggest you to wait for its release and re-test it, because this new version uses the latest API and libraries.
