### ISSUE TITLE
Synoptic Panel - Tooltip report page

### ISSUE THREAD

**Issue by WKNSTG** [okviz/free-visuals#51]
Hi,

I was wondering if it was possible to have the tooltip function available in the synoptic panel where you could create a graphical tooltip when hovering over a panel.
![image](https://user-images.githubusercontent.com/54435425/63580056-3960fd00-c594-11e9-9ee2-c4772200939d.png)

**Comment by danieleperilli** [comment]
It is a feature we will include in the next version, but we didn't planned a release date yet.

**Comment by WKNSTG** [comment]
Great! We are looking forward to it!

**Comment by harmenverburg** [comment]
Any idea when this will be released? If we could disable the default tooltip provided by PowerBI would be nice as well.

**Comment by franmer** [comment]
> It is a feature we will include in the next version, but we didn't planned a release date yet.

Any updates on this, Daniel? Would be really nice to have this feature.

**Comment by ntf1992** [comment]
> It is a feature we will include in the next version, but we didn't planned a release date yet.

Dear Daniele,
are there any news on the planned update for adding own tooltips to the Synpotic Panel ? 

All the best
Nico

**Comment by Ar3s701** [comment]
Would love to see an update to this visual. This is the single visual that made me switch from Tableau to PowerBI. The tooltip feature would be a great addition for my silly little project.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
