### ISSUE TITLE
Synoptic Panel - Data Labels appear in the wrong position

### ISSUE THREAD

**Issue by Mike-Honey** [okviz/free-visuals#52]
When I turn on Data Labels, they appear in the wrong position.  They are far below their area, and in a large font size.  See 2nd page in attached PBIX file. SVG file is also attached.

[Synoptic Panel questions 2019-08-25.zip](https://github.com/okviz/free-visuals/files/3538021/Synoptic.Panel.questions.2019-08-25.zip)

**Comment by danieleperilli** [comment]
I checked your SVG and there are a few issues. For example, it contains the same bitmap image twice. 
I tried to remove its viewBox and I got this: 
<img width="868" src="https://user-images.githubusercontent.com/9072177/63749887-ad5d1700-c8ac-11e9-8908-d38aeeb7f97a.png">
Probably when you exported the image from Inkscape some options affected the rendering or Inkscape itself is not so reliable.

I tried to open it in Adobe Illustrator and, after throwing some errors, it repaired the image successfully. Unfortunately, during the process all the areas id have been removed, so you have to assign them again. 
You can use this image: [fixed-CMI-diagram.zip](https://github.com/okviz/free-visuals/files/3544833/fixed-CMI-diagram.zip)

I have done it with a single area just to test and it works:
<img width="1282" src="https://user-images.githubusercontent.com/9072177/63750555-f497d780-c8ad-11e9-9d3a-c01050906dc6.png">

**Comment by Mike-Honey** [comment]
Thanks so much for your help Daniele - I guess I made a real mess of that SVG !
