### ISSUE TITLE
Bullet Chart - Mobile Drill In Not Available

### ISSUE THREAD

**Issue by Nate432** [okviz/free-visuals#54]
When using this visual on a mobile app you are unable to press on a parent value to drill down and see it's children. You are only able to show next level or expand to next level, not press and hold on a parent value and drill into it like other native visuals allow on mobile. You can turn on drill down on desktop and on the browser but not in the mobile power bi application (tested using an iphone XR).

**Comment by danieleperilli** [comment]
Solved in version 2.2.0. It will be released in a couple of months (unfortunately it doesn't depend on us - the Microsoft review process is very long).
