### ISSUE TITLE
Bullet chart - decimail point format

### ISSUE THREAD

**Issue by hosznyak** [okviz/free-visuals#55]
Hi, in Hungarian, the decimal point is a comma, not a dot. The regional settings in the PowerBI file is Hungarian (Hungary), but on the data label, on the tooltip the decimal point is a dot, not a comma. It is possible to update it? Thanks.

**Comment by danieleperilli** [comment]
We already fixed it in the latest version of the visual. It is currently under review by Microsoft and, hopefully, it will be released in 3-6 weeks.
