### ISSUE TITLE
Smart Filter - Pro advertisement displaying on exported reports

### ISSUE THREAD

**Issue by Joshua-Hammond** [okviz/free-visuals#57]
Hello. 
The "This report contains a theme. Themes are supported by **Smart Filter Pro** only. Upgrade now" message is displayed on reports that are exported from Power BI desktop using the "Export to PDF" functionality. While I understand the desire to up-sell customers to the premium version of the product, this advertisement completely detracts from the content of reports. It appears that theme support in the Pro version is a recent development as our reports, which were authored using the free visual, did not promote the Pro version until recently.

Could you please consider removing this advertisement or devising a way to prevent it from being shown on report exports?

![Screenshot](https://user-images.githubusercontent.com/37918389/64185131-984b2f80-ce3a-11e9-9862-79d85a70b9d3.png)

**Comment by danieleperilli** [comment]
There is an option in the properties of the visual to disable that message.
<img width="331" alt="Development_-_Smart_Filter_Pro_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/64186535-4a045380-ce6f-11e9-8732-0fb40ab31494.png">

**Comment by Joshua-Hammond** [comment]
Thank you for your assistance, Daniele!

Thanks,
Josh
