### ISSUE TITLE
Synoptic Panel - Filter by Measure

### ISSUE THREAD

**Issue by tkendrew** [okviz/free-visuals#58]
Currently if you select a panel it filters other visualizations on the page by Category. 
Would it be possible to have a feature that allows filtering to occur based on the Measure when a panel is selected?

This would assist when the Data Label is set to display value, you could then filter you page by the value displayed in panel rather than the entire data set that falls under the Category of that panel.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
