### ISSUE TITLE
Card With States - Needs Tooltip support

### ISSUE THREAD

**Issue by simpsonk512** [okviz/free-visuals#59]
Tool tips both regular a report based should be supported like the default card. This would allow users to see additional information like the comparison value.

**Comment by danieleperilli** [comment]
The next version will support report tooltips.

**Comment by simpsonk512** [comment]
Any updates on the next release? Thanks

**Comment by danieleperilli** [comment]
Unfortunately, it is still under review by MS.

**Comment by simpsonk512** [comment]
It's been 5 months since this ticket was closed and still no update? What can be done to make the new version available? Can you make it available it uncertified for now?

**Comment by danieleperilli** [comment]
Still under review, sorry.

**Comment by simpsonk512** [comment]
Daniele,
It looks like the new version has finally made it into the AppSource repository. However, Looks like you may need to update your web site now though as it says version 1.6.2.0 requires a free license for advanced features but no information or capability was available for that when I visited the OkViz website. In addition when I installed it, it still shows version 1.4.2.
Really looking forward to this new functionality.
Thanks,
Ken

[cid:image001.png@01D5EE53.A13DDD20]

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by marcosqlbi** [comment]
Ken, did you import Card with States from AppSource in Power BI Desktop? It is currently version 1.4.2, the new version is mentioned on the AppSource website but it should take 2-3 weeks before being deployed. I tried now and I still get the version 1.4.2.
Please can you clarify how did you download the version 1.6.2?
Thanks!

**Comment by simpsonk512** [comment]
Hello Marco,
I’m impressed and honored to have you respond personally!
AppSource accessed via add visuals from Power BI Desktop shows that the latest version is 1.6.1 as you can see below. Are you saying that even though this page has been updated they are still only providing 1.4.2 like before? When installed the About does show version 1.4.2.
Thanks for the quick response.
Ken
[cid:image003.png@01D5EE5E.D29A6D10]

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by marcosqlbi** [comment]
Indeed - when you download it is still 1.4.2 version, the web page will be updated on time when the 1.6.2 version will be actually downloadable from AppSource.
Thanks!

**Comment by simpsonk512** [comment]
Hello Marco,
It seems that the status of the new version of Card with states is even more complex now. Per this thread I had tried to download the new 1.6.2 version that showed available in App Source and it still showed it was only installing 1.4.2 as we discussed.

However, a report that I published after doing that las week is now showing version 1.6.2 in the service without my redeploying it since last week. This is a bit disconcerting since the formatting changed slightly and I didn’t really get a change to validate the changes before they showed up in my published report. In addition, some of the features require that sign up page which is not live on your web site yet. Any help would be appreciated.
Thanks,
Ken

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by simpsonk512** [comment]
Unfortunately, it appears that the new version is not honoring the number of decimal places selected for the Reference anymore.

Visual

Setting

[cid:image002.png@01D5F643.B3CDAC20]
Previously (on version 1.4.2) this was showing a variance of 8.5% with these same settings.

[cid:image003.png@01D5F643.B3CDAC20]




Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

From: Simpson, Ken J. [US-US]
Sent: Monday, March 09, 2020 6:40 PM
To: 'okviz/free-visuals' <reply@reply.github.com>; okviz/free-visuals <free-visuals@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: EXTERNAL: Re: [okviz/free-visuals] Card With States - Needs Tooltip support (#59)

Hello Marco,
It seems that the status of the new version of Card with states is even more complex now. Per this thread I had tried to download the new 1.6.2 version that showed available in App Source and it still showed it was only installing 1.4.2 as we discussed.

However, a report that I published after doing that las week is now showing version 1.6.2 in the service without my redeploying it since last week. This is a bit disconcerting since the formatting changed slightly and I didn’t really get a change to validate the changes before they showed up in my published report. In addition, some of the features require that sign up page which is not live on your web site yet. Any help would be appreciated.
Thanks,
Ken

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by danieleperilli** [comment]
Do you have any reports you can share with us? Several users reported this bug, but we can't fully understand the problem. In the meantime, we asked Microsoft to roll back the previous version.

**Comment by simpsonk512** [comment]
Hello all,
I just noticed your web site is updated to show the latest version of Card with States as 1.6.4. However, I’m having difficulty getting that version. I am really eager to get the updated version so just trying to understand where we are at.

·        When I installed to Power BI from the App Store today I still got version 1.4.2

·        When I downloaded the latest version from your site link I got version 1.6.2.0 (cardWithStatesByOKViz.PBI_CV_7B952816_A48F_49B4_9E13_15E3BB2C0337.1.6.2.0)

·        When I logged into my Downloads page on OkViz where I subscribed to the premium features, I was offered version 1.4.2 again
Subscription

Product

Version

License

Download

#546989

Card with States

1.4.2

Licensee name: Leidos - simpsonk@leidos.com

cardWithStatesByOKViz-1.4.2-priv_546989.zip<https://okviz.com/?download_file=4491&order=wc_order_cZbo8A7jzTcdN&email=simpsonk%40leidos.com&key=598be2f5-7967-4fde-8f87-65981e8d44f9>

Thanks,
Ken

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

From: Simpson, Ken J. [US-US]
Sent: Monday, March 09, 2020 6:40 PM
To: 'okviz/free-visuals' <reply@reply.github.com>; okviz/free-visuals <free-visuals@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: EXTERNAL: Re: [okviz/free-visuals] Card With States - Needs Tooltip support (#59)

Hello Marco,
It seems that the status of the new version of Card with states is even more complex now. Per this thread I had tried to download the new 1.6.2 version that showed available in App Source and it still showed it was only installing 1.4.2 as we discussed.

However, a report that I published after doing that las week is now showing version 1.6.2 in the service without my redeploying it since last week. This is a bit disconcerting since the formatting changed slightly and I didn’t really get a change to validate the changes before they showed up in my published report. In addition, some of the features require that sign up page which is not live on your web site yet. Any help would be appreciated.
Thanks,
Ken

Kenneth J. Simpson | Leidos
Senior Business Intelligence Manager | Business Insights & Optimization Solutions (BIOS)
phone:  469.322.2863
simpsonk@leidos.com<mailto:simpsonk@leidos.com> |  leidos.com<http://www.leidos.com/>

[cid:image001.png@01CEF746.A8FF7B50]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by danieleperilli** [comment]
The new version is not yet available on the marketplace. You can download the private version (1.6.4) from this link: https://okviz.com/wp-content/okviz/pbiviz/free/cardWithStatesByOKViz-1.6.4-priv.pbiviz
