### ISSUE TITLE
Card With States - Long Load Times for Visual

### ISSUE THREAD

**Issue by simpsonk512** [okviz/free-visuals#60]
Performance analyzer says it takes 6-7 seconds to render this visualization. It can take longer when multiple Card With States visualizations are used on the same page. Is there a way to improve the performance of the rendering?

**Comment by danieleperilli** [comment]
I suggest you to wait the next version of the visual. It should be released in a couple of weeks. It is more responsive and has a multiple cards layout (so you can use a single visual with different measures).

**Comment by simpsonk512** [comment]
Any updates on the next release? Thanks
