### ISSUE TITLE
Smart Filter - Filtering issue

### ISSUE THREAD

**Issue by ctspradeep** [okviz/free-visuals#61]
Smart filter all versions including 1.2.5 is not filtering column which has text data type. This was working fine in earlier versions before Smart filter pro update.

**Comment by danieleperilli** [comment]
Please, provide a sample file.

**Comment by ctspradeep** [comment]
PFA

**Comment by danieleperilli** [comment]
I don’t see any attachment.

**Comment by ctspradeep** [comment]
rename the attached zip to pbix for your use.
[Data.zip](https://github.com/okviz/free-visuals/files/3595154/Data.zip)

**Comment by ctspradeep** [comment]
HI Daniele,

https://github.com/okviz/free-visuals/files/3595154/Data.zip

Thanks

**Comment by danieleperilli** [comment]
I checked your file and found the bug. It is not related to numbers but to the structure of your data model. I fixed the issue in our code and just sent a new version to Microsoft. 
The v1.2.6 will fix the issue.

**Comment by ctspradeep** [comment]
Hi Daniele,

Is it possible to get 1.2.6 (fixed version) to me for immediate use? I am
not sure estimated date to reach your latest changes to marketplace.

Thanks,
Pradeep J
716-430-4182(M)

**Comment by ctspradeep** [comment]
Thanks . Will check it out
