### ISSUE TITLE
Smart Filter - Require a version compatible with PBI Desktop August 2018

### ISSUE THREAD

**Issue by mixtaman** [okviz/free-visuals#62]
As I am using Power BI Desktop August 2018 due to using Power BI Report Server I am unable to upgrade to latest version of PBI Desktop.  I require a previous version of Smart Filter in order to use this with August 2018 version - can anyone assist please?

**Comment by danieleperilli** [comment]
Sorry, we don’t support previous versions of Smart Filter Free anymore, so we decided to not provide them. You can try the Pro version  that is built with an API compatible with your server. Also, Pro customers can access all releases (including the previous ones). More info at https://okviz.com/smart-filter-pro/
