### ISSUE TITLE
Card with States - Wrap text

### ISSUE THREAD

**Issue by oelghira** [okviz/free-visuals#63]
I not only use the card with states to display numbers but also specific messages to my power bi users based off their filter selections. Currently there is no option to wrap text in the card with states visual. 

Could the wrap text ability could be added to the card with states visual?

**Comment by danieleperilli** [comment]
Currently is not supported. We will consider for next updates.

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
