### ISSUE TITLE
Bullet Chart - Line Targets (Vertical Orientation) 

### ISSUE THREAD

**Issue by WillRod36** [okviz/free-visuals#64]
The line targets do not work on vertical oriented graphs when the target is the same as the max. 
Please see the attached; the first graph shows the issue; second graph shows that targets appear when changed to crosses; third graph shows that line charts show (when target = max) on horizontal charts. (Note - all graphs have the same underlying data; all changes are listed)

Also, see attachment 'Graph4' where the targets show when the axis is changed from AUTO to a fixed 'END' number (above target)

![IssueOne](https://user-images.githubusercontent.com/38290353/65722597-90b62980-e07a-11e9-8406-3690b8c70805.png)
![GraphFour](https://user-images.githubusercontent.com/38290353/65722816-1639d980-e07b-11e9-90d0-41076116d31d.png)

**Comment by danieleperilli** [comment]
It has been solved in the v2.2.0. It is currently under review by Microsoft and it will be released in 3/4 weeks (hopefully).
