### ISSUE TITLE
Smart Filter - Filter issue on Power BI Report Server

### ISSUE THREAD

**Issue by emub00** [okviz/free-visuals#65]
When deployed to the report server, the Smart Filter is not applying the filters as per design. It works well in Power BI Desktop - this is why it is difficult to attach an example, because when working in Power BI desktop, the visual works just fine.
We are using the PowerBI Report Server September 2019 release (15.0.1102.597) and replicated this 
using both version 1.2.5 and 1.2.6(beta) of the visual. Thanks for your insight on this!

**Comment by danieleperilli** [comment]
Can you provide a screencast that reproduce the issue?

**Comment by emub00** [comment]
Thanks for the quick response Daniele!
This is how it works in the Power BI Desktop - showing an unfiltered view and a  filtered view, for comparison:
![image](https://user-images.githubusercontent.com/4396471/65962025-c87bf300-e425-11e9-90f9-89a682d77eaf.png)

The same file deployed to the server with no filter applied. Trying to apply the filter, while on the server:
![pbi server](https://user-images.githubusercontent.com/4396471/65962140-0aa53480-e426-11e9-8d35-a65976fa4bb3.png)

In addition, if I deploy the file to the server with a filter applied in the desktop, the filter stays applied, but the filter visual becomes unusable (blank region on the left):

![pbi desktop - filter applied](https://user-images.githubusercontent.com/4396471/65962246-3fb18700-e426-11e9-8422-ac9ea24a0144.png)

I have also created a small sample file with both versions of the visual available. The file exhibits the same behaviour when deployed to our report server.

[tst.zip](https://github.com/okviz/free-visuals/files/3676207/tst.zip)

Thanks for looking into this.

**Comment by Ankerok4** [comment]
Hello, Daniel!
I have same problem as emub00. I've tried current stable and beta version of smart filter. All other versions of software is September 2019 (PBI optimized and Server).
Please fix asap.

**Comment by emub00** [comment]
Checking the Power BI Report Server blog it looks like the issue is widespread across multiple types of filter / slicer visuals. It seems that only the built-in filters are working...Tested and confirmed that it is correct.

**Comment by danieleperilli** [comment]
Thanks for the update.

**Comment by danieleperilli** [comment]
Reference: https://community.powerbi.com/t5/Report-Server/Text-Visual-not-working-in-PBIRS-September/td-p/804487

**Comment by emub00** [comment]
There is a platform update for the September 2019 PowerBI Report Server (15.0.1102.620) that fixes the issue with this and other custom filter visuals.
