### ISSUE TITLE
Synoptic Panel - Colors do not work properly when a slicer is applied and saturation is enabled

### ISSUE THREAD

**Issue by ndsch** [okviz/free-visuals#67]
**Starting point:**
Synoptic Panel with saturation in data colors enabled (default color: orange; unmatched color: green)

**Description of the error:**
When selecting a certain element in a slicer, the following correct behaviour occurs: 

![slicer_applied_first_time](https://user-images.githubusercontent.com/56300782/66389779-7f99e080-e9c9-11e9-9d3f-4936c222342d.JPG)

When deselecting the element in the slicer and applying it again, the visual is behaving correctly. But if another element in the slicer is chosen and then the first element in the slicer is selected again, the following error occurs:

![slicer_applied_second_time](https://user-images.githubusercontent.com/56300782/66390219-7fe6ab80-e9ca-11e9-9c9d-ea92e8b1cd64.JPG)

Although the visual recognizes the matched value (area 10), it does not change its color to orange, but keeps green. This behaviour does only occur when saturation in data colors is enabled.

**Comment by danieleperilli** [comment]
Please, provide a sample file.

**Comment by ndsch** [comment]
here is a sample file which contains the pbix file, the data and the svg file:
[sample_file.zip](https://github.com/okviz/free-visuals/files/3755420/sample_file.zip)

Because the file from my first comment above is confidential, I created a new sample file. Therefore I will slightly adapt the problem description:

**Starting point:**
Synoptic Panel with saturation in data colors enabled (default color: green; unmatched color: red)

**Description of the error:**
When selecting a certain element in a slicer (in this case "name = B" and "binary = True") , the following correct behaviour occurs:

![image](https://user-images.githubusercontent.com/56300782/67284426-d62d1180-f4d5-11e9-873b-e3b6cbb25d06.png)

When deselecting the element in the slicer (binary = True) and applying it again, the visual is behaving correctly. But if another element in the slicer is chosen (in this case binary = False) and then the first element in the slicer is selected again (binary = True), the following error occurs:

![image](https://user-images.githubusercontent.com/56300782/67284555-17252600-f4d6-11e9-8e57-ff4640f62a59.png)

Although the visual recognizes the matched value (area 5), it does not change its color to green, but keeps red. This behaviour does only occur when saturation in data colors is enabled.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
