### ISSUE TITLE
Bullet Chart and Sparkline - Performance Issues

### ISSUE THREAD

**Issue by kamal-axtria** [okviz/free-visuals#68]
Hi,

We are having performance issues with Bullet Chart and Sparkline visuals. We reached out to Microsoft support and were told that these visuals were built using Power BI API 1.x. 
API 2.x is the latest one and visuals created through same should be a lot faster. 
Could you please migrate these visuals to API 2.x and perform any other performance optimizations if possible?

Thanks,
Kamal Manchanda

**Comment by danieleperilli** [comment]
The Bullet Chart visual has been already migrated and we are waiting for Microsoft approval (it could take up to 2 months).
The Sparkline visual has not been migrated yet and I don't think it will receive an update before Q1 2020.
