### ISSUE TITLE
Synoptic Panel - Issue with State panel

### ISSUE THREAD

**Issue by ericfromPCL** [okviz/free-visuals#69]
I have an example attached...

I'm trying to color a synoptic panel based on the state of the row.

State A = Blue; State B = Green, etc.

I have the visual using states and the states are being colored correctly.

The issue I have is when in the designer...when you open up the States area to choose the color...the panel seems to display one choice for each state for each row in the data.

If I have 500 rows and 11 states...the visual seems to try to display 5,500 color selectors. The same 11 states are displayed over and over. Power BI sometimes runs out of memory occasionally when opening the States panel. If Power BI does not run out of memory, then in Power BI the UI seems to almost lock up.

What I expect...
If I have 500 rows and 11 states...
When I open the states panel I would be given 11 states to set the color for.

[PANEL SAMPLE - Power BI Errors.zip](https://github.com/okviz/free-visuals/files/3713819/PANEL.SAMPLE.-.Power.BI.Errors.zip)

Did I use the visual correctly?
Can I somehow configure the visual differently to get around this?
Is this a bug?

**Comment by danieleperilli** [comment]
It seems an issue related to your specific model and the fact that states are designed to work with measures. I think we can fix it in the next version - unfortunately, we didn't plan to release it anytime soon. I will update you here when we have a release date, in the meantime probably you can improve your model to obtain better results.

**Comment by ericfromPCL** [comment]
Daniele,

Thanks for the update. I only used measures as that seemed the only way I could get this to work.

I'm using an Azure Analysis Services model. Ideally I'm trying to do this in Power BI without updating the underlying model. I don't have the ability with an AAS model to add columns.

That being said if I need to update the model I will!

Ignoring what I've done...what is the preferred way to do this? You mentioned to update your model to obtain better results...but I'm not sure what changes to try...

**Comment by ericfromPCL** [comment]
Accidentally hit the close button...reopened!

**Comment by ericfromPCL** [comment]
Daniele,

I reread your original comments...

"It seems an issue related to your specific model and the fact that states are designed to work with measures."

I did use measures in the sample...

**Comment by danieleperilli** [comment]
Sorry, I'm not able to give any advice about data modeling at the moment, but because no one had this issue in the latest 3 years I supposed it is something it can be solved with a different model.
I know you used measures, but in a way that is not fully supported. It is a design issue on our side, we have to fix it.

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
