### ISSUE TITLE
Card with States - culture setting not working for variance

### ISSUE THREAD

**Issue by wtanis** [okviz/free-visuals#7]
Dear OKViz,

I reported this issue earlier. The variance element is not updated in the PBI service environment based on the culture setting set in PBI desktop.

The last time I got the response that this would be fixed in the new update. What is the current ETA of the new update with this fix? And when will it be certified?

**Comment by danieleperilli** [comment]
Same response. The issue has been fixed in the next version and the update will be submitted to Microsoft on the next week. The review process for publishing in the Marketplace and certification will take 2 or 3 weeks.
