### ISSUE TITLE
Sparkline - Tooltip Format

### ISSUE THREAD

**Issue by twynne1213** [okviz/free-visuals#70]
Hi - first off, appreciate all the hard work on this, love the custom visual. My issue relates to the tooltip - I have multiple measures in a single visual that are in different formats. Some are whole numbers, some are currency, some are percentages, etc. The tooltip seems to only reflect the format of the top value for all values. I can workaround by creating multiple visuals and stacking them as they then all retain the proper tooltip format, but somewhat inconvenient. Thoughts?

**Comment by danieleperilli** [comment]
Improving tooltips is in our backlog. Unfortunately, we higher priorities at the moment and I don't think we will release an update before the next year, sorry.

**Comment by twynne1213** [comment]
Understood, appreciate the quick response.

**Comment by danieleperilli** [comment]
Unfortunately, we have suspended the release of updates on this visual, except for security bugs. I have added an On-Hold tag and closed the issue; I will reopen it when we begin actively working on the project again.
