### ISSUE TITLE
Bullet Chart - Multiple targets can't have different colors

### ISSUE THREAD

**Issue by philInsight** [okviz/free-visuals#71]
Hello,

Basically as the subject mentions, I'm not able to set a different color for my second target.
The option to do so is there, but it's of no effect. 

I've noticed this issue was brought up before; Is this a known issue?

**Comment by danieleperilli** [comment]
Please provide a sample file to reproduce the issue.

**Comment by philInsight** [comment]
[Repro - BulletChart.zip](https://github.com/okviz/free-visuals/files/3739334/Repro.-.BulletChart.zip)

**Comment by danieleperilli** [comment]
Sorry, you can't assign multiple colors to different target markers.
