### ISSUE TITLE
Card with States - PowerBI Theme

### ISSUE THREAD

**Issue by ChristianEller** [okviz/free-visuals#73]
Hey guys, 

I love your Card with States. As we provide more and more Customers with it we need to format it with a PowerBI Theme. 

Could you please provide an Example how to set the formatting Options? 
Most urgent: Font, Fontsize, Hide category label = True

[Okviz_CardwithStates.zip](https://github.com/okviz/free-visuals/files/3755470/Okviz_CardwithStates.zip)

Also please note, that the culture setting de-DE and de-CH do not work. for x1000 still "K" is shown, not "Tsd." as expected.

Thank you!

**Comment by danieleperilli** [comment]
Unfortunately, custom visuals can only provide basic support to themes – font formatting is not included at the moment. The next version of Card with States (currently under review by Microsoft) will support colors defined in custom themes and will fix the issue about culture setting.
