### ISSUE TITLE
Bullet Chart - Cross report drill through

### ISSUE THREAD

**Issue by ctspradeep** [okviz/free-visuals#74]
Hi OKVIZ Team, 
I am unable to view drill through (cross report) option when I right click on Bullet char visual created by you. Could you add this feature or let me know any option to achieve drill though in Bullet chart.

Thanks in advance.
Regards,
Pradeep J

**Comment by danieleperilli** [comment]
The drill-through feature has supported by version 2.2.2 of the visual. It will be released the next week, hopefully.

**Comment by ctspradeep** [comment]
Hi Danielle,

Could you provide pbiviz file as attachment for my testing.

Thanks,
Pradeep J
716-430-4182(M)

**Comment by danieleperilli** [comment]
The new version will be available in the marketplace in a few days, please wait for the official release.

**Comment by ctspradeep** [comment]
Hi Daniele, I am not able to find the latest version 2.2.2 in marketplace.  Do you know exact date for us to use latest version?

**Comment by danieleperilli** [comment]
No, sorry. Microsoft doesn’t provide such as information.

**Comment by ctspradeep** [comment]
can i get pbiviz ?

**Comment by ctspradeep** [comment]
Hi Daniele,  latest version 2.2.2 in marketplace is not available. Could you provide me pbiviz?

**Comment by danieleperilli** [comment]
Please, wait for the official version. It would be released in a few days.

**Comment by ctspradeep** [comment]
Thanks Daniele. Waiting for more than 10 days. We are excited to see latest version.
