### ISSUE TITLE
Synoptic Panel - Map does not change when other tile filter the report - only when slicer filter

### ISSUE THREAD

**Issue by Yagelhen** [okviz/free-visuals#75]
Hello, 
I have several custom maps that replace accordingly to the user's choice - in the synoptic map.
When I filter the report by one of the SLICERS I can see the relevant map appear in the synoptic panel tile.
BUT, when I filter the report by other visual in the report the synoptic panel map is stuck and show the first map.
Please see the attached - PBIX & GIF that shows the unexpected behavior.

Can you help with that?
Thanks 
Yagel

[Unit Analysis.zip](https://github.com/okviz/free-visuals/files/3828308/Unit.Analysis.zip)
![selected categories1](https://user-images.githubusercontent.com/57348390/68542296-f9036500-03b3-11ea-8590-f115b1668353.gif)

**Comment by yagel-hen-40** [comment]
Hey @danieleperilli
Did you come across this issue?
Thanks 
Yagel

**Comment by C-Wedge** [comment]
Hi @yagel-hen-40,

I'm keen to know how you setup the above maps as I cannot get it right. I constantly get a SVG file error when I use the Map measure, but the files display when I select from Local Map. I'd appreciate any guidance/tips you may have.

Thank you

**Comment by Yagelhen** [comment]
Hey @C-Wedge , 
Thank for your replay, 
I dont know which map are you talking about, the geo map or synoptic map?
- Geo Map - it is ordinary map with regular filed in it
- Synoptic map - I saved the map charts in advance at a web address controlled by the end user's selection in the report. so if the end user choose building "A" than synoptic panel visual will present the related map.
It was clear enough for you? it helped you ?
Did you manage to open the file? 
I am here if you have more questions

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.

To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
