### ISSUE TITLE
Smart Filter - Not filtering multidimensional cubes, SSAS

### ISSUE THREAD

**Issue by adamGallard** [okviz/free-visuals#76]
I am trying to filter using a dimension from SSAS through a gateway as a direct connection, I can see all of my values in my dimension but when I filter using the smart filter nothing happens, I have checked to see if the filter interactions are correct. if I filter using PowerBI's slicer it works fine. I have also tried both 1.2.5 and 1.2.6 neither work.
![image](https://user-images.githubusercontent.com/47691041/68733180-93b4ab80-0621-11ea-9897-6e4031169f7a.png)

**Comment by danieleperilli** [comment]
Hi Adam, sorry for the late relpy. Unfortunately, we are currently not able to test and reproduce the issue. Can you try to use our Pro version (you can get a free trial)

**Comment by adamGallard** [comment]
Yes I can confirm this is the same issue with the Pro version 2.1.0_445120

Adam

**Comment by adamGallard** [comment]
Hey is there any update on this, I am still having issues and my clients want to use your product, I am happy to demo the issue.

**Comment by danieleperilli** [comment]
No updates as far as we can't test it. Can you reproduce the issue in a sample report?

**Comment by adamGallard** [comment]
I have a sample report and login details for you, but I would prefer to send them directly, can you give me an email address to send them to.

**Comment by danieleperilli** [comment]
Of course: daniele.perilli@okviz.com

**Comment by marcosqlbi** [comment]
Adam, can you confirm that a regular slicer works in the same situation where you are not able to use Smart Filter Pro?

**Comment by adamGallard** [comment]
Yes , i can confirm that a regular slicer works correctly in the same situation.

**Comment by adamGallard** [comment]
thanks for your support, I have raised a support ticket with Microsoft, 120042323002656 I will let you know the outcome.

**Comment by adamGallard** [comment]
I have been speaking with Microsoft, they have asked for more information on the hidden fields that are needed to allow the filter to work. if you let me know I will pass them on to the support team at Microsoft.

**Comment by danieleperilli** [comment]
Sorry, Adam, what do you mean? Hidden fields?

**Comment by adamGallard** [comment]
you sent me an email a few days ago, that states: 

The problem seems the following: only the native slicer in Power BI correctly applies a filter to a Multidimensional model. Any custom visual is not able to do that, and we are not able to operate on that because there are additional hidden columns that are not provided to the custom visuals and are required to apply the filter correctly.

We think you should contact Microsoft to ask whether they have plans to support filters over Multidimensional through custom visuals.

Microsoft is asking what the "additional hidden columns" are that you have referenced in your email.

**Comment by danieleperilli** [comment]
Ok, Marco will reply about this later then.

**Comment by marcosqlbi** [comment]
Adam, when you connect to Multidimensional then Power BI uses fields with the suffix ".UniqueName" that are not exposed in the Power BI UI and are not made visible to the custom visuals. You can see an example of this syntax in this blog post: http://byobi.com/2017/08/ssas-multidimensional-and-super-dax/

**Comment by adamGallard** [comment]
Hi, I have had a response from Microsoft to say this is a known issue and is scheduled to be fixed by the end of the year!!! so we will just have to wait and see.  Thanks for your support.

**Comment by danieleperilli** [comment]
Thanks for your feedback!

**Comment by adamGallard** [comment]
Hey I see the new version of smart filter pro is now working with the issue I had, is there any roadmap for the fix to be applied to the free version?  Thanks
