### ISSUE TITLE
Bullet Chart - Legend Color Stopped Working

### ISSUE THREAD

**Issue by cbhoffm1** [okviz/free-visuals#77]
![Bullet Chart Formatting Issues 20191118](https://user-images.githubusercontent.com/47642807/69090122-fcc36700-0a05-11ea-8dd3-9f2459a50131.JPG)
The color of the legend no longer shows the correct color for the default value.

**Comment by cbhoffm1** [comment]
[OkVIz Bullet Chart Issues.zip](https://github.com/okviz/free-visuals/files/3860561/OkVIz.Bullet.Chart.Issues.zip)

**Comment by danieleperilli** [comment]
I do confirm it is a bug – a fix will be included in the next version. A temporary workaround would be displaying all the data colors.
<img width="182" alt="bullet-chart-222-axis-issue_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/69120932-31353280-0a9b-11ea-8c99-3df721bd73d8.png">

**Comment by danieleperilli** [comment]
This has been fixed in v2.2.3. You can try the beta from this link: https://okviz.com/wp-content/okviz/pbiviz/free/bulletChartByOKViz.2.2.3-beta.pbiviz

**Comment by cbhoffm1** [comment]
I uploaded the beta bullet chart into one of our dashboards and confirmed that the corrections are working.
Thanks

**Comment by danieleperilli** [comment]
Thanks for the feedback. The visual has been already sent to the Power BI team for the review.

**Comment by kjmar** [comment]
Hi - once published by PBI team will we need to do anything manually or will the fix apply automatically to all existing instances of this viz? 
Also, do you have an idea of how long it generally takes the PBI team to review and publish?

I use this great Viz in almost all our dashboards and I´m getting a lot of questions from confused users

Thanks and keep up the great work

**Comment by danieleperilli** [comment]
If you don't change the current visual with the beta I provided, then it will be automatically updated in all your reports. About the timing: usually, the PBI team review takes 4 weeks or even more. We already asked for a faster review. You can contribute by opening a ticket with their support, I guess.

**Comment by kjmar** [comment]
ok thanks

**Comment by kjmar** [comment]
feel free to pile on!

https://community.powerbi.com/t5/Issues/OK-viz-bullet-chart-BUG/idi-p/854362#M50997

**Comment by kjmar** [comment]
Hi Daniel

Just wanted to relay this message from PBI:
(you guys have already done this right?)

************************************************************************************

Re: OK viz bullet chart BUG 
Hi @kjmar, 
 
As the custom visual owner needs to send a submission request to Power BI Power BI visuals submission team (pbivizsubmit@microsoft.com), I would suggest you share your feedback to this team. See: https://docs.microsoft.com/en-us/power-bi/developer/office-store#submitting-to-power-bi
 
Best Regards,
Qiuyun Yu_**

**Comment by danieleperilli** [comment]
Of course, we did it.

**Comment by djurecic0** [comment]
I'm still seeing this behavior in v2.2.8. The legend color does not change.

![image](https://user-images.githubusercontent.com/76531789/112835558-6e360f80-9067-11eb-9410-ebc2ba8df25c.png)

![image](https://user-images.githubusercontent.com/76531789/112835533-67a79800-9067-11eb-8149-300d4e2e85d0.png)

**Comment by djurecic0** [comment]
It looks like changing the data color then changing it back will update the legend.

**Comment by cbhoffm1** [comment]
Hello, I would suggest you submit a new ticket for your use case.  I’m not sure what the expected functionality is with the conditional formatting. From: djurecic0Sent: Tuesday, March 30, 2021 8:32 AMTo: okviz/free-visualsCc: ChrisHoffman; MentionSubject: Re: [okviz/free-visuals] Bullet Chart - Legend Color Stopped Working ***@***.*** Sorry if this is the wrong forum. Is the Legend Color meant to change when conditional colors are used?Should the legend color for Total Sales USD be red to match the conditional color in the example below?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
