### ISSUE TITLE
Bullet Chart - Not displaying on IE 11

### ISSUE THREAD

**Issue by tommasopasini** [okviz/free-visuals#79]
It looks like Internet Explorer is not displaying the chart anymore on Power BI Report Server september 2019. Things work as expected in both Edge and Chrome. Clearing cache and temporary files does not help, and the issue is present across different PCs

![image](https://user-images.githubusercontent.com/131651/69151729-79744500-0adb-11ea-8b50-d068727c1ea5.png)

![image](https://user-images.githubusercontent.com/131651/69151790-a0327b80-0adb-11ea-8750-ee5113a0ff37.png)

**Comment by danieleperilli** [comment]
Unfortunately, it's a known issue. We are working on a fix. In the meantime, you can use the previous version from this link: https://okviz.com/wp-content/okviz/pbiviz/free/bulletChartByOKViz-2.1.6B.pbiviz 
Please note that the above build will be not updated automatically when a new release will reach the marketplace.

**Comment by tommasopasini** [comment]
Thanks, we'll try that!

**Comment by mamajoutt** [comment]
Version 2.1.6B works.
Thanks for providing work-around.

**Comment by danieleperilli** [comment]
We just released a new version working with IE: https://okviz.com/wp-content/okviz/pbiviz/free/bulletChartByOKViz.2.2.3-beta.pbiviz

**Comment by PARDESIP** [comment]
Hi All , Is there any other approach rather than using the new version of the Visual ? Since all the reports which are live currently to users has to be reworked. Thank you.

**Comment by j-vanderzell** [comment]
Is there a date when this will be available in the marketplace as a Power BI certified visual? My organization currently blocks non-certified custom visuals.

**Comment by danieleperilli** [comment]
Unfortunately, Microsoft doesn't provide such a date.

**Comment by danieleperilli** [comment]
Microsoft approved the new version on Dec 24, 2019, but it requires additional time to be deployed in the marketplace.

**Comment by danieleperilli** [comment]
The visual has been released in the marketplace today.

**Comment by GHS05** [comment]
The issue still persists can anyone help.
I have updated the latest bullet chart okviz from marketplace ,i dont see the visual in IE,Chrome or edge
