### ISSUE TITLE
File problems while uploading in Power BI

### ISSUE THREAD

**Issue by alexanderholz** [okviz/free-visuals#8]
Hi there, I've tried to Export a file of mine via Synoptic Designer into Power BI. Unfortunately it doesn't let me open the file (it's a .svg file). Any solution given on this one? Like converting into .pbiviz files? Thanks a lot! Best, A

**Comment by okviz** [comment]
You have to import it in Power BI by using Synoptic Panel. For more information, please refer to this article: https://okviz.com/blog/introducing-synoptic-panel-v1-4/
