### ISSUE TITLE
Bullet Chart - Dates : Category axis only shows days but not months

### ISSUE THREAD

**Issue by HaroldBartels** [okviz/free-visuals#82]

**Comment by danieleperilli** [comment]
Please provide a sample repro.

**Comment by HaroldBartels** [comment]
Hi Thanks for the fast reply,

here is an image, I would like to know to which Monat does the day corresponds

![image](https://user-images.githubusercontent.com/41052972/69536841-18d38500-0f7f-11ea-812c-6447b38a0524.png)

**Comment by danieleperilli** [comment]
Yes, it shows only categorized values. If you connect days it will show a number, if months, the month name and so on. We will consider your request for future updates.

**Comment by HaroldBartels** [comment]
Yeah, it would be usefull if the month could be seen just below the number of the day

**Comment by danieleperilli** [comment]
Closed since we moved issues/suggestions for Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen it there.
