### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by alokmitali** [okviz/free-visuals#83]
Is there a way to display the Target Value on the line itself.

**Comment by danieleperilli** [comment]
No, sorry. We will evaluate it in the future.

**Comment by alokmitali** [comment]
Any enhancement possibility in the near term if we engage actively to get this feature added.

**Comment by danieleperilli** [comment]
What do you mean exactly? Please write to support@okviz.com

**Comment by alokmitali** [comment]
What i meant was we can share the cost/pay for the feature to be developed to Display the Target Marker Value.

**Comment by danieleperilli** [comment]
We can evaluate it, please write to support@okviz.com describing your requirements.
