### ISSUE TITLE
Synoptic Panel - SVG file wont load to Power BI

### ISSUE THREAD

**Issue by annauk** [okviz/free-visuals#85]
Hey, 

I have this big file 1254kb svg marked with over 10k cells when uploading to the Power BI I am getting the Out of Memory message. Is there there any fix for this? 

Thanks

**Comment by annauk** [comment]
I have found it the solution. You need edit in Inkscape and flip over, save, voila works. Even with bigger size.

**Comment by artman696** [comment]
I'm having the same issue. I've spent an incredible amount of time plotting areas in Synoptic panel. When I try to upload into power bi I'm received an this error. Something went wrong. We're sorry. This report ran out of memory. Power BI destop will close now. Please restart. So if I use Inkscape what exactly would I need to do?
