### ISSUE TITLE
Bullet Chart - Tooltip and Culture Code

### ISSUE THREAD

**Issue by clusa7** [okviz/free-visuals#86]
Hi,
There is a problem with this visual. I change culture code to Spanish, but it doesn't change. Thousand separator remains the same.
Do you know any solution?
Thanks in advance,

**Comment by danieleperilli** [comment]
Can you provide a sample report?

**Comment by clusa7** [comment]
Of course!!! I'm going to attach a simple screenshot. :) 
Do you need more information?
<img width="960" alt="example_Culture_Code_Tooltip" src="https://user-images.githubusercontent.com/58388013/70516968-27ea3380-1b38-11ea-9f1b-4f4a23702789.png">

Thanks in advance.

**Comment by clusa7** [comment]
Yes, of course!!! 
I'm going to attach a simple screenshot.

<img width="960" alt="example_Culture_Code_Tooltip" src="https://user-images.githubusercontent.com/58388013/70517367-cc6c7580-1b38-11ea-9992-9d72a80fcf63.png">

Thanks in advance :)
