### ISSUE TITLE
Bullet Chart - sort order, show % in values

### ISSUE THREAD

**Issue by GijsvK** [okviz/free-visuals#88]
Hi Daniel, thanx for supporting this excellent viz.
I have two questions (see screenshot) 
- Instead of the actual value, I want to show the "% actual vs limit" as a number. I have this as a calculated column, but don't see how I can display it in the graph...
- the viz doesn't seem to honor my custom-defined sort order for the category?
Thanx, Gijs.

![bulletviz](https://user-images.githubusercontent.com/58604041/70341227-c46bb780-1852-11ea-85a7-a46cb1e263c1.PNG)

**Comment by danieleperilli** [comment]
Can you provide a sample file?

**Comment by GijsvK** [comment]
see attached zip file...
[data4viz.zip](https://github.com/okviz/free-visuals/files/3935498/data4viz.zip)

**Comment by GijsvK** [comment]
I just noticed something else: if I set a "comparison value" the data appears in a bar and shows up in the legend.  But the color in the legend is not the same as the color of the comparison bar!
Also the legend says "limit", shouldn't it say "comparison"?
thanx, Gijs.  (PS I know these vizualizations aren't simple to build - perhaps you've made it too powerful?)

**Comment by danieleperilli** [comment]
Sorry, I don't understand your first point. You can change the value of the bars to the % actual (you called Percent), but it doesn't work like the Clustered line and column chart, you don't have 2 seprate axes, you have to change also the Limit to a percentage. 
For the other point: you can change the sorting from the menu in the top-right menu, you can't define a custom order.

<img width="810" alt="bullet-chart-88_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/71336677-76d89580-2548-11ea-8b3b-3e142fc50074.png">

**Comment by danieleperilli** [comment]
About the problem with the legend: it is a known issue, solved in a new beta https://github.com/okviz/free-visuals/issues/77
