### ISSUE TITLE
Bullet Chart - Shows the numbers shifted in EDGE

### ISSUE THREAD

**Issue by HaroldBartels** [okviz/free-visuals#89]
If the visual is in Power Bi Desktop / Chrome, there is no problem, but EDGE shows the values shifted upwards. Therefore numbers appear chopped.

![image](https://user-images.githubusercontent.com/41052972/70802375-9be34080-1db1-11ea-8c2d-14c6f0382b4e.png)

**Comment by scrampy** [comment]
We are seeing the same issue on iPad/Safari both on iOS 12.4 and iOS 13.  Please let me know if I should file a separate bug.

![2020-01-13_08h47_09](https://user-images.githubusercontent.com/3229013/72263361-b3972a00-35e6-11ea-919d-f829fb1f24cd.png)
![2020-01-13_08h50_21](https://user-images.githubusercontent.com/3229013/72263375-ba25a180-35e6-11ea-9b6e-f38b73f6071c.png)
![2020-01-13_08h53_28](https://user-images.githubusercontent.com/3229013/72263386-c1e54600-35e6-11ea-9761-7c9cfdfa47d8.png)

**Comment by scrampy** [comment]
@danieleperilli do you think this issue might get fixed "soon"?

**Comment by danieleperilli** [comment]
The update is on its way to the marketplace. Unfortunately, it requires 4/6 weeks before is approved and released. Stay tuned.
