### ISSUE TITLE
Bullet Chart - Not resizing properly on Power BI Mobile

### ISSUE THREAD

**Issue by jonathanneo** [okviz/free-visuals#9]
Hi, 

I am using the Bullet Chart v2.1.6 and the visuals are not resizing properly on Power BI Mobile (published to a Power BI Service). The same issue appears on both Power BI App and Power BI Workspace when viewing the report on Mobile. See screenshots below. 

**What it looks like**
![What_it_looks_like](https://user-images.githubusercontent.com/16749633/56628646-2b9a7a00-667d-11e9-8fec-bd035bc2e47a.png)

The above is what it looks like when I first open the report containing the Bullet Charts. 

**What it should look like** 
![What_it_should_look_like](https://user-images.githubusercontent.com/16749633/56628651-33f2b500-667d-11e9-8f70-feb572d2dc85.png)

To get the Bullet Chart to resize correctly (like the above image), the user has to click on the chart(s) a few times and the chart will resize. But that isn't a good user experience, and doesn't immediately present stunning visuals to my end-users. 

**Q: Is it possible to fix Bullet Chart resizing on Mobile in the next version release?**

For your reference, below is a screenshot of what it looks like when I'm creating the visual in Power BI Desktop and some additional specifications. 

**What it looks like when I'm developing** 
![What_it_looks_like_developing](https://user-images.githubusercontent.com/16749633/56629040-ac0daa80-667e-11e9-83d9-8cac6e60e5c3.PNG)

- I am using a 6 x 2 grid for each Bullet Chart and resizing always seems to be a problem. 
- I've tested with a 6 x 4 grid for each Bullet Chart and resizing issues doesn't occur. 
- I am designing a mobile optimised report and flipping the mobile device landscape to switch to the desktop view is not an option. 

Thanks in advance for your time in reviewing this issue! 

Attached is a sample pbix file of the issue. 
[OKVizBulletChartSampleFile.zip](https://github.com/okviz/free-visuals/files/3130452/OKVizBulletChartSampleFile.zip)

**Comment by danieleperilli** [comment]
Closed since we moved issues with Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen the issue there if the bug still exists with version 2.2.9.4 or higher.
