### ISSUE TITLE
Synoptic Panel - CORS Issue

### ISSUE THREAD

**Issue by alreadygothub** [okviz/free-visuals#90]
I've enabled CORS on my site but due to the nature of the work we are doing we can't allow all (*) to access our site. I'm hoping we can to restrict the "Access-Control-Allow-Origin" to the required domain(s). Any chance you can tell me the domain to allow?

Thank you

**Comment by danieleperilli** [comment]
Probably, you just need to allow powerbi.com domains, because when the report is published on Power BI service, the maps run in a iframe hosted there.

**Comment by alreadygothub** [comment]
I'm actually using powerbi desktop. I tried allowing the powerbi server but
the images only work when I allow *. Is the request coming from my server
or from OkViz?

**Comment by okviz** [comment]
No, OKViz is not involved if you don’t use maps from our gallery.

Sent from my iPhone. Forgive the brevity, the typos and the lack of nuance.
________________________________

**Comment by alreadygothub** [comment]
Thank you, I'm finding now that I need to add the http request header to the origin header. Is that something that your users have experienced or am I off base. Does Synoptic Panel have a place to enter the header? 
![image](https://user-images.githubusercontent.com/36752656/71120185-b3933e00-2190-11ea-9d52-9c71e0292392.png)

**Comment by danieleperilli** [comment]
No, I'm sorry. The visual calls a GET from the iframe hosted on the powerbi.com domain (or from the internal browser of Power BI desktop - so is a local request), but you can't define the request header parameters. No users had reported the problem before, but I suppose they set the * in the CORS settings.

**Comment by alreadygothub** [comment]
thanks, maybe the answer is to store the images on Github, I saw that the sample image is no longer working. Is Github still a viable option for storing images.

Also thank you for responding so quickly to all my questions.

**Comment by danieleperilli** [comment]
Yes, it should work, also if the sample repo is not available anymore (I’m sorry, wasn’t aware of that).
