### ISSUE TITLE
Bullet Chart - no charts during subscription

### ISSUE THREAD

**Issue by toziz** [okviz/free-visuals#91]
Hello Daniele,

Since last week (Thu or Fri) there is no Bullet Charts presented on REPORT pages subscription. The space remaining empty. I've checked all three version Bullet Chart (2.1.6B, 2.2.2.0, 2.2.3-beta). 

What is interesting that in the same time DASHBOARD subscription produce proper results.

Many thanks. Cheers. 
Tomek

**Comment by danieleperilli** [comment]
Beta versions are not certified, so they cannot be included in emails or exported to PDF.

**Comment by toziz** [comment]
That I was supposed, but I've also tested stable version 2.2.2.0 (as the first one).

**Comment by danieleperilli** [comment]
Ok, thanks for the feedback. Other users are reporting the same issue with different custom visuals. I suggest opening a ticket on Microsoft support website.

**Comment by toziz** [comment]
Thanks Daniele.

**Comment by danieleperilli** [comment]
@toziz Do you have any update about this issue? Did you receive any reply from Microsoft?

**Comment by toziz** [comment]
Hi @danieleperilli,  
It was general issue. Details below: 
•	Service Request #: 119121822000086
•	Closed Date: 19-12-2019 11:43:56 UTC
Since then everything should be ok. 
Many thanks Daniele and all the best in New Year !

**Comment by danieleperilli** [comment]
Thanks for the feedback!
