### ISSUE TITLE
Area lable Issue

### ISSUE THREAD

**Issue by ChincholeSaket** [okviz/free-visuals#92]
Hello,

As per below image attached I want to change label name **Area** to some other name is that possible? Can you please suggest.

![image](https://user-images.githubusercontent.com/57440844/71803092-411fca80-3079-11ea-8a44-74bed86d714a.png)

Thanks in advance.

**Comment by danieleperilli** [comment]
No, it's not possible. That name is assigned when the area is not matched with your data and cannot be edited, sorry.

**Comment by ChincholeSaket** [comment]
Thanks Daniel for reply.
