### ISSUE TITLE
Bullet Chart - Tooltip - No conditional formatting

### ISSUE THREAD

**Issue by mpetot** [okviz/free-visuals#93]
Hello,
Really love the visual and thank you!
Found a small bug but wanted to post a workaround as well - If you use the Bullet chart as a tooltip, it will not give you the option to set up the conditional formatting for the data colors. BUT, you can create the chart on a regular Power BI page and copy/paste it over to the tooltip and it works!
Thanks, OKViz!

**Comment by danieleperilli** [comment]
That feature is not available yet in custom visuals
