### ISSUE TITLE
Card with states - Clicking data point does not change value of data label

### ISSUE THREAD

**Issue by JoshFlory** [okviz/free-visuals#94]
Firstly, thank you so much for your work in releasing these free visuals!

In Cards With States, when I click a data point, the tool tip will show the information about that data point but it does not update the value of the data label at the top of the card.

If I have 3 data points, 50%, 90%, 100%.  Clicking any of those points does nothing to change the card's value. 

I would have expected clicking the data point for 50% would have updated the card to show the 50% information.

Thank you for your help

**Comment by danieleperilli** [comment]
In the new version of the visual (that will be released in a few days in the AppSource) we introduced a new feature that works as you suggested but without the need of clicking – indeed, the label changes its value just by moving the mouse over the trendline.
