### ISSUE TITLE
Smart Filter - Dropdown menu should always be in front of other visuals

### ISSUE THREAD

**Issue by emilevanlier** [okviz/free-visuals#97]
Hi, 
I am using Smart Filter in a Power BI report. The customer wants to have the filter on the top-left of the page. When you click on the triangle to see the list of entries, it needs to fill up the page to the bottom. The problem is that it doesn't work as expected in the Edge browser. I have a button placed below the Smart Filter. When the Smart Filter dropdown list is open, you still see the button. This only happens in Edge. In Chrome it works correctly. 

I have added some screenshots as example, I hope the example is clear. 

Looking forward to your response, I hope you have a solution for this. 
[smartfilter_issue.docx](https://github.com/okviz/free-visuals/files/4071053/smartfilter_issue.docx)

**Comment by danieleperilli** [comment]
Are you using the modern version of Edge? Have you tried the Pro version of Smart Filter?

**Comment by emilevanlier** [comment]
Hi,
Thanks for your response!

  *   I do not use the Pro version of Smart Filter
  *   Version of Edge:

[cid:image001.png@01D5CC6E.032F7B90]

Best regards,
Emile



Met vriendelijke groet / Kind regards,
​
​CRM Partners​ BV
Emile van Lier
Consultant
 
Emile.van.Lier@crmpartners.com
+31 (6) 22180919

**Comment by danieleperilli** [comment]
The version is not visible and I’m suggesting to try the Pro version.
