### ISSUE TITLE
Smart filter Pro - filtered text disappears

### ISSUE THREAD

**Issue by fauves** [okviz/free-visuals#98]
Each time I switch between pages, the selection disappears from the filter, but the filter remains active

**Comment by danieleperilli** [comment]
This repo is for free versions of OKViz visuals. Is your issue related to the Pro version of Smart Filter?
Anyway, can you provide a sample file?

**Comment by fauves** [comment]
ok, sorry my bad. This issue is related to the pro version. In attach.
[issue.zip](https://github.com/okviz/free-visuals/files/4097971/issue.zip)

**Comment by danieleperilli** [comment]
Ok, please write to support@okviz.com. We need to know the version of the visual you're using, the browser or the version of Power BI Desktop and **a sample file, not just the screencast**.
