### ISSUE TITLE
Synoptic Panel - Embedding maps does not work

### ISSUE THREAD

**Issue by NewtonEhv** [okviz/free-visuals#99]
I cannot get the embed maps functions to work. The SVG is correctly loaded, but as soon as I add a Category of SubCategory field it says "Can't display the visual". If I only add a Maps field and a Measure field it displays a empty SVG (as expected) The datamodel is not the issue, if I import the SVG using the Local Maps folder it works fine. 

See attached file, Page 1 is a working and page 2 is broken
[Broken map.zip](https://github.com/okviz/free-visuals/files/4147046/Broken.map.zip)

**Comment by danieleperilli** [comment]
The problem is in the data model, not in the visual itself.
<img width="642" alt="bug-27-synoptic-panel_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/73645381-7cf98000-4677-11ea-97c3-52cbf39c36a8.png">

**Comment by NewtonEhv** [comment]
But why does it work when directly loading the image?

**Comment by danieleperilli** [comment]
Because that way the URL of the image is stored in a property of the visual, not in a measure. By using measures, you can't bound different tables that are not interconnected.
